### ISSUE TITLE
Traceback when tracking an element

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1012]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1012)
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Apr 26, 2019, 20:57

## Summary

With Buildstream 1.2.5, as well as the tip of the bst-1.2 branch, I get a traceback when tracking an element.

## Steps to reproduce

0. Use Buildstream 1.2 (I have not tried reproducing with the master branch)
1. `git clone https://gitlab.com/freedesktop-sdk/freedesktop-sdk`
2. `cd freedesktop-sdk`
3. `git checkout master`
4. `bst track components/libglvnd.bst`

## What is the current bug behavior?

The tracking seems to have worked fine, however I get a traceback.

It seems to be in the codewhich prints messages to the console.

## What is the expected correct behavior?

Tracking works, no traceback.

## Relevant logs and/or screenshots

```
$ bst track components/libglvnd.bst 
[--:--:--][][] START   Track
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[00:00:00][][] SUCCESS Resolving elements
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state

BuildStream Version 1.2.5+62.g162c4166
  Session Start: Friday, 26-04-2019 at 21:54:57
  Project:       freedesktop-sdk (/home/mathieu/Projects/desktop/freedesktop-sdk)
  Targets:       
  Cache Usage:   11.7G / infinity (6%)

User Configuration
  Configuration File:      Default Configuration
  Log Files:               /home/mathieu/.cache/buildstream/logs
  Source Mirrors:          /home/mathieu/.cache/buildstream/sources
  Build Area:              /home/mathieu/.cache/buildstream/build
  Artifact Cache:          /home/mathieu/.cache/buildstream/artifacts
  Strict Build Plan:       Yes
  Maximum Fetch Tasks:     10
  Maximum Build Tasks:     4
  Maximum Push Tasks:      4
  Maximum Network Retries: 2

Project Options
  bootstrap_build_arch: x86_64
  snap_grade:           devel
  target_arch:          x86_64

Loaded Plugins
  Source Plugins
    - git_tag

Pipeline

===============================================================================
[--:--:--][????????][track:components/libglvnd.bst       ] START   freedesktop-sdk/components-libglvnd/????????-track.15689.log
Exception in callback Job._parent_recv()
handle: <Handle Job._parent_recv()>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 642, in _parent_recv
    self._parent_process_queue()
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 634, in _parent_process_queue
    self._parent_process_envelope(envelope)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 606, in _parent_process_envelope
    self._scheduler.context.message(envelope.message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_context.py", line 376, in message
    self._message_handler(message, context=self)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/app.py", line 701, in _message_handler
    text = self.logger.render(message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/widget.py", line 593, in render
    return self._render(message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/widget.py", line 628, in _render
    text += widget.render(message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/widget.py", line 227, in render
    plugin = Plugin._lookup(element_id)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/plugin.py", line 659, in _lookup
    assert unique_id in cls.__TABLE, "Could not find plugin with ID {}".format(unique_id)
AssertionError: Could not find plugin with ID 215
Exception in callback Job._parent_recv()
handle: <Handle Job._parent_recv()>
Traceback (most recent call last):
  File "/usr/lib64/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 642, in _parent_recv
    self._parent_process_queue()
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 634, in _parent_process_queue
    self._parent_process_envelope(envelope)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 606, in _parent_process_envelope
    self._scheduler.context.message(envelope.message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_context.py", line 376, in message
    self._message_handler(message, context=self)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/app.py", line 701, in _message_handler
    text = self.logger.render(message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/widget.py", line 593, in render
    return self._render(message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/widget.py", line 628, in _render
    text += widget.render(message)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/_frontend/widget.py", line 227, in render
    plugin = Plugin._lookup(element_id)
  File "/home/mathieu/.local/lib/python3.7/site-packages/buildstream/plugin.py", line 659, in _lookup
    assert unique_id in cls.__TABLE, "Could not find plugin with ID {}".format(unique_id)
AssertionError: Could not find plugin with ID 215
[--:--:--][        ][track:components/libglvnd.bst-0     ] INFO    Found new revision: v1.1.1-0-gbc9990b7bede44899627354d0c356f48950f4ad1
[00:00:00][????????][track:components/libglvnd.bst       ] SUCCESS freedesktop-sdk/components-libglvnd/????????-track.15689.log
[00:00:02][][] SUCCESS Track

Resolved key Summary
     waiting 3d8725eac964652be6b2238c9ab2ad5aed5d1d087d4a3becd62095e35794dcf9 components/libglvnd.bst 

Pipeline Summary
  Total:       0
  Session:     1
  Track Queue: processed 1, skipped 0, failed 0 
```

* BuildStream version affected: /milestone %BuildStream_v1.2

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Apr 26, 2019, 20:58

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 29, 2019, 09:02

This is a regression introduced by 9e85e36e and e0ca1ce9, reverting those in `bst-1.2` fixes the issue.

In master it is introduced by bd7e75f9 and 90af8990.

Let me see if I can wrangle up a regression test for this...

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @bochecha]](https://gitlab.com/bochecha) on Apr 29, 2019, 09:05

> This is a regression introduced by 9e85e36e and 9e85e36e, reverting those in `bst-1.2` fixes the issue.

Those are the same two commits, did you typo one of them?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 29, 2019, 10:19

> Those are the same two commits, did you typo one of them?

Sorry, fixed that in the above comment.

Also, it took me a while but I've figured out the root causes of the change:

* The code has always been invalid around the cloning of `Source`s, such that Source's which are cloned for the purpose of accessing mirrors do not inherit the plugin ID

* This has mostly gone unnoticed because we prefer using the overall *task* ID (which is the owning element) for logging purposes

* [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert)'s change of plugin ID handling has made it possible for a plugin to have ID 0, which was never valid (but easy to miss and not obviously documented). The plugin IDs intentionally start at ID 1 so that code can safely make the assumption that a falsy value for an ID holding variable represents an unset plugin ID.

All of these combined together, have caused line 227 of `_frontend/widget.py` to think that the task_id is not available for the message in question, which in turn caused the code to hit the unknown, cloned plugin ID which was created only in the child process.

I will try to put together a regression test, but the ultimate fixes for this are simple:

* Change `plugin.py` to initialize the monotonic counter at `1`, by calling `itertools.count(1)` instead of `itertools.count()`.

* Allow explicit setting of `unique_id` in `Plugin` constructor, so that `Source` can create the cloned sources which inherit their actual ID, which is important for any case that this ID needs to be reported to the main process.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 29, 2019, 11:41

mentioned in commit 0312f051fe78d620a56371c7c07fce40c52a510e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 29, 2019, 11:43

mentioned in merge request !1315

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 29, 2019, 11:47

mentioned in commit 202559b3a791742d2f7c8a943ca3bf496c75b0a6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 29, 2019, 11:48

mentioned in merge request !1316

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Apr 30, 2019, 06:54

mentioned in commit e435ca5255c77c6184b1cffe568646ae6045a77c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 30, 2019, 12:53

mentioned in commit 60bbe8daa1995b471aa69e234a4d39d61525adbd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Apr 30, 2019, 14:50

closed via merge request !1316

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Apr 30, 2019, 14:50

mentioned in commit 377f20fe5f2a20d8d432e9a5a09e666cdba5afb3
