### ISSUE TITLE
source checkout fails when parent directory is not writable

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1083]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1083)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 17, 2019, 13:53

## Summary

If you look around [here](https://gitlab.com/BuildStream/buildstream/blob/d55b9e398ca4d95e2ffe70580cddf7911c161d20/buildstream/_stream.py#L1200), you will notice that `_stream.py:_source_checkout()` incorrectly assumes that the parent directory of the destination is going to be writable. This is not a valid assumption and currently results in an ugly stacktrace when it happens:

```
    Traceback (most recent call last):
      File "/usr/bin/bst", line 10, in <module>
        sys.exit(cli())
      File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/buildstream/_frontend/cli.py", line 195, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/usr/lib/python3.7/site-packages/buildstream/_frontend/cli.py", line 792, in source_checkout
        include_build_scripts=build_scripts)
      File "/usr/lib/python3.7/site-packages/buildstream/_stream.py", line 660, in source_checkout
        fetch, tar, include_build_scripts)
      File "/usr/lib/python3.7/site-packages/buildstream/_stream.py", line 1352, in _source_checkout
        temp_source_dir = tempfile.TemporaryDirectory(dir=location_parent)
      File "/usr/lib/python3.7/tempfile.py", line 788, in __init__
        self.name = mkdtemp(suffix, prefix, dir)
      File "/usr/lib/python3.7/tempfile.py", line 366, in mkdtemp
        _os.mkdir(file, 0o700)
    PermissionError: [Errno 13] Permission denied: '/tmpj050eb3g'
```

## Steps to reproduce

* Find a BuildStream project to test against
* Pick your favorite element
* Run `bst source checkout ELEMENT DIRECTORY`

where DIRECTORY is a location such that you have write permissions there but not for its parent.

## What is the current bug behavior?

BuildStream throws a stack trace.

## What is the expected correct behavior?

I get my sources correctly.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 17, 2019, 13:54

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Jul 18, 2019, 13:00

So it looks like we use the parent directory for the tmp dir `location_parent`, and then handle moving it into to the specific location once extracted. We could raise an appropriate `StreamError()` to inform the user this is the intended behaviour and supress the stacktrace, however I agree it would be nice to not have this as a requirement.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 18, 2019, 22:51

mentioned in commit e1658f6bb67fae4fe69e426b816f230328d99fa0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 18, 2019, 22:51

mentioned in merge request !1491

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 19, 2019, 18:07

mentioned in commit c9e7114a0f3f7966038d25c9b3c3bb2b3a1bfe07

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 19, 2019, 18:52

closed via merge request !1491

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 19, 2019, 18:52

mentioned in commit 4de721d62bec7ab07f55e425c2d2388e0923cd56

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 25, 2019, 15:24

mentioned in commit b91c12b39e799d42456ebab07e47f8b70830e1bc
