### ISSUE TITLE
BuildStream crashes when trying to push a non-build artifact

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1095]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1095)
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jul 31, 2019, 14:39

## Summary

[//]: # (Summarize the bug encountered concisely)

When trying to push elements and at least an element is not 'cached', BuildStream crashes horribly

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

- create a new bst element
- bst push your_element

A test has been pushed to trigger the bug: https://gitlab.com/BuildStream/buildstream/commit/52f140d388a731d48aa0ea32e07c9840e9f73286

## What is the current bug behavior?

[//]: # (What actually happens)

We get a stacktrace with `AttributeError`

## What is the expected correct behavior?

[//]: # (What you should see instead)

A nice error message/silence

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
(venv) me[[Gitlab user @myhost]](https://gitlab.com/myhost) $ bst --config user.conf artifact push --remote http://localhost:8000
[--:--:--][        ][    main:core activity                 ] START   Push
[--:--:--][        ][    main:core activity                 ] START   Loading elements
[00:00:04][        ][    main:core activity                 ] SUCCESS Loading elements

    29 subtasks processed

[--:--:--][        ][    main:core activity                 ] START   Resolving elements
[00:00:00][        ][    main:core activity                 ] SUCCESS Resolving elements

    29 of 29 subtasks processed

[--:--:--][        ][    main:core activity                 ] START   Initializing remote caches
[00:00:00][        ][    main:core activity                 ] SUCCESS Initializing remote caches
[--:--:--][        ][    main:core activity                 ] START   Resolving cached state
[00:00:05][        ][    main:core activity                 ] SUCCESS Resolving cached state
[--:--:--][        ][    main:core activity                 ] START   Checking sources
[00:00:00][        ][    main:core activity                 ] SUCCESS Checking sources
[--:--:--][        ][    main:core activity                 ] BUG     'NoneType' object has no attribute 'was_workspaced'

    Traceback (most recent call last):
      File "/usr/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/usr/lib/python3.6/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/home/tellendil/buildstreamgit/re/buildstream/src/buildstream/_frontend/cli.py", line 223, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3.6/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3.6/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/tellendil//buildstream/src/buildstream/_frontend/cli.py", line 1155, in artifact_push
        ignore_junction_targets=ignore_junction_targets)
      File "/home/tellendil//buildstream/src/buildstream/_stream.py", line 490, in push
        self._enqueue_plan(elements, queue=push_queue)
      File "/home/tellendil/buildstream/src/buildstream/_stream.py", line 1265, in _enqueue_plan
        queue.enqueue(plan)
      File "/home/tellendil/buildstream/src/buildstream/_scheduler/queues/queue.py", line 183, in enqueue
        self._enqueue_element(elt)
      File "/home/tellendil/buildstream/src/buildstream/_scheduler/queues/queue.py", line 367, in _enqueue_element
        status = self.status(element)
      File "/home/tellendil/buildstream/src/buildstream/_scheduler/queues/artifactpushqueue.py", line 39, in status
        if element._skip_push():
      File "/home/tellendil/buildstream/src/buildstream/element.py", line 1869, in _skip_push
        if self.__get_tainted():
      File "/home/tellendil/buildstream/src/buildstream/element.py", line 2507, in __get_tainted
        workspaced = self.__artifact.get_metadata_workspaced()
      File "/home/tellendil/buildstream/src/buildstream/_artifact.py", line 311, in get_metadata_workspaced
        self._metadata_workspaced = artifact.was_workspaced
    AttributeError: 'NoneType' object has no attribute 'was_workspaced'
```

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 7, 2019, 11:05

mentioned in merge request !1524

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Aug 14, 2019, 16:18

closed via merge request !1524

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Aug 14, 2019, 16:19

mentioned in commit b94d80defe3b60cc90427494c454035400d34cce
