### ISSUE TITLE
Error when using interactive bst init

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1100]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1100)
In GitLab by [[Gitlab user @tmewett]](https://gitlab.com/tmewett) on Aug 8, 2019, 17:01

## Summary

[//]: # (Summarize the bug encountered concisely)

Interactive `bst init` fails with a Python error.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

1. Run `bst init`
1. Enter a project name

## What is the current bug behavior?

[//]: # (What actually happens)
It fails and a Python traceback is printed.

## What is the expected correct behavior?

[//]: # (What you should see instead)
A project is created.

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
Traceback (most recent call last):
  File "/home/tommewett/.local/bin/bst", line 8, in <module>
    sys.exit(cli())
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/tommewett/Documents/buildstream/src/buildstream/_frontend/cli.py", line 223, in override_main
    standalone_mode=standalone_mode, **extra)
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/tommewett/Documents/buildstream/src/buildstream/_frontend/cli.py", line 356, in init
    app.init_project(project_name, format_version, element_path, force, target_directory)
  File "/home/tommewett/Documents/buildstream/src/buildstream/_frontend/app.py", line 369, in init_project
    self._init_project_interactive(project_name, format_version, element_path)
  File "/home/tommewett/Documents/buildstream/src/buildstream/_frontend/app.py", line 859, in _init_project_interactive
    value_proc=project_name_proc, err=True)
  File "/home/tommewett/.local/lib/python3.5/site-packages/click/termui.py", line 126, in prompt
    result = value_proc(value)
  File "/home/tommewett/Documents/buildstream/src/buildstream/_frontend/app.py", line 821, in project_name_proc
    node._assert_symbol_name(None, user_input, 'project name')
  File "src/buildstream/node.pyx", line 1483, in buildstream.node._assert_symbol_name (src/buildstream/node.c:20551)
TypeError: _assert_symbol_name() takes exactly 2 positional arguments (3 given)
```
----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 8, 2019, 17:30

mentioned in merge request !1534

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Aug 8, 2019, 17:32

Look like an error slipped through the cracks as we lack coverage on this interactivity, I've pushed !1534 to fix it

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Aug 9, 2019, 10:49

closed via merge request !1534

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Aug 9, 2019, 10:51

mentioned in commit 8b0ed6d379a2198e5c037693731b15db3392689d
