### ISSUE TITLE
Autocompletion of artifacts is throwing stack traces

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1142]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1142)
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Sep 24, 2019, 16:19

## Summary

[//]: # (Summarize the bug encountered concisely)

When trying to autocomplete an artifact, BuildStream throws an exception

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

`bst artifact delete <TAB> <TAB>`

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
buildstream[[Gitlab user @d09513488e77]](https://gitlab.com/d09513488e77):~/project$ bst artifact delete Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_cas/cascache.py", line 183, in release_resources
    self._casd_process.wait(timeout=0.5)
  File "/usr/lib/python3.7/subprocess.py", line 990, in wait
    return self._wait(timeout=timeout)
  File "/usr/lib/python3.7/subprocess.py", line 1616, in _wait
    raise TimeoutExpired(self.args, timeout)
subprocess.TimeoutExpired: Command '['/usr/local/bin/buildbox-casd', '--bind=unix:/tmp/buildstreamkhholy_4/casd.sock', '/home/buildstream/.cache/buildstream']' timed out after 0.5 seconds

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/bst", line 10, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/cli.py", line 196, in override_main
    if main_bashcomplete(self, prog_name, partial(override_completions, args)):
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/complete.py", line 335, in main_bashcomplete
    do_complete(cmd, prog_name, override)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/complete.py", line 325, in do_complete
    for item in get_choices(cli, prog_name, args, incomplete, override):
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/complete.py", line 294, in get_choices
    choices.extend(get_user_autocompletions(all_args, incomplete, ctx.command, cmd_param, override))
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/complete.py", line 243, in get_user_autocompletions
    incomplete=incomplete)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/cli.py", line 185, in override_completions
    return complete_artifact(orig_args, args, incomplete)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_frontend/cli.py", line 159, in complete_artifact
    return complete_list
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_context.py", line 193, in __exit__
    self._cascache.release_resources(self.messenger)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_cas/cascache.py", line 189, in release_resources
    with cm:
  File "/usr/lib/python3.7/contextlib.py", line 112, in __enter__
    return next(self.gen)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_messenger.py", line 168, in timed_activity
    self.message(message)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_messenger.py", line 123, in message
    assert self._message_handler
AssertionError
```

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 26, 2019, 12:15

`complete_artifact` in cli.py doesn't call `app.initialized` which is responsible for assigning the `self._message_handler` callback into _messenger, as the cas operation is trying to load a `timed_activity` context manager it then fails to be able to call the message_handler

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Sep 26, 2019, 16:34

Hi [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert), I'm not managing to replicate this error, with or without anything in my local cache. I'm currently based off of 7491b7c8273b01af3e12af7256f6ef943fc30345, and have buildbox 20190919-bc3eeb4b from https://buildstream.build/buildbox_install.html. Is there anything specific about your environment I should know about?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 2, 2019, 11:10

marked this issue as related to #1149

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 2, 2019, 11:11

We've been struggling to reproduce this in person as well. I'll leave the issue open for now, because [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) wants to give it another go with a different environment, but I'll mark it needinfo for now.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Oct 9, 2019, 10:20

!1615 fixed it. Let's close. Thanks!

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Oct 9, 2019, 10:20

closed
