### ISSUE TITLE
Autocompletion without buildbox-casd will stacktrace

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1149]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1149)
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 2, 2019, 11:07

## Summary

[//]: # (Summarize the bug encountered concisely)

Autocompletion without buildbox-casd will stacktrace

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

1. Install BuildStream without buildbox-casd
2. Source bash completion (`source src/buildstream/data/bst`)
3. Type `bst artifact delete <tab> <tab>` when shelled into a project directory

## What is the current bug behavior?

[//]: # (What actually happens)

Stacktrace

## What is the expected correct behavior?

[//]: # (What you should see instead)

We should see a list of files and artifact refs.

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
Error instantiating artifact cache: Did not find 'buildbox-casd' in PATH: /home/tlater/Documents/Work/buildstream/.tox/venv/bin:/home/tlater/.local/usr/bin:/home/tlater/.lo
cal/bin:/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
tlater[[Gitlab user @ren]](https://gitlab.com/ren) /home/tlater/Documents/Work/buildstream/tests/integration/project $ bst artifact delete Traceback (most recent call last):
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/bin/bst", line 11, in <module>
    sys.exit(cli())
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/cli.py", line 196, in override_main
    if main_bashcomplete(self, prog_name, partial(override_completions, args)):
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/complete.py", line 335, in main_bashcomplete
    do_complete(cmd, prog_name, override)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/complete.py", line 325, in do_complete
    for item in get_choices(cli, prog_name, args, incomplete, override):
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/complete.py", line 294, in get_choices
    choices.extend(get_user_autocompletions(all_args, incomplete, ctx.command, cmd_param, override))
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/complete.py", line 243, in get_user_autocompletions
    incomplete=incomplete)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/cli.py", line 185, in override_completions
    return complete_artifact(orig_args, args, incomplete)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_frontend/cli.py", line 157, in complete_artifact
    complete_list.extend(ref for ref in ctx.artifactcache.list_artifacts() if ref.startswith(incomplete))
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_context.py", line 381, in artifactcache
    self._artifactcache = ArtifactCache(self)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_artifactcache.py", line 143, in __init__
    super().__init__(context)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_basecache.py", line 52, in __init__
    self.cas = context.get_cascache()
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_context.py", line 512, in get_cascache
    self._cascache = CASCache(self.cachedir, cache_quota=self.config_cache_quota)
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/_cas/cascache.py", line 75, in __init__
    casd_args = [utils.get_host_tool('buildbox-casd')]
  File "/home/tlater/Documents/Work/buildstream/.tox/venv/lib/python3.6/site-packages/buildstream/utils.py", line 480, in get_host_tool
    raise ProgramNotFoundError("Did not find '{}' in PATH: {}".format(name, search_path))
buildstream.utils.ProgramNotFoundError: Did not find 'buildbox-casd' in PATH: /home/tlater/Documents/Work/buildstream/.tox/venv/bin:/home/tlater/.local/usr/bin:/home/tlater
/.local/bin:/usr/lib/llvm/8/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin
```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

Don't check for `buildbox-casd` when performing auto-completion

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 2, 2019, 11:07

mentioned in merge request !1615

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 2, 2019, 11:10

marked this issue as related to #1142

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 2, 2019, 12:17

closed via merge request !1615

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 2, 2019, 12:17

mentioned in commit dbc8f59f3e480610ca054eca07a823a2d9d5dc58
