### ISSUE TITLE
device failures do not cause buildstream failures

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1158]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1158)
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 5, 2019, 08:35

Running `bst build bootstrap/bash.bst` on wsl with a windows container throws a permission failure while trying to open the fuse device but this does not seem to cause an error at the buildstream level. This seems like a fatal error and I'd expect that to be communicated to buildstream.

```
[--:--:--][e07b42b9][   build:bootstrap/freedesktop-junction.bst:bootstrap/build/debugedit-build.bst] START   Staging dependencies
[--:--:--][04eea704][    pull:bootstrap/freedesktop-junction.bst:bootstrap/libstdc++-stage1.bst] START   freedesktop-sdk/bootstrap-libstdc++-stage1/04eea704-pull.57301.log
[--:--:--][04eea704][    pull:bootstrap/freedesktop-junction.bst:bootstrap/libstdc++-stage1.bst] STATUS  Pulling artifact 04eea704 <- http://artifact_cache:11002
[--:--:--][04eea704][    pull:bootstrap/freedesktop-junction.bst:bootstrap/libstdc++-stage1.bst] INFO    Remote (http://artifact_cache:11002) does not have artifact 04eea704 cached
[00:00:00][04eea704][    pull:bootstrap/freedesktop-junction.bst:bootstrap/libstdc++-stage1.bst] SKIPPED Pull
==================================================================== 00:00:06 buildstream-demo (14/30) ====================================================================
                                                (Pull:0 12 0)→ (Fetch:0 12 0)→ (Build:0 0 0)→ (Push:0 0 0)→ (Src-push:0 0 0)
                                                                   ~~~~~~ cache: 3.3G / 44.4G (7%) ~~~~~~
[00:00:00][Build:bootstrap/freedesktop-junction.bst:bootstrap/build/debugedit-build.bst] [00:00:00][Pull:bootstrap/freedesktop-junction.bst:bootstrap/libstdc++-stage1.bst]
fuse: failed to open /dev/fuse: Permission denied
Process Process-18:1:
Traceback (most recent call last):
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/dist-packages/buildstream/_fuse/mount.py", line 191, in __run_fuse
[00:00:00][e07b42b9][   build:bootstrap/freedesktop-junction.bst:bootstrap/build/debugedit-build.bst] SUCCESS Staging dependencies
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Oct 7, 2019, 14:47

mentioned in merge request !1620

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Oct 8, 2019, 15:42

assigned to [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Oct 8, 2019, 20:12

mentioned in merge request !1634

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 9, 2019, 14:05

closed via merge request !1634

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Oct 9, 2019, 14:05

mentioned in commit 372bcab32b37d4f78f3f6a5c0d250d1e65c599bd
