### ISSUE TITLE
OSTree plugin fails with: `TypeError: OSTree.Repo.remote_gpg_import() takes exactly 5 arguments (6 given)`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1164]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1164)
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Oct 8, 2019, 15:41

## Summary

[//]: # (Summarize the bug encountered concisely)

OSTree/GObject seem to have changed and now cause BuildStream 1.4's OSTree plugin to fail when importing gpg keys.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

1. Build any old project with an ostree source plugin
2. Fail

## What is the current bug behavior?

[//]: # (What actually happens)

A BUG message as pasted below.

## What is the expected correct behavior?

[//]: # (What you should see instead)

A nice and comfortable build

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)
```
    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/_scheduler/jobs/job.py", line 413, in _child_action
        result = self.child_process()
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/_scheduler/queues/fetchqueue.py", line 46, in process
        source._fetch(previous_sources)
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/source.py", line 695, in _fetch
        self.__do_fetch()
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/source.py", line 1014, in __do_fetch
        self.fetch(**kwargs)
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/plugins/sources/ostree.py", line 126, in fetch
        remote_name = self.ensure_remote(self.url)
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/plugins/sources/ostree.py", line 194, in ensure_remote
        _ostree.configure_remote(self.repo, remote_name, url, key_url=gpg_key)
      File "/home/tlater/Documents/Work/buildstream/buildstream-1/buildstream/_ostree.py", line 274, in configure_remote
        repo.remote_gpg_import(remote, stream, None, 0, None)
    TypeError: OSTree.Repo.remote_gpg_import() takes exactly 5 arguments (6 given)
```
## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

The following diff does the trick:

```diff
diff --git a/buildstream/_ostree.py b/buildstream/_ostree.py
index 5a4039f2..a0c05629 100644
--- a/buildstream/_ostree.py
+++ b/buildstream/_ostree.py
[[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) -271,6 +271,6 [[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) def configure_remote(repo, remote, url, key_url=None):
         try:
             gfile = Gio.File.new_for_uri(key_url)
             stream = gfile.read()
-            repo.remote_gpg_import(remote, stream, None, 0, None)
+            repo.remote_gpg_import(remote, stream, None, None)
         except GLib.GError as e:
             raise OSTreeError("Failed to add gpg key from url '{}': {}".format(key_url, e.message)) from e
```

*Unfortunately* it isn't quite so simple, because this will probably break with old ostree/gobject combos. Having done some sleuthing, it seems like this function never changed on the OSTree side, so I suspect this is a GObject change, but I don't have the time to dig into this further right now.

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.2 /milestone %"BuildStream_v1.4" /milestone %"BuildStream_v1.6" 

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jul 2, 2020, 11:02

This was "fixed" in !1853 (breaking for old ostree versions) and finally fixed in !1917.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jul 2, 2020, 11:02

closed
