### ISSUE TITLE
bst build does not exit gracefully on a second CTRL-C

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1185]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1185)
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 29, 2019, 16:13

## Summary

Doing a CTRL-C from with the user interrupt handler (the presented click dialogue) should terminate buildstream. It is terminating, however we get errors from unknown child processes, leading to ERROR messages.

* Note this behaviour is seen on native Ubuntu 19.04

## Steps to reproduce

bst build hello.bst in the autotools example project

ctrl-c whilst fetching/building to get the interrupt dialogue, ctrl-c again to terminate

## What is the current bug behavior?

```
--:--:--][96c13701][   fetch:base/alpine.bst               ] START   autotools/base-alpine/96c13701-fetch.18691.log
[--:--:--][96c13701][    main:base/alpine.bst               ] STATUS  Fetch suspending

User interrupted with ^C

Choose one of the following options:
  (c)ontinue  - Continue queueing jobs as much as possible
  (q)uit      - Exit after all ongoing jobs complete
  (t)erminate - Terminate any ongoing jobs and exit

Pressing ^C again will terminate jobs and exit

Choice: [continue]: ^C

Terminating all jobs at user request

[--:--:--][96c13701][    main:base/alpine.bst               ] STATUS  Fetch terminating
Unknown child process pid 18691, will report returncode 255
[--:--:--][96c13701][    main:base/alpine.bst               ] ERROR   Internal job process unexpectedly died with exit code 255
[00:00:04][        ][    main:core activity                 ] WARNING Build Terminated

Pipeline Summary
  Total:       3
  Session:     3
  Fetch Queue: processed 0, skipped 3, failed 0 
  Build Queue: processed 0, skipped 0, failed 0 
```

## What is the expected correct behavior?

We should handle the child watcher more gracefully so it doesn't emit an error, presumably it's the casd process child watcher in this case, with the pid being reaped early.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 29, 2019, 16:15

changed title from **{-B-}uild does not exit gracefully on a second CTRL-C** to **{+bst b+}uild does not exit gracefully on a second CTRL-C**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 30, 2019, 11:33

It looks like the second ctrl-c on a `bst source fetch` leads to a unhandled keyboard interrupt, which is even less graceful.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Oct 30, 2019, 11:34

mentioned in merge request !1613

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Nov 5, 2019, 15:48

assigned to [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Nov 6, 2019, 10:05

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Nov 6, 2019, 10:10

I can try this on wsl and macos for comparison

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Nov 6, 2019, 10:55

I get this with BuildStream 1.4.1:

```
11:42:29 [--:--:--][598100dd][ main:buildbox-casd.bst             ] STATUS  Build suspending

User interrupted with ^C

Choose one of the following options:
  (c)ontinue  - Continue queueing jobs as much as possible
  (q)uit      - Exit after all ongoing jobs complete
  (t)erminate - Terminate any ongoing jobs and exit

Pressing ^C again will terminate jobs and exit

Choice: [continue]: ^CException in callback Scheduler._interrupt_event()
handle: <Handle Scheduler._interrupt_event()>
KeyboardInterrupt

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "buildstream/code/buildstream-1/buildstream/_scheduler/scheduler.py", line 475, in _interrupt_event
    self._interrupt_callback()
  File "buildstream/code/buildstream-1/buildstream/_frontend/app.py", line 506, in _interrupt_handler
    default='continue', err=True)
  File "buildstream/venv-1/lib/python3.7/site-packages/click/termui.py", line 116, in prompt
    value = prompt_func(prompt)
  File "buildstream/venv-1/lib/python3.7/site-packages/click/termui.py", line 100, in prompt_func
    return f('')
SystemError: PyEval_EvalFrameEx returned a result with an error set
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Nov 7, 2019, 09:41

Some first notes:

- This problem is also happening in bst 1.4
- There are actually multiple problems:
  - We sometimes get a corrupted buffer on the second `CTRL-C`, which raises a SystemError instead of a KeyboardInterrupt.
  - While terminating, we `join` the subprocesses before killing them, which calls `os.waitpid` under the hood. That breaks the `ChildWatcher`, which can't recover the information from the child.
  - While terminating we also seem to be receiving loads of `SIGTERM` on the main process??, which slows down the whole loop and causes us to send multiple SIGTERMs to the child, which takes time with an increasing amount of processes

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Nov 8, 2019, 13:28

With https://gitlab.com/BuildStream/buildstream/merge_requests/1690 merged, I no longer see an unhandled interrupt error on a second ctrl-c for the source fetch usecase.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Nov 8, 2019, 13:35

Based on the above, should we close this issue or do we want to keep this open for 1.4 branch?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Nov 8, 2019, 13:38

[[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) !1690 does not fix the entire problem, rather the one from https://gitlab.com/BuildStream/buildstream/issues/1185#note_240749689.

We still need !1691 and another change in order to call that fixed (and backport)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Nov 8, 2019, 15:00

mentioned in merge request !1692

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Nov 13, 2019, 16:39

closed via commit c3eee615fb5fe957d17151ff655ebebc3d029681

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Nov 13, 2019, 16:39

closed via merge request !1692

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Nov 14, 2019, 10:19

mentioned in commit c3eee615fb5fe957d17151ff655ebebc3d029681
