### ISSUE TITLE
bst [anything requiring an event loop] completely funted using python 3.8

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1246]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1246)
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Dec 20, 2019, 15:24

## Summary

[//]: # (Summarize the bug encountered concisely)
Trying to use BuildStream with python 3.8 is completely broken for either master or 1.4, as far as I can tell. It seems to be some issue from async changes perhaps.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)
* Install BuildStream (either 1.4 or master) on a system using python 3.8
* Clone your favourite BuildStream project
* Run `bst build [something].bst`

## What is the current bug behavior?

[//]: # (What actually happens)
Elements, cached state and so on gets resolved, but when the main loop starts this happens:
```bash
[--:--:--][][] BUG     no running event loop

    Traceback (most recent call last):
      File "/home/tom/Documents/integration/int-venv/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_frontend/cli.py", line 173, in override_main
        original_main(self, args=args, prog_name=prog_name, complete_var=None,
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_frontend/cli.py", line 340, in build
        app.stream.build(elements,
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_stream.py", line 211, in build
        self._run()
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_stream.py", line 1022, in _run
        _, status = self._scheduler.run(self.queues)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_scheduler/scheduler.py", line 153, in run
        self._sched()
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_scheduler/scheduler.py", line 427, in _sched
        self._sched_queue_jobs()
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_scheduler/scheduler.py", line 401, in _sched_queue_jobs
        self._spawn_job(job)
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_scheduler/scheduler.py", line 281, in _spawn_job
        job.spawn()
      File "/home/tom/Documents/integration/int-venv/lib/python3.8/site-packages/buildstream/_scheduler/jobs/job.py", line 162, in spawn
        self._watcher.add_child_handler(self._process.pid, self._parent_child_completed)
      File "/usr/lib/python3.8/asyncio/unix_events.py", line 1286, in add_child_handler
        loop = events.get_running_loop()
    RuntimeError: no running event loop
```

## What is the expected correct behavior?

[//]: # (What you should see instead)
The project should build.

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: 1.4 and master, probably 1.2 as well

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Dec 20, 2019, 15:25

marked this issue as related to #1173

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Dec 20, 2019, 15:28

I think we've caught this specific issue already in #1173 , however there's still a few kinks to iron out. I added some comments to the issue earlier in the week with my findings

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Dec 20, 2019, 16:21

We already have an issue for this. Let's close this one.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Dec 20, 2019, 16:21

closed
