### ISSUE TITLE
Multiline comment in a "(>)" crashes "bst track"

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1265]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1265)
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Feb 17, 2020, 10:13

## Summary

[//]: # (Summarize the bug encountered concisely)

Multiline comments

## Steps to reproduce

Try to track the following element:

```
kind: manual

config:
  build-commands:
    (<):
    # BuildStream does not like that
    # multiline comment
    - |
      true

sources:
- kind: remote
  url: https://www.timeanddate.com/worldclock/uk/manchester
```

## What is the current bug behavior?

[//]: # (What actually happens)

```
        Traceback (most recent call last):
          File "/home/valentin/.local/lib/python3.7/site-packages/buildstream/_scheduler/queues/queue.py", line 280, in _job_done
            self.done(job, element, result, status)
          File "/home/valentin/.local/lib/python3.7/site-packages/buildstream/_scheduler/queues/trackqueue.py", line 60, in done
            source._set_ref(new_ref, save=True)
          File "/home/valentin/.local/lib/python3.7/site-packages/buildstream/source.py", line 879, in _set_ref
            _yaml.dump(provenance.toplevel, provenance.filename.name)
          File "/home/valentin/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 248, in dump
            yaml.round_trip_dump(node, f)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1312, in round_trip_dump
            prefix_colon=prefix_colon,
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/main.py", line 1190, in dump_all
            dumper._representer.represent(data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 85, in represent
            node = self.represent_data(data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 112, in represent_data
            node = self.yaml_representers[data_types[0]](self, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1173, in represent_dict
            return self.represent_mapping(tag, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1018, in represent_mapping
            node_value = self.represent_data(item_value)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 112, in represent_data
            node = self.yaml_representers[data_types[0]](self, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1173, in represent_dict
            return self.represent_mapping(tag, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1018, in represent_mapping
            node_value = self.represent_data(item_value)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 112, in represent_data
            node = self.yaml_representers[data_types[0]](self, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1173, in represent_dict
            return self.represent_mapping(tag, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1018, in represent_mapping
            node_value = self.represent_data(item_value)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 112, in represent_data
            node = self.yaml_representers[data_types[0]](self, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 1188, in represent_list
            return self.represent_sequence(tag, data)
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 935, in represent_sequence
            self.merge_comments(node_item, item_comments.get(idx))
          File "/home/valentin/.local/lib/python3.7/site-packages/ruamel/yaml/representer.py", line 957, in merge_comments
            assert val is None or val == nc
        AssertionError
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

It should just track and succeed.

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %"BuildStream_v1.4" 

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Feb 17, 2020, 10:15

mentioned in merge request freedesktop-sdk/freedesktop-sdk!2323

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Feb 17, 2020, 10:16

mentioned in merge request freedesktop-sdk/freedesktop-sdk!2324

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tpollard]](https://gitlab.com/tpollard) on Feb 17, 2020, 14:36

marked this issue as related to #1146

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 23:11

mentioned in commit caa83310f778337bf614d10ae230d33cd4fb3d12

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 23:13

mentioned in merge request !2028

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 23:17

This is caused by an upstream ruamel.yaml issue - https://sourceforge.net/p/ruamel-yaml/tickets/335. That has been fixed since version 0.16.7.

I have created !2028 to bump BuildStream's minimum requirements.

In the meantime, you can fix it on your machines by installing a more recent version of ruamel.yaml. More specifically, `ruamel.yaml >= 0.16.7`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 23:20

mentioned in commit 726913ee485b55053b71df4e376e2480b089c06e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 13, 2020, 23:28

mentioned in commit 3f177d88fc17d1f9b72f0e298ab62ba92749913d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 18, 2020, 21:07

mentioned in commit cccfe96f3747ec0b72c220c9c0af2517cce7b701

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Aug 19, 2020, 12:52

mentioned in commit 01ffd02de4cb4e600d108b42254a21d13c1c4ddd
