### ISSUE TITLE
bst deletes objects that are needed for the session

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1268]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1268)
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Mar 1, 2020, 20:20

## Steps to reproduce

take a big project and a small disk, and launch the build.

to be sure this is not a corrupted cache, I deleted `~/.cache/buildstream` (and have sourcedir configured outside of it), and launched a full rebuild with no remote cache configured. The build was run with `--on-error continue`

## What is the current bug behavior?
One element build fails with the following error
```
[--:--:--] START   freedesktop-sdk.bst:extensions/mesa/mesa.bst: Staging dependencies
[--:--:--] START   freedesktop-sdk.bst:bootstrap/gnu-config.bst: Staging bootstrap/gnu-config.bst/39fb0a36
[00:00:00] FAILURE freedesktop-sdk.bst:bootstrap/gnu-config.bst: Staging bootstrap/gnu-config.bst/39fb0a36
[00:00:00] FAILURE freedesktop-sdk.bst:extensions/mesa/mesa.bst: Staging dependencies
[00:00:00] FAILURE freedesktop-sdk.bst:extensions/mesa/mesa.bst: Directory not found in local cache: [Errno 2] No such file or directory: '/home/abderrahim/.cache/buildstream/cas/objects/6d/08cdaaa5b10bfe42c9f28dac47ce7d82bdf46736db5d47a6eff9b1d9e39494'
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

## Relevant logs and/or screenshots
```
  File "/home/abderrahim/.virtualenvs/bst-master/bin/bst", line 8, in <module>
    sys.exit(cli())
  File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.7/site-packages/click/core.py", line 766, in __call__
    return self.main(*args, **kwargs)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_frontend/cli.py", line 281, in override_main
    original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
  File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.7/site-packages/click/core.py", line 1139, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.7/site-packages/click/core.py", line 958, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/abderrahim/.virtualenvs/bst-master/lib/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_frontend/cli.py", line 491, in build
    app.stream.build(elements, selection=deps, ignore_junction_targets=ignore_junction_targets, remote=remote)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_stream.py", line 326, in build
    self._run()
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_stream.py", line 1363, in _run
    status = self._scheduler.run(self.queues, self._context.get_cascache().get_casd_process_manager())
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/scheduler.py", line 211, in run
    self.loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 538, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1782, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/scheduler.py", line 458, in real_schedule
    self._sched_queue_jobs()
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/scheduler.py", line 438, in _sched_queue_jobs
    self._start_job(job)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/scheduler.py", line 386, in _start_job
    job.start()
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/jobs/job.py", line 187, in start
    self._process.start()
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/_multiprocessing.py", line 62, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/_multiprocessing.py", line 69, in run
    super().run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/jobs/job.py", line 707, in child_action
    result = self.child_process()  # pylint: disable=assignment-from-no-return
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/jobs/elementjob.py", line 103, in child_process
    return self._action_cb(self._element)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_scheduler/queues/buildqueue.py", line 93, in _assemble_element
    return element._assemble()
  File "/home/abderrahim/Projects/bst-master/src/buildstream/element.py", line 1589, in _assemble
    self.stage(sandbox)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/buildelement.py", line 223, in stage
    self.stage_dependency_artifacts(sandbox, Scope.BUILD)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/element.py", line 729, in stage_dependency_artifacts
    result = dep.stage_artifact(sandbox, path=path, include=include, exclude=exclude, orphans=orphans)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/element.py", line 679, in stage_artifact
    files_vdir = self.__artifact.get_files()  # type: ignore
  File "/home/abderrahim/Projects/bst-master/src/buildstream/_artifact.py", line 79, in get_files
    return CasBasedDirectory(self._cas, digest=files_digest)
  File "/home/abderrahim/Projects/bst-master/src/buildstream/storage/_casbaseddirectory.py", line 143, in __init__
    self._reset(digest=digest)
```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jun 6, 2020, 17:44

I have a new stack trace for this

```
  File "/home/abderrahim/.virtualenvs/bst2/bin/bst", line 8, in <module>
    sys.exit(cli())
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/abderrahim/bst-master/src/buildstream/_frontend/cli.py", line 280, in override_main
    original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/abderrahim/.virtualenvs/bst2/lib/python3.7/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/abderrahim/bst-master/src/buildstream/_frontend/cli.py", line 861, in source_fetch
    app.stream.fetch(elements, selection=deps, except_targets=except_, remote=remote)
  File "/home/abderrahim/bst-master/src/buildstream/_stream.py", line 345, in fetch
    self._fetch(elements)
  File "/home/abderrahim/bst-master/src/buildstream/_stream.py", line 1385, in _fetch
    self._run()
  File "/home/abderrahim/bst-master/src/buildstream/_stream.py", line 1359, in _run
    status = self._scheduler.run(self.queues, self._context.get_cascache().get_casd_process_manager())
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/scheduler.py", line 211, in run
    self.loop.run_forever()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 539, in run_forever
    self._run_once()
  File "/usr/lib/python3.7/asyncio/base_events.py", line 1775, in _run_once
    handle._run()
  File "/usr/lib/python3.7/asyncio/events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/scheduler.py", line 480, in real_schedule
    self._sched_queue_jobs()
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/scheduler.py", line 445, in _sched_queue_jobs
    self._start_job(job)
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/scheduler.py", line 385, in _start_job
    job.start()
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/jobs/job.py", line 189, in start
    self._process.start()
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/_multiprocessing.py", line 62, in start
    self._popen = self._Popen(self)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/context.py", line 277, in _Popen
    return Popen(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 20, in __init__
    self._launch(process_obj)
  File "/usr/lib/python3.7/multiprocessing/popen_fork.py", line 74, in _launch
    code = process_obj._bootstrap()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 297, in _bootstrap
    self.run()
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/_multiprocessing.py", line 69, in run
    super().run()
  File "/usr/lib/python3.7/multiprocessing/process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/jobs/job.py", line 709, in child_action
    result = self.child_process()  # pylint: disable=assignment-from-no-return
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/jobs/elementjob.py", line 103, in child_process
    return self._action_cb(self._element)
  File "/home/abderrahim/bst-master/src/buildstream/_scheduler/queues/fetchqueue.py", line 78, in _fetch_not_original
    element._fetch(fetch_original=False)
  File "/home/abderrahim/bst-master/src/buildstream/element.py", line 2059, in _fetch
    self.__cache_sources()
  File "/home/abderrahim/bst-master/src/buildstream/element.py", line 2939, in __cache_sources
    self.__sourcecache.commit(source, [])
  File "/home/abderrahim/bst-master/src/buildstream/_sourcecache.py", line 181, in commit
    source._stage(vdir)
  File "/home/abderrahim/bst-master/src/buildstream/source.py", line 831, in _stage
    cas_dir = CasBasedDirectory(self._get_context().get_cascache(), digest=self.__digest)
  File "/home/abderrahim/bst-master/src/buildstream/storage/_casbaseddirectory.py", line 146, in __init__
    self._reset(digest=digest)
  File "/home/abderrahim/bst-master/src/buildstream/storage/_casbaseddirectory.py", line 152, in _reset
    self._populate_index(digest)
  File "/home/abderrahim/bst-master/src/buildstream/storage/_casbaseddirectory.py", line 163, in _populate_index
```

It seems to be caused by a `local` source (which defines BST_KEY_REQUIRES_STAGE), where the files disappear from the cache between the calls to `_get_unique_key()` and `_stage()`. The former is likely called at around bst startup, whereas the latter happens when the source is actually needed.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jun 7, 2020, 11:42

And another one. (Note I'm running it with low disk space on purpose to find more of these)
```
[--:--:--] BUG     bootstrap/linux-headers.bst: Fetch

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/abderrahim/bst-master/src/buildstream/_scheduler/jobs/job.py", line 709, in child_action
        result = self.child_process()  # pylint: disable=assignment-from-no-return
      File "/home/abderrahim/bst-master/src/buildstream/_scheduler/jobs/elementjob.py", line 103, in child_process
        return self._action_cb(self._element)
      File "/home/abderrahim/bst-master/src/buildstream/_scheduler/queues/fetchqueue.py", line 78, in _fetch_not_original
        element._fetch(fetch_original=False)
      File "/home/abderrahim/bst-master/src/buildstream/element.py", line 2059, in _fetch
        self.__cache_sources()
      File "/home/abderrahim/bst-master/src/buildstream/element.py", line 2936, in __cache_sources
        self.__sourcecache.commit(source, self.__sources[last_requires_previous:ix])
      File "/home/abderrahim/bst-master/src/buildstream/_sourcecache.py", line 177, in commit
        vdir.export_files(tmpdir)
      File "/home/abderrahim/bst-master/src/buildstream/storage/_casbaseddirectory.py", line 570, in export_files
        self.cas_cache.checkout(to_directory, self._get_digest(), can_link=can_link)
      File "/home/abderrahim/bst-master/src/buildstream/_cas/cascache.py", line 262, in checkout
        self.checkout(fullpath, dirnode.digest, can_link=can_link)
      File "/home/abderrahim/bst-master/src/buildstream/_cas/cascache.py", line 262, in checkout
        self.checkout(fullpath, dirnode.digest, can_link=can_link)
      File "/home/abderrahim/bst-master/src/buildstream/_cas/cascache.py", line 262, in checkout
        self.checkout(fullpath, dirnode.digest, can_link=can_link)
      [Previous line repeated 1 more time]
      File "/home/abderrahim/bst-master/src/buildstream/_cas/cascache.py", line 244, in checkout
        utils.safe_copy(self.objpath(filenode.digest), fullpath)
      File "/home/abderrahim/bst-master/src/buildstream/utils.py", line 388, in safe_copy
        shutil.copyfile(src, dest)
      File "/usr/lib/python3.7/shutil.py", line 120, in copyfile
        with open(src, 'rb') as fsrc:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/abderrahim/.cache/buildstream/cas/objects/4a/16cab41a8f641d77f5c3cb94e7ab34b15c97db8f816c124bca9ebad53340c0'
```

This one seems to be sourcecache related as well.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jun 8, 2020, 09:57

mentioned in commit 09b2c8527bb88c457fb40fbb14a1dfcea04afc60

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jun 8, 2020, 09:59

mentioned in merge request !1958

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jun 8, 2020, 14:30

closed via merge request !1958

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jun 8, 2020, 14:30

mentioned in commit feb82abe89c56a0f6bfbddcf69e1534c68b7e973
