### ISSUE TITLE
automatic cachekey updating for tests is broken

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1289]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1289)
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Apr 22, 2020, 13:39

running the `update.py` script will throw an error in the case of missing 'build-uid' and 'build-gid' keys for the sandbox config since the default `None` is not valid in `MappingNode.get_int()`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Apr 22, 2020, 13:41

mentioned in commit d1068c1c86d7934d86cb8e1cdcae03fdb4ece661

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 22, 2020, 13:55

It seems to work fine for me. Can you please paste the exact error here?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Apr 22, 2020, 15:17

```
BuildStream exited with code -1 for invocation:
	bst --no-colors --no-verbose --config /home/traveltissues/projects/co042/buildstream/tests/cachekey/project/tmp6xm6nhwo/cache/buildstream.conf --directory /home/traveltissues/projects/co042/buildstream/tests/cachekey/project --no-colors show --format %{name}::%{full-key} target.bst
Program stderr was:
[--:--:--][        ][    main:core activity                 ] START   Loading elements
[00:00:00][        ][    main:core activity                 ] SUCCESS Loading elements

    28 subtasks processed

[--:--:--][        ][    main:core activity                 ] START   Resolving elements

Traceback (most recent call last):
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/testing/runcli.py", line 379, in _invoke
    cli_object.main(args=args or (), prog_name=cli_object.name)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_frontend/cli.py", line 281, in override_main
    original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_frontend/cli.py", line 596, in show
    dependencies = app.stream.load_selection(elements, selection=deps, except_targets=except_)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_stream.py", line 167, in load_selection
    load_refs=load_refs,
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_stream.py", line 1267, in _load
    targets, except_targets, rewritable=False
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_stream.py", line 1147, in __load_elements_from_targets
    elements, except_elements = self._pipeline.load(loadable, rewritable=rewritable)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_pipeline.py", line 77, in load
    elements = self._project.load_elements(targets, rewritable=rewritable)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_project.py", line 463, in load_elements
    elements = [Element._new_from_meta(meta, task) for meta in meta_elements]
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_project.py", line 463, in <listcomp>
    elements = [Element._new_from_meta(meta, task) for meta in meta_elements]
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/element.py", line 901, in _new_from_meta
    element = meta.project.create_element(meta, first_pass=meta.first_pass)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_project.py", line 380, in create_element
    return self.config.element_factory.create(self._context, self, meta)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/_elementfactory.py", line 62, in create
    element = element_type(context, project, meta, default_config)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/element.py", line 317, in __init__
    self.__sandbox_config = self.__extract_sandbox_config(context, project, meta)
  File "/home/traveltissues/projects/co042/buildstream/src/buildstream/element.py", line 2709, in __extract_sandbox_config
    sandbox_config.get_int("build-uid", None), sandbox_config.get_int("build-gid", None), build_os, build_arch,
  File "src/buildstream/node.pyx", line 596, in buildstream.node.MappingNode.get_int
    cpdef object get_int(self, str key, object default=_sentinel):
  File "src/buildstream/node.pyx", line 616, in buildstream.node.MappingNode.get_int
    if default is None and scalar.is_none():
  File "src/buildstream/node.pyx", line 387, in buildstream.node.ScalarNode.as_int
    return int(self.value)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
No results from parsing /home/traveltissues/projects/co042/buildstream/tests/cachekey/project:target.bst
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Apr 22, 2020, 15:21

mentioned in commit 70e470f185449360aa2c22ba539032c4fbe94e23

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 22, 2020, 15:28

I suspect this is just a Cython build issue. Can you try with `tox -e venv -- python3 ./tests/cachekey/update.py`?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Apr 22, 2020, 15:38

that works but i don't understand why this seems to be executing `scalar.as_int()` even in the None default case. unless this is not reliably returning true from `is_none()` on the none-defaulted scalar node. previously i was able to run this script in my own environment, has something changed in node handling?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 22, 2020, 15:46

The generated `node.c` and/or `node.cpython37m-x86_64-linux-gnu.so` are out of date on your system outside the tox environment. I.e., it was executing the old line 616 where it was always calling `as_int() and there was no special case for `None` yet.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Apr 22, 2020, 15:46

closed
