### ISSUE TITLE
Bad exit from log from RE

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1306]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1306)
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 12, 2020, 20:52

## Summary
```
    [00:00:00] FAILURE bootstrap/gnu-config.bst: Failed to query action cache: StatusCode.INVALID_ARGUMENT (Invalid instance name: [development-emea-1])
    ======================================================================

[20:42:28][--:--:--][        ][    main:core activity                 ] BUG     'NoneType' object has no attribute 'was_workspaced'

    Traceback (most recent call last):
      File "/usr/lib64/python3.7/asyncio/events.py", line 88, in _run
        self._context.run(self._callback, *self._args)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/scheduler.py", line 458, in real_schedule
        self._sched_queue_jobs()
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/scheduler.py", line 406, in _sched_queue_jobs
        queue.enqueue(elements)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/queues/queue.py", line 184, in enqueue
        self._enqueue_element(elt)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/queues/queue.py", line 367, in _enqueue_element
        status = self.status(element)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/queues/artifactpushqueue.py", line 39, in status
        if element._skip_push():
      File "/home/will/projects/buildstream/buildstream/src/buildstream/element.py", line 1769, in _skip_push
        if self.__get_tainted():
      File "/home/will/projects/buildstream/buildstream/src/buildstream/element.py", line 2409, in __get_tainted
        workspaced = self.__artifact.get_metadata_workspaced()
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_artifact.py", line 341, in get_metadata_workspaced
        self._metadata_workspaced = artifact.was_workspaced
    AttributeError: 'NoneType' object has no attribute 'was_workspaced'
```

Odd failure after looking at logs of failed RE build the server was not called `development-emea-1`
## Steps to reproduce

add `instance-name: development-emea-1` to the `remote-execution:` sections eg. `action-cache-service:` when the service is called ""

then look at logs
then ctl+C

## What is the current bug behavior?

un recoverable crash and track back as above.

## What is the expected correct behavior?

graceful exit

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on May 12, 2020, 21:23

dupe of #1304

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 20, 2020, 23:54

This seems to be fixed in master thanks [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) for the fix

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 20, 2020, 23:55

closed
