### ISSUE TITLE
format strings are not doing robust checks

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1307]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1307)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 13, 2020, 15:53

## Summary

I wasn't sure how to title this issue, so feel free to rephrase it if you have a better title in mind.

Her's the gist of the issue - if you pass some things to `bst show --format` that is not quite expecting, it will throw a stack trace. Also, in some cases where it doesn't throw a stack trace, it may not produce the right output.

## Steps to reproduce

Here are a few examples:

1.  ~~When a `$` character is used, some things are chopped of from the output that shouldn't be. For example, in this case the output should been `hello.bst ${build-deps}`. Since we don't consider `$` as a special character, it should be printed literally.~~

EDIT: this is not a real bug, this was my mistake of using double quotes instead of single quotes.

    ```bash
    $ bst -C doc/examples/first-project show --format "%{name} ${build-deps}"
    hello.bst deps
    ```

2. When a `%` prefix is not used, we should again expect to have it rendered literally. But that's not what happens:

    ```bash
        $ bst -C doc/examples/first-project show --format "%{name} {build-deps}"

            Traceback (most recent call last):
              File "/home/kote/.venvs/bst/bin/bst", line 8, in <module>
                sys.exit(cli())
              File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 764, in __call__
                return self.main(*args, **kwargs)
              ...
              File "/home/kote/buildstream/buildstream/src/buildstream/_frontend/profile.py", line 76, in fmt_subst
                return re.sub(r"%(\{(" + varname + r")[^%]*\})", subst_callback, text)
              File "/usr/lib64/python3.7/re.py", line 192, in sub
                return _compile(pattern, flags).sub(repl, string, count)
              File "/home/kote/buildstream/buildstream/src/buildstream/_frontend/profile.py", line 70, in subst_callback
                formatted = inner_token.format(**{varname: value})
            KeyError: 'build-deps'
    ```

3. There are probably more edge cases that I haven't considered.

## What is the current bug behavior?

BuildStream either throws a stack trace or prints incorrect output.

## What is the expected correct behavior?

BuildStream never throws a stack trace, no matter the input. If the input format is irrevocably messed up, we give a nice error message. And, for everything else, we should get the output in the expected format.

## Possible fixes

[[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) mentioned that the greediness of our regexes might be at play here. If that's the issue, we can look into making them miser searches instead.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 14, 2020, 20:33

mentioned in commit e5a1c606592a9a45224955d9292869502969db16

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 14, 2020, 20:34

mentioned in merge request !1932

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 14, 2020, 20:35

The first problem was me being stupid as `$` and the following text was being interpreted by `bash` and not BuildStream. I have verified that things work as expected when using single quotes, instead of double quotes ad I originally mentioned in the ticket.

The second part is a real bug, and I've created !1932 to fix that.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 14, 2020, 20:36

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on May 18, 2020, 11:24

mentioned in commit 6157b4fd09397ecb5304c523bf31f079f6a8d44e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on May 18, 2020, 12:47

closed via merge request !1932

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on May 18, 2020, 12:47

mentioned in commit ef00fc2f384631a001442b5cd2b5765c58809720
