### ISSUE TITLE
Crash on remote failure try

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1309]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1309)
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 13, 2020, 23:56

## Summary

[//]: # (Summarize the bug encountered concisely)
```
23:48:13][--:--:--][a78252e5][    main:bootstrap/build/coreutils-manpages.bst] STATUS  Push terminating
[23:48:13][--:--:--][        ][    main:core activity                 ] BUG     'NoneType' object has no attribute 'terminate'

    Traceback (most recent call last):
      File "/usr/lib64/python3.7/asyncio/events.py", line 88, in _run
        self._context.run(self._callback, *self._args)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/scheduler.py", line 562, in _terminate_jobs_real
        job.terminate()
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/jobs/job.py", line 217, in terminate
        self._process.terminate()
    AttributeError: 'NoneType' object has no attribute 'terminate'

[23:48:13][--:--:--][a78252e5][    main:bootstrap/build/coreutils-manpages.bst] WARNING Push did not terminate gracefully, killing
[23:48:13][--:--:--][        ][    main:core activity                 ] BUG     'NoneType' object has no attribute 'pid'

    Traceback (most recent call last):
      File "/usr/lib64/python3.7/asyncio/events.py", line 88, in _run
        self._context.run(self._callback, *self._args)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/scheduler.py", line 556, in kill_jobs
        job_.kill()
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_scheduler/jobs/job.py", line 238, in kill
        utils._kill_process_tree(self._process.pid)
    AttributeError: 'NoneType' object has no attribute 'pid'

```

## Steps to reproduce

Cross build freedesktop-sdk, `bst -o target_arch aarch64 build bootstrap/bootstrap.bst` if it fails to build then pic retry.

## What is the current bug behavior?

Crash so that Ctl+C will not stop bst, The hole scroll back is this error over and over again.

## What is the expected correct behavior?

tetry to build.

## Relevant logs and/or screenshots
running bst branch willsalmon/expandsan

```
diff --git a/project.conf b/project.conf
index d94b59dc..61c74308 100644
--- a/project.conf
+++ b/project.conf
[[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) -74,8 +74,6 [[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) plugins:
 options:
   ([[Gitlab user @]](https://gitlab.com/)): include/_private/options.yml
 
-artifacts:
-  url: https://public.aws.celduin.co.uk
 
 elements:
   cmake:
[[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) -92,3 +90,9 [[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) elements:
 sources:
   git_tag:
     ([[Gitlab user @]](https://gitlab.com/)): include/_private/git_tag-conf.yml
+
+
+sandbox:
+  build-arch: '%{arch}'
+
+
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 13, 2020, 23:56

changed title from **{-Horible c-}rash on remote failure try** to **{+C+}rash on remote failure try**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 14, 2020, 13:03

I ran into something like this last week, this is in fact 2 issues in one.

It appears that we have an issue where in some code section in the main process (hard to tell exactly where, but this also happens while in the process of queueing jobs) causes infinite loops when a bug occurs, because the `Job` does not cope well with crashing before it's process is ever created (resulting in crashes when trying to terminate itself, causing it to try to terminate itself again and so on).

The above is one issue: A very bad side effect of crashing.

The other issue is whatever is causing this original crash, which is hard to capture.

The way I found my issue last week was like this, with 2 terminals:

* Run the command which triggers the error in one terminal, `bst show foo.bst` or similar
* Quickly hit `alt-tab`
* Run `killall -9 bst` in the second terminal
* Do this many times until you find the *first* stack trace, which will most probably be different and completely unrelated to `Job` having a `None` process.
  * If you `killall -9 bst` too soon, then you don't get the important stack trace because the project was still loading
  * If you `killall -9 bst` too late, then your millions of lines of terminal history (or whatever you've configured your terminal to keep), are completely full of this spamming of `Job` termination stack traces, and you won't have the stack trace you're looking for.

Can you try the above in order to capture the original stack trace ?

We'll inevitably need to fix both issues (the crash, and the side effect of infinite cycling crashes).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 15, 2020, 13:46

marked this issue as related to #1312

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 19, 2020, 11:29

Since landing !1933, the infinite crashes (documented in #1312) should be fixed.

Can you try to reproduce this again with BuildStream master ? I expect you should get a more concise stack trace now (and no looping crashes).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 20, 2020, 23:56

This seems to be fixed, thanks [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @pointswaves]](https://gitlab.com/pointswaves) on May 20, 2020, 23:56

closed
