### ISSUE TITLE
link_target error

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1337]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1337)
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Jun 3, 2020, 16:01

## Summary

I dont know if there is a issue with my branch of FD or not but buildstream should not be given a trace back but a error message.

```
(venvbuildstream) [will[[Gitlab user @wsx280]](https://gitlab.com/wsx280) freedesktop-sdk]$ XDG_CACHE_HOME=/home/will/projects/buildstream/freedesktop-sdk/pullissue; bst build bootstrap/bootstrap.bst
[--:--:--][        ][    main:core activity                 ] START   Build
[--:--:--][        ][    main:core activity                 ] START   Loading elements
[--:--:--][        ][    main:core activity                 ] BUG     'buildstream._loader.loadelement.LoadElement' object has no attribute 'link_target'

    Traceback (most recent call last):
      File "/home/will/projects/buildstream/venvbuildstream/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/will/projects/buildstream/venvbuildstream/lib64/python3.7/site-packages/click/core.py", line 829, in __call__
        return self.main(*args, **kwargs)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_frontend/cli.py", line 280, in override_main
        original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
      File "/home/will/projects/buildstream/venvbuildstream/lib64/python3.7/site-packages/click/core.py", line 782, in main
        rv = self.invoke(ctx)
      File "/home/will/projects/buildstream/venvbuildstream/lib64/python3.7/site-packages/click/core.py", line 1259, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/will/projects/buildstream/venvbuildstream/lib64/python3.7/site-packages/click/core.py", line 1066, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/will/projects/buildstream/venvbuildstream/lib64/python3.7/site-packages/click/core.py", line 610, in invoke
        return callback(*args, **kwargs)
      File "/home/will/projects/buildstream/venvbuildstream/lib64/python3.7/site-packages/click/decorators.py", line 33, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_frontend/cli.py", line 501, in build
        app.stream.build(elements, selection=deps, ignore_junction_targets=ignore_junction_targets, remote=remote)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_stream.py", line 282, in build
        dynamic_plan=True,
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_stream.py", line 1259, in _load
        targets, except_targets, rewritable=False
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_stream.py", line 1139, in __load_elements_from_targets
        elements, except_elements = self._pipeline.load(loadable, rewritable=rewritable)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_pipeline.py", line 77, in load
        elements = self._project.load_elements(targets, rewritable=rewritable)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_project.py", line 449, in load_elements
        meta_elements = self.loader.load(targets, task, rewritable=rewritable, ticker=None)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_loader/loader.py", line 117, in load
        element = loader._load_file(name, rewritable, ticker)
      File "/home/will/projects/buildstream/buildstream/src/buildstream/_loader/loader.py", line 564, in _load_file
        if top_element.link_target is not None:
    AttributeError: 'buildstream._loader.loadelement.LoadElement' object has no attribute 'link_target'


```

## Steps to reproduce

checkout `willsalmon/bst2-buildbox-fix` from Freedesktop-sdk and build

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Jun 3, 2020, 16:08

Turned out i had stall compiled parts and needed to recompile.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Jun 3, 2020, 16:08

closed
