### ISSUE TITLE
`artifact checkout` crashes when no arguments are supplied

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1367]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1367)
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jul 17, 2020, 14:13

## Summary

When `bst artifact checkout` is run without any arguments, it just throws a stack trace (rather embarrisingly).

## Steps to reproduce

```bash
# From the root of this repository
$ cd doc/examples/first-project
$ bst artifact checkout
Traceback (most recent call last):
  File "/home/kote/.venvs/bst/bin/bst", line 8, in <module>
    sys.exit(cli())
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/kote/buildstream/buildstream/src/buildstream/_frontend/cli.py", line 238, in override_main
    original_main(self, args=args, prog_name=prog_name, complete_var=None, standalone_mode=standalone_mode, **extra)
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/kote/.venvs/bst/lib64/python3.7/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/kote/buildstream/buildstream/src/buildstream/_frontend/cli.py", line 1239, in artifact_checkout
    location = os.path.abspath(os.path.join(os.getcwd(), target))
  File "/usr/lib64/python3.7/posixpath.py", line 94, in join
    genericpath._check_arg_types('join', a, *p)
  File "/usr/lib64/python3.7/genericpath.py", line 149, in _check_arg_types
    (funcname, s.__class__.__name__)) from None
TypeError: join() argument must be str or bytes, not 'NoneType'
```

## What is the current bug behavior?

A stack trace is shown.

## What is the expected correct behavior?

BuildStream can either do nothing (similar to what happens when you do `bst artifact delete` with no arguments) or an error is displayed that at least one element/artifact must be specified. I'd be leaning towards the latter option since that's symmetrical to what happens when you don't provide any options to `bst source checkout`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 4, 2020, 22:58

mentioned in commit 87bd1cf287c1f918b74ddfb33d855a9e3f658677

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 4, 2020, 22:58

mentioned in merge request !2017

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 7, 2020, 12:39

mentioned in commit 7dc9be9c0c2c0793f7443b29a802535031e5afbd

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 11, 2020, 02:02

mentioned in commit c791cd895b95533f27b742aec8152fc313b20d0e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 11, 2020, 03:10

mentioned in commit 8935cbb09922178dd0636758edd3b9946b5f0026
