### ISSUE TITLE
aborting bst push command causes stack trace

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#138]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/138)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 27, 2017, 18:15

When running

> bst push --deps all apps/meta-gnome-apps-tested.bst

And things are failing, perhaps connectivity reasons, I tried `retry` option once, it failed, and decided to hit \^C on the next prompt.

The result is an ugly unhandled exception:
```
00:00:00][b1dbab84][ push:apps/accerciser.bst           ] FAILURE Sending artifact
[00:00:08][b1dbab84][ push:apps/accerciser.bst           ] FAILURE Pushing Artifact
[00:00:08][b1dbab84][ push:apps/accerciser.bst           ] FAILURE gnome/apps-accerciser/b1dbab84-push.19019.log

    Failed to push artifact gnome/apps-accerciser/b1dbab84ef8722a28a2062314171155f16e8f6a954395e25dc52bcb6ee4bb003: Expected reply, got none

    
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/usr/lib/pkgconfig
        SHELL: /bin/sh
        SOURCE_DATE_EPOCH: '1320937200'
        TERM: dumb
        TZ: UTC
        USER: tomjon
        USERNAME: tomjon
        V: '1'
    [--:--:--] START   [apps/accerciser.bst]: Pushing Artifact
    [--:--:--] START   [apps/accerciser.bst]: Preparing compressed archive
    [00:00:07] SUCCESS [apps/accerciser.bst]: Preparing compressed archive
    [--:--:--] START   [apps/accerciser.bst]: Sending artifact
    pushreceive: INFO: Executing ssh -l artifacts -p 10007 gnome7.codethink.co.uk bst-artifact-receive --verbose artifacts
    pushreceive: INFO: Receiving repository information
    ssh: connect to host gnome7.codethink.co.uk port 10007: Connection refused
    [00:00:00] FAILURE [apps/accerciser.bst]: Sending artifact
    [00:00:08] FAILURE [apps/accerciser.bst]: Pushing Artifact
    [00:00:08] FAILURE [apps/accerciser.bst]: Push
    
        Failed to push artifact gnome/apps-accerciser/b1dbab84ef8722a28a2062314171155f16e8f6a954395e25dc52bcb6ee4bb003: Expected reply, got none

[--:--:--][d621e192][ main:apps/evolution.bst            ] STATUS  Push suspending
[--:--:--][7a00f6e6][ main:apps/ghex.bst                 ] STATUS  Push suspending
[--:--:--][6e4be59e][ main:apps/libgit2-glib.bst         ] STATUS  Push suspending

Push failure on element: apps/accerciser.bst

Choose one of the following options:
  continue  - Continue queueing jobs as much as possible
  quit      - Exit after all ongoing jobs complete
  terminate - Terminate any ongoing jobs and exit
  retry     - Retry this job
  log       - View the full log file

Pressing ^C will terminate jobs and exit

Choice: [continue]: ^C

Terminating all jobs

[--:--:--][d621e192][ main:apps/evolution.bst            ] STATUS  Push resuming
[--:--:--][7a00f6e6][ main:apps/ghex.bst                 ] STATUS  Push resuming
[--:--:--][6e4be59e][ main:apps/libgit2-glib.bst         ] STATUS  Push resuming
[--:--:--][d621e192][ main:apps/evolution.bst            ] STATUS  Push terminating
[--:--:--][7a00f6e6][ main:apps/ghex.bst                 ] STATUS  Push terminating
[--:--:--][6e4be59e][ main:apps/libgit2-glib.bst         ] STATUS  Push terminating
[--:--:--][d2fca14e][ main:apps/gitg.bst                 ] STATUS  Push terminating
Process Process-13:
Traceback (most recent call last):
  File "/codethink/GNOME/buildstream/buildstream/_artifactcache/ostreecache.py", line 352, in push
    [ref, weak_ref], output_file)
  File "/codethink/GNOME/buildstream/buildstream/_artifactcache/pushreceive.py", line 675, in push
    pusher.run()
  File "/codethink/GNOME/buildstream/buildstream/_artifactcache/pushreceive.py", line 459, in run
    args = self.reader.receive_info()
  File "/codethink/GNOME/buildstream/buildstream/_artifactcache/pushreceive.py", line 266, in receive_info
    cmdtype, args = self.receive([PushCommandType.info])
  File "/codethink/GNOME/buildstream/buildstream/_artifactcache/pushreceive.py", line 260, in receive
    raise PushException('Expected reply, got none')
buildstream._artifactcache.pushreceive.PushException: Expected reply, got none

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/codethink/GNOME/buildstream/buildstream/_scheduler/job.py", line 265, in child_action
    result = self.action(element)
  File "/codethink/GNOME/buildstream/buildstream/_scheduler/pushqueue.py", line 39, in process
    return element._push()
  File "/codethink/GNOME/buildstream/buildstream/element.py", line 1173, in _push
    return self.__artifacts.push(self)
  File "/codethink/GNOME/buildstream/buildstream/_artifactcache/ostreecache.py", line 354, in push
    raise _ArtifactError("Failed to push artifact {}: {}".format(ref, e)) from e
buildstream.exceptions._ArtifactError: Failed to push artifact gnome/apps-evolution/d621e19297b2df27ed9607cb0a355a7dafcab6f92a5417bc6bbd78ad48666fab: Expected reply, got none

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/codethink/GNOME/buildstream/buildstream/element.py", line 1289, in _logging_enabled
    yield self.__log_path
  File "/codethink/GNOME/buildstream/buildstream/_scheduler/job.py", line 281, in child_action
    self.child_shutdown(1)
  File "/codethink/GNOME/buildstream/buildstream/_scheduler/job.py", line 314, in child_shutdown
    sys.exit(exit_code)
SystemExit: 1

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/codethink/GNOME/buildstream/buildstream/_scheduler/job.py", line 297, in child_action
    logfile=filename)
  File "/usr/lib/python3.5/contextlib.py", line 77, in __exit__
    self.gen.throw(type, value, traceback)
  File "/codethink/GNOME/buildstream/buildstream/element.py", line 1291, in _logging_enabled
    self.__log_path = None
  File "/codethink/GNOME/buildstream/buildstream/_signals.py", line 37, in terminator_handler
    terminator()
  File "/codethink/GNOME/buildstream/buildstream/element.py", line 1282, in flush_log
    .format(action_name, self.name))
ValueError: I/O operation on closed file.
^C^C

[00:00:29][9ac8d8be][ main:apps/meta-gnome-apps-tested.bst] FAILURE Push failed
ERROR: 
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Nov 13, 2017, 15:53

created branch [`138-aborting-bst-push-command-causes-stack-trace`](https://gitlab.com/BuildStream/buildstream/compare/master...138-aborting-bst-push-command-causes-stack-trace)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 7, 2018, 21:42

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 20, 2018, 18:05

assigned to [[Gitlab user @coldtom]](https://gitlab.com/coldtom)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 21, 2018, 09:06

[[Gitlab user @cs]](https://gitlab.com/cs)\-shadow What changes did you make to the description?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 21, 2018, 11:22

[[Gitlab user @coldtom]](https://gitlab.com/coldtom) nothing major, I just fixed the formatting of `^C`, which was previously rendering as a superscript (^C). Sorry if I caused more confusion than before :)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 21, 2018, 11:29

Thanks, I was hoping it was just a cosmetic change :)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 21, 2018, 17:53

created branch [`138-aborting-bst-push-command-causes-stack-trace-2`](https://gitlab.com/BuildStream/buildstream/compare/master...138-aborting-bst-push-command-causes-stack-trace-2)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 21, 2018, 17:54

mentioned in merge request !513

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 21, 2018, 18:16

created branch [`138-aborting-bst-push-command-causes-stack-trace-3`](https://gitlab.com/BuildStream/buildstream/compare/master...138-aborting-bst-push-command-causes-stack-trace-3)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jun 21, 2018, 18:16

mentioned in merge request !514

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jul 2, 2018, 17:27

I could not reproduce the behaviour despite my best efforts, and as a result it was recommended this issue be closed or set to needs info for the time being.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Jul 2, 2018, 17:27

unassigned [[Gitlab user @coldtom]](https://gitlab.com/coldtom)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 2, 2018, 17:44

Thanks for the update. After reading the comments on your associated [MR](https://gitlab.com/BuildStream/buildstream/merge_requests/514) that says: 

'In this case, I think we really need to reproduce if we're going to fix. Otherwise, I think we should put this to sleep, closed in a `NEEDINFO` state in case it happens again.'

Then I think the action here is to close the issue (and then the MR) and add the label 'NeedInfo'. [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) what do you think?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Jul 2, 2018, 17:44

assigned to [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 10, 2018, 08:30

mentioned in commit a615e00185b097a3ff3ce15f58e79a803339d9f8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 10, 2018, 08:51

mentioned in commit 76cbcd4ec52c26fc77134533df64c64221610e22

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 10, 2018, 17:06

mentioned in commit 8c7ab2f0a3582cde19d5be7f293b47bfa51efbc4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 10, 2018, 18:12

mentioned in commit 1792150b63971e2c4335f785cb9c7da1243cfcc4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 16, 2018, 15:33

mentioned in commit cb79b711f0c653c10d78e44f3154eee4f9d123b9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 16, 2018, 17:24

mentioned in commit fdbc1e33f84fd45f6ac4527846fc3cc8a14d009b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 17, 2018, 06:58

mentioned in commit 1f8b4aa290a908a697f008a29ea143a9320dd639

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jul 17, 2018, 08:59

closed via merge request !337
