### ISSUE TITLE
NameError while processing BlobNotFound by bst 1.6.0

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#1403]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/1403)
In GitLab by [[Gitlab user @nanonyme]](https://gitlab.com/nanonyme) on Oct 6, 2020, 17:46

## Summary

[//]: # (Summarize the bug encountered concisely)
artifactcache tries to raise BlobNotFound but it's not defined there.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)
Unknown, this seems like a chained exception. 

## What is the current bug behavior?

[//]: # (What actually happens)
Exception while processing exception

## What is the expected correct behavior?

[//]: # (What you should see instead)
Just the original exception

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)
```
    [00:00:00][bec0953f][ pull:components/json-glib.bst      ] BUG     Pull
        An unhandled exception occured:
    
        Traceback (most recent call last):
          File "/usr/lib/python3.8/site-packages/buildstream/_artifactcache/artifactcache.py", line 770, in pull
          File "/usr/lib/python3.8/site-packages/buildstream/_artifactcache/cascache.py", line 262, in pull
          File "/usr/lib/python3.8/site-packages/buildstream/_artifactcache/cascache.py", line 1062, in init
        OSError: [Errno 24] Too many open files: '/cache-certificate/server.crt'
    
        During handling of the above exception, another exception occurred:
    
        Traceback (most recent call last):
          File "/usr/lib/python3.8/site-packages/buildstream/_scheduler/jobs/job.py", line 384, in _child_action
          File "/usr/lib/python3.8/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
          File "/usr/lib/python3.8/site-packages/buildstream/_scheduler/queues/pullqueue.py", line 38, in process
          File "/usr/lib/python3.8/site-packages/buildstream/element.py", line 1712, in _pull
          File "/usr/lib/python3.8/site-packages/buildstream/element.py", line 1676, in _pull_strong
          File "/usr/lib/python3.8/site-packages/buildstream/_artifactcache/artifactcache.py", line 778, in pull
        NameError: name 'BlobNotFound' is not defined
```
## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)
https://gitlab.com/BuildStream/buildstream/-/blob/bst-1/buildstream/_artifactcache/artifactcache.py#L778
## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @nanonyme]](https://gitlab.com/nanonyme) on Oct 6, 2020, 17:47

changed title from **{-Undefined exception raise-}d by bst 1.6.0** to **{+NameError while processing BlobNotFoun+}d by bst 1.6.0**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @nanonyme]](https://gitlab.com/nanonyme) on Oct 6, 2020, 17:47

The original error may be same as in https://gitlab.com/BuildStream/buildstream/-/issues/1382

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @nanonyme]](https://gitlab.com/nanonyme) on Oct 6, 2020, 18:44

mentioned in merge request !2082

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @nanonyme]](https://gitlab.com/nanonyme) on Oct 7, 2020, 07:19

mentioned in merge request !2083
