### ISSUE TITLE
Unhandled exception in utils._force_rmtree()

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#153]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/153)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Nov 13, 2017, 10:24

This happened today during a GNOME build:

```
[--:--:--] BUG     [apps/qqwing.bst]: Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/codethink/GNOME/buildstream/buildstream/_scheduler/job.py", line 265, in child_action
        result = self.action(element)
      File "/codethink/GNOME/buildstream/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/codethink/GNOME/buildstream/buildstream/element.py", line 1135, in _assemble
        cleanup_rootdir()
      File "/codethink/GNOME/buildstream/buildstream/element.py", line 1058, in cleanup_rootdir
        utils._force_rmtree(rootdir)
      File "/codethink/GNOME/buildstream/buildstream/utils.py", line 481, in _force_rmtree
        shutil.rmtree(rootpath, **kwargs)
      File "/usr/lib/python3.5/shutil.py", line 480, in rmtree
        _rmtree_safe_fd(fd, path, onerror)
      File "/usr/lib/python3.5/shutil.py", line 418, in _rmtree_safe_fd
        _rmtree_safe_fd(dirfd, fullname, onerror)
      File "/usr/lib/python3.5/shutil.py", line 418, in _rmtree_safe_fd
        _rmtree_safe_fd(dirfd, fullname, onerror)
      File "/usr/lib/python3.5/shutil.py", line 438, in _rmtree_safe_fd
        onerror(os.unlink, fullname, sys.exc_info())
      File "/usr/lib/python3.5/shutil.py", line 436, in _rmtree_safe_fd
        os.unlink(name, dir_fd=topfd)
    IsADirectoryError: [Errno 21] Is a directory: 'mount'
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Nov 14, 2017, 17:42

I can't seem to reproduce this locally, but it looks like this may have been caused by a sandbox failing to unmount a directory.

Both implementations check quite thoroughly for this, as far as I am aware, are there any other messages in the logs for this?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @franred]](https://gitlab.com/franred) on Jul 11, 2018, 22:34

I've reproduce this issue aborting a build using "ctrl + c"

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 2, 2018, 22:23

mentioned in commit 7cc121fee74f15165c3bd23ed312b136e6fd5a17

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 2, 2018, 22:24

mentioned in merge request !849

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 2, 2018, 22:25

!849 should fix it.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 4, 2018, 15:55

mentioned in commit 26d48cc9c3870eb9ca3dd7816d32b8fe0606414e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 4, 2018, 15:56

mentioned in commit a79842185f3e762154002c6e928da30d6745568b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 4, 2018, 15:57

mentioned in merge request !861

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Oct 4, 2018, 16:31

mentioned in commit b7b20d9e7c46d8b3bc7541437cc66905ffd28fc0
