### ISSUE TITLE
Build of gnome-build-meta.git is broken

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#202]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/202)
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 22, 2018, 15:30

Following the instructions from https://wiki.gnome.org/Newcomers/BuildSystemComponent leads to an internal error with latest BuildStream:

```
bst --no-strict build --track-all --track-save core-deps/gtk+-3.bst
[--:--:--] START   Loading pipeline
[00:00:00] SUCCESS Loading pipeline
[--:--:--] START   Resolving pipeline
[00:00:00] SUCCESS Resolving pipeline
[--:--:--] START   Initializing remote caches
[00:00:00] SUCCESS Initializing remote caches
[--:--:--] START   Resolving cached state
[00:00:00] SUCCESS Resolving cached state

BuildStream Version 1.0.1.dev61+g43bc41b
  Session Start: Monday, 22-01-2018 at 15:28:37
  Project:       gnome (/home/shared/src/gnome-build-meta)
  Targets:       core-deps/gtk+-3.bst

User Configuration
  Configuration File:      /home/sam/.config/buildstream.conf
  Log Files:               /home/sam/cache/buildstream/logs
  Source Mirrors:          /home/sam/cache/buildstream/sources
  Build Area:              /home/sam/cache/buildstream/build
  Artifact Cache:          /home/sam/cache/buildstream/artifacts
  Maximum Fetch Tasks:     10
  Maximum Build Tasks:     4
  Maximum Push Tasks:      4
  Maximum Network Retries: 2

Project Options
  arch: x86_64

Pipeline
no reference ???????? base/base-system.bst 
     waiting ???????? base/base-configure.bst 
no reference ???????? base/linker-priority.bst 
no reference ???????? base/ninja.bst 
downloadable ???????? base.bst 
no reference ???????? core-deps/gettext.bst 
no reference ???????? core-deps/yelp-xsl.bst 
no reference ???????? core-deps/yelp-tools.bst 
no reference ???????? core-deps/gtk-doc.bst 
no reference ???????? core-deps/glib.bst 
no reference ???????? core-deps/gobject-introspection.bst 
no reference ???????? core-deps/meson.bst 
no reference ???????? core-deps/atk.bst 
no reference ???????? core-deps/gdk-pixbuf.bst 
no reference ???????? core-deps/harfbuzz.bst 
no reference ???????? core-deps/pango.bst 
no reference ???????? core-deps/wayland.bst 
no reference ???????? core-deps/wayland-protocols.bst 
no reference ???????? core/at-spi2-core.bst 
no reference ???????? core/at-spi2-atk.bst 
no reference ???????? core-deps/gtk+-3.bst 
\~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[--:--:--] START   Starting build
[--:--:--][????????][ pull:base.bst                      ] START   gnome/base/????????-pull.9456.log
[00:00:00][????????][ pull:base.bst                      ] WARNING Try #1 failed, retrying
[--:--:--][????????][track:base/base-system.bst          ] START   gnome/base-base-system/????????-track.9458.log
[--:--:--][????????][track:base/base-system.bst          ] STATUS  Creating local mirror for http://gnome7.codethink.co.uk/repo
[--:--:--][????????][track:base/linker-priority.bst      ] START   gnome/base-linker-priority/????????-track.9460.log
[00:00:00][????????][track:base/linker-priority.bst      ] SUCCESS gnome/base-linker-priority/????????-track.9460.log
[--:--:--][????????][track:base/ninja.bst                ] START   gnome/base-ninja/????????-track.9462.log
[--:--:--][????????][track:base/ninja.bst                ] INFO    Found new revision: None
[00:00:00][????????][track:base/ninja.bst                ] SUCCESS gnome/base-ninja/????????-track.9462.log
[--:--:--][????????][track:core-deps/yelp-xsl.bst        ] START   gnome/core-deps-yelp-xsl/????????-track.9467.log
[--:--:--][????????][track:core-deps/yelp-xsl.bst        ] START   Tracking master from https://git.gnome.org/browse/yelp-xsl
[--:--:--][????????][track:core-deps/gettext.bst         ] START   gnome/core-deps-gettext/????????-track.9469.log
[--:--:--][????????][track:core-deps/gettext.bst         ] START   Tracking https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
[--:--:--][????????][track:core-deps/yelp-tools.bst      ] START   gnome/core-deps-yelp-tools/????????-track.9474.log
[--:--:--][????????][track:core-deps/yelp-tools.bst      ] START   Tracking master from https://git.gnome.org/browse/yelp-tools
[--:--:--][????????][track:core-deps/gtk-doc.bst         ] START   gnome/core-deps-gtk-doc/????????-track.9478.log
[--:--:--][????????][track:core-deps/gtk-doc.bst         ] START   Tracking master from https://git.gnome.org/browse/gtk-doc
[--:--:--][????????][ pull:base.bst                      ] START   gnome/base/????????-pull.9506.log
[00:00:00][????????][ pull:base.bst                      ] WARNING Try #2 failed, retrying
[--:--:--][????????][fetch:base/linker-priority.bst      ] START   gnome/base-linker-priority/????????-fetch.9510.log
[00:00:00][????????][fetch:base/linker-priority.bst      ] SUCCESS gnome/base-linker-priority/????????-fetch.9510.log
====================================== 00:00:00 gnome (21/21) ======================================
                  (Tracked:0 4 0)→ (Pulled:0 3 0)→ (Fetched:0 1 0)→ (Built:0 0 0)                  
                                      ~~~~~ Active Tasks ~~~~~                                      
[00:00:00][Pull:base.bst                 ] [00:00:00][Track:base/base-system.bst               ]
[00:00:00][Track:core-deps/yelp-xsl.bst  ] [00:00:00][Track:core-deps/gettext.bst              ]
[00:00:00][Track:core-deps/yelp-tools.bst] [00:00:00][Track:core-deps/gtk-doc.bst              ]
[00:00:00][Track:core-deps/glib.bst      ] [00:00:00][Track:core-deps/gobject-introspection.bst]
[00:00:00][Fetch:base/linker-priority.bst] [00:00:00][Fetch:base/ninja.bst                     ]
Unknown exception in SIGCHLD handler
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 810, in _sig_chld
    self._do_waitpid_all()
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 876, in _do_waitpid_all
    self._do_waitpid(pid)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 910, in _do_waitpid
[--:--:--][????????][ pull:base.bst                      ] START   gnome/base/????????-pull.9516.log
[00:00:00][????????][ pull:base.bst                      ] FAILURE Cache key missing

    Printing the last 20 lines from log file:
    /home/sam/cache/buildstream/logs/gnome/base/????????-pull.9516.log
    ======================================================================
    [--:--:--] START   [base.bst]     : Pull
    [--:--:--] LOG     [base.bst]     : Build environment for element base.bst
    
        HOME: /tmp
        LC_ALL: en_US.UTF-8
        LDFLAGS: -L/usr/lib
        LD_LIBRARY_PATH: /usr/lib
        LOGNAME: tomjon
        PATH: /usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin
        PKG_CONFIG_PATH: /usr/local/lib/pkgconfig:/usr/lib/pkgconfig
        SHELL: /bin/sh
        SOURCE_DATE_EPOCH: '1320937200'
        TERM: dumb
        TZ: UTC
        USER: tomjon
        USERNAME: tomjon
    [00:00:00] FAILURE [base.bst]     : Cache key missing
    ======================================================================

[--:--:--][????????][ main:base/base-system.bst          ] STATUS  Track suspending
[--:--:--][????????][ main:core-deps/yelp-xsl.bst        ] STATUS  Track suspending
[--:--:--][????????][ main:core-deps/gettext.bst         ] STATUS  Track suspending
[--:--:--][????????][ main:core-deps/yelp-tools.bst      ] STATUS  Track suspending
[--:--:--][????????][ main:core-deps/gtk-doc.bst         ] STATUS  Track suspending
[--:--:--][????????][ main:core-deps/glib.bst            ] STATUS  Track suspending
[--:--:--][????????][ main:core-deps/gobject-introspection.bst] STATUS  Track suspending
[--:--:--][????????][ main:base/ninja.bst                ] STATUS  Fetch suspending

Pull failure on element: base.bst

Choose one of the following options:
  (c)ontinue  - Continue queueing jobs as much as possible
  (q)uit      - Exit after all ongoing jobs complete
  (t)erminate - Terminate any ongoing jobs and exit
  (r)etry     - Retry this job
  (l)og       - View the full log file

Pressing ^C will terminate jobs and exit

Choice: [continue]: 
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 22, 2018, 15:32

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 22, 2018, 15:32

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 22, 2018, 15:37

This also occurs with current master (f490343d98e40f9c9b651aa02f351d0bbee9afd9)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 22, 2018, 17:23

This is reproducible every time if you have an empty source cache and artifact cache.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield) on Jan 22, 2018, 17:58

mentioned in merge request !250

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jan 22, 2018, 18:30

This looks like a regression from the state handling changes by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) - i thought this was fixed last week wasnt it ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 22, 2018, 19:54

mentioned in commit 00c29a7e007b10747f0b45317dc70974f5d022b4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 23, 2018, 09:45

Last week's fix was for source state handling. There is apparently also an issue with element state handling in non-strict mode. I'm looking into it.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 23, 2018, 12:33

mentioned in commit 4df5d035f62ecee62d679323e4e770625957827c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jan 23, 2018, 12:36

mentioned in merge request !253

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jan 23, 2018, 17:15

closed via merge request !253
