### ISSUE TITLE
BuildStream crashes if the dependency tree is too deep

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#203]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/203)
In GitLab by [[Gitlab user @awacheux]](https://gitlab.com/awacheux) on Jan 23, 2018, 11:06

If the dependency tree depth exeeds 1000, BuildStream crashes throwing a `RecursionError`.

I think it shouldn't crash but print something like `The dependency tree is too deep`.

Below is the full stack trace:

```
[--:--:--] START   Loading pipeline
Traceback (most recent call last):
  File "/usr/local/bin/bst", line 11, in <module>
    load_entry_point('BuildStream', 'console_scripts', 'bst')()
  File "/usr/lib/python3/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/buildstream/buildstream/_frontend/main.py", line 137, in override_main
    standalone_mode=standalone_mode, **extra)
  File "/usr/lib/python3/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/buildstream/buildstream/_frontend/main.py", line 459, in show
    app.initialize(elements, except_=except_, use_configured_remote_caches=downloadable)
  File "/buildstream/buildstream/_frontend/main.py", line 864, in initialize
    rewritable=rewritable)
  File "/buildstream/buildstream/_pipeline.py", line 131, in __init__
    meta_elements = loader.load(rewritable, None)
  File "/buildstream/buildstream/_loader.py", line 225, in load
    self.load_file(target, rewritable, ticker)
  File "/buildstream/buildstream/_loader.py", line 282, in load_file
    self.load_file(dep.name, rewritable, ticker)
  File "/buildstream/buildstream/_loader.py", line 282, in load_file
    self.load_file(dep.name, rewritable, ticker)
  File "/buildstream/buildstream/_loader.py", line 282, in load_file
    self.load_file(dep.name, rewritable, ticker)
  [Previous line repeated 946 more times]
  File "/buildstream/buildstream/_loader.py", line 273, in load_file
    data = _yaml.load(fullpath, shortname=filename, copy_tree=rewritable)
  File "/buildstream/buildstream/_yaml.py", line 180, in load
    return load_data(f, shortname=shortname, copy_tree=copy_tree)
  File "/buildstream/buildstream/_yaml.py", line 191, in load_data
    contents = yaml.load(data, yaml.loader.RoundTripLoader)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/main.py", line 636, in load
    return loader._constructor.get_single_data()  # type: ignore
  File "/usr/lib/python3/dist-packages/ruamel/yaml/constructor.py", line 102, in get_single_data
    node = self.composer.get_single_node()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 75, in get_single_node
    document = self.compose_document()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 96, in compose_document
    node = self.compose_node(None, None)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 130, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 163, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 132, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 194, in compose_mapping_node
    item_value = self.compose_node(node, item_key)
  File "/usr/lib/python3/dist-packages/ruamel/yaml/composer.py", line 106, in compose_node
    if self.parser.check_event(AliasEvent):
  File "/usr/lib/python3/dist-packages/ruamel/yaml/parser.py", line 144, in check_event
    self.current_event = self.state()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/parser.py", line 572, in parse_block_mapping_value
    if self.scanner.check_token(ValueToken):
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 1620, in check_token
    self._gather_comments()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 1662, in _gather_comments
    self.fetch_more_tokens()
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 304, in fetch_more_tokens
    if self.check_plain():
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 788, in check_plain
    if self.scanner_processing_version == (1, 1):
  File "/usr/lib/python3/dist-packages/ruamel/yaml/scanner.py", line 152, in scanner_processing_version
    return self.loader.processing_version  # type: ignore
  File "/usr/lib/python3/dist-packages/ruamel/yaml/resolver.py", line 443, in processing_version
    version = self.parser.yaml_version
RecursionError: maximum recursion depth exceeded
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jan 25, 2018, 16:02

We can change the limit using https://docs.python.org/3/library/sys.html#sys.setrecursionlimit but it would still be a finite number so we may want to do both - increase the limit _and_ make this exception nicer.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Feb 28, 2018, 08:37

Marking critical for stack trace; at the *very least* we should be able to print a reasonable error message instead (at best, we can process the tree without the recursion, that is difficult to change as a lot of code already assumes this).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 18, 2018, 17:36

Todo list to get this issue to an acceptable state:
* [x]  Create test case reproducing the issue on the current version of BuildStream.
* [x]  Properly handle RecursionError/Runtime exception.
* [ ]  Add configuration option which allows the maximum recursion depth to be set. I'm thinking that this could be set in project.conf.

Falling back to processing the tree non-recursively can be looked into after these have been done.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 20, 2018, 10:50

assigned to [[Gitlab user @phildawson]](https://gitlab.com/phildawson)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 20, 2018, 15:07

mentioned in commit 0a4d0c5d6df1edded630eca888ccccfd123e733a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 20, 2018, 15:07

mentioned in commit fd6a1f5b489bfacb4294de59a1016af571273f06

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 21, 2018, 15:53

mentioned in commit cb576619ca2f1fc423ddc5d9503bbfb145b962ac

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 21, 2018, 16:00

mentioned in merge request !512

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jun 21, 2018, 16:24

Just commented this on Phil's MR:

I'm a bit concerned about the ability to increase the stack limit arbitrarily. I assume (although I've no idea really) that the Python runtime will choose a default which avoids crashing the stack into something else. The docs just say "a too-high limit can lead to a crash." which is a bit vague. You might end up with unpredictable behaviour which is worse than the original stack trace and error.

Perhaps we could have a minimum stack size specified in the config file, and if the runtime default isn't high enough, throw an error on startup?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jun 21, 2018, 16:47

mentioned in commit 46cdf937c43a93bdb81bd181921f2af947059462

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jul 3, 2018, 10:44

mentioned in commit c8f0353ee257280b95d764de60a2ee41bb4d4ff0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jul 17, 2018, 09:08

mentioned in commit 6d2d068b39da48c739974c4a0c78ea4668130b10

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jul 17, 2018, 09:11

mentioned in commit c1be39d465f9d9ab18542f14b7ce2724473b1be8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jul 20, 2018, 11:07

Reviewed !512, needs a very small change but otherwise good

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Jul 23, 2018, 09:56

mentioned in commit 2bff390d1d9bb914b92c120b33bf8979a6a3d83d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Jul 25, 2018, 14:03

mentioned in commit a0ad985f7b342d68a19803ae23319eac3b895550

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 1, 2018, 10:44

unassigned [[Gitlab user @phildawson]](https://gitlab.com/phildawson)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 1, 2018, 17:26

BuildStream now gracefully handles the exception thrown when max recursion depth is exceeded.

It was decided that an option to increase the allowed recursion depth should not be added. If this issue is encountered in a real life project then we will investigate refactoring eliminate the offending recursion.

Related discussion: https://gitlab.com/BuildStream/buildstream/merge_requests/512#note_83270028

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 1, 2018, 17:26

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 14:17

This is a bug affecting 1.2. It should be backported.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 14:32

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 15:49

mentioned in commit 9627e6a99b59ebd21cbe3c25c5d2a2fa5005640a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 15:52

mentioned in merge request !654

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 14, 2018, 06:33

mentioned in commit b82d67938d984f52dd9f24cd0f6fc0874df3639c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 14, 2018, 08:13

This is backported in !654

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 14, 2018, 08:13

closed
