### ISSUE TITLE
Error when trying to "bst shell" in a component

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#230]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/230)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Feb 5, 2018, 17:13

```
[jjardon[[Gitlab user @edoras]](https://gitlab.com/edoras) gnome-build-meta (master)]$ bst build --track-all --track-save core-deps/glib.bst
[--:--:--] START   Loading pipeline
[00:00:00] SUCCESS Loading pipeline
[--:--:--] START   Resolving pipeline
[00:00:00] SUCCESS Resolving pipeline
[--:--:--] START   Initializing remote caches
[00:00:00] SUCCESS Initializing remote caches
[--:--:--] START   Resolving cached state
[00:00:00] SUCCESS Resolving cached state

BuildStream Version 1.0.1.dev87+g315c4ef
  Session Start: Monday, 05-02-2018 at 17:10:53
  Project:       gnome (/home/jjardon/gnome/gnome-build-meta)
  Targets:       core-deps/glib.bst

User Configuration
  Configuration File:      Default Configuration
  Log Files:               /home/jjardon/.cache/buildstream/logs
  Source Mirrors:          /home/jjardon/.cache/buildstream/sources
  Build Area:              /home/jjardon/.cache/buildstream/build
  Artifact Cache:          /home/jjardon/.cache/buildstream/artifacts
  Maximum Fetch Tasks:     10
  Maximum Build Tasks:     4
  Maximum Push Tasks:      4
  Maximum Network Retries: 2

Project Options
  arch: x86_64

Pipeline
no reference ???????? base/base-system.bst 
     waiting ???????? base/base-configure.bst 
no reference ???????? base/linker-priority.bst 
no reference ???????? base/ninja.bst 
     waiting ???????? base.bst 
no reference ???????? core-deps/gettext.bst 
no reference ???????? core-deps/yelp-xsl.bst 
no reference ???????? core-deps/yelp-tools.bst 
no reference ???????? core-deps/gtk-doc.bst 
no reference ???????? core-deps/glib.bst 

[--:--:--] START   Starting build
[--:--:--][????????][track:base/base-system.bst      ] START   gnome/base-base-system/????????-track.17983.log
[--:--:--][????????][track:base/base-system.bst      ] STATUS  Creating local mirror for http://gnome7.codethink.co.uk/repo
[--:--:--][????????][track:base/linker-priority.bst  ] START   gnome/base-linker-priority/????????-track.17985.log
[00:00:00][????????][track:base/linker-priority.bst  ] SUCCESS gnome/base-linker-priority/????????-track.17985.log
[--:--:--][????????][track:base/ninja.bst            ] START   gnome/base-ninja/????????-track.17987.log
[00:00:00][????????][track:base/ninja.bst            ] SUCCESS gnome/base-ninja/????????-track.17987.log
[--:--:--][????????][track:core-deps/yelp-xsl.bst    ] START   gnome/core-deps-yelp-xsl/????????-track.17992.log
[--:--:--][????????][track:core-deps/yelp-xsl.bst    ] START   Tracking master from https://git.gnome.org/browse/yelp-xsl
[--:--:--][????????][track:core-deps/gettext.bst     ] START   gnome/core-deps-gettext/????????-track.17994.log
[--:--:--][????????][track:core-deps/gettext.bst     ] START   Tracking https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
[--:--:--][????????][track:core-deps/yelp-tools.bst  ] START   gnome/core-deps-yelp-tools/????????-track.17997.log
[--:--:--][????????][track:core-deps/yelp-tools.bst  ] START   Tracking master from https://git.gnome.org/browse/yelp-tools
[--:--:--][????????][track:core-deps/glib.bst        ] START   gnome/core-deps-glib/????????-track.18006.log
[--:--:--][????????][track:core-deps/glib.bst        ] START   Tracking master from https://git.gnome.org/browse/glib
[--:--:--][????????][track:core-deps/gtk-doc.bst     ] START   gnome/core-deps-gtk-doc/????????-track.18002.log
[--:--:--][????????][track:core-deps/gtk-doc.bst     ] START   Tracking master from https://git.gnome.org/browse/gtk-doc
[00:00:00][????????][track:core-deps/yelp-xsl.bst    ] SUCCESS Tracking master from https://git.gnome.org/browse/yelp-xsl
[00:00:00][????????][track:core-deps/yelp-xsl.bst    ] SUCCESS gnome/core-deps-yelp-xsl/????????-track.17992.log
[00:00:00][????????][track:core-deps/yelp-tools.bst  ] SUCCESS Tracking master from https://git.gnome.org/browse/yelp-tools
[00:00:00][????????][track:core-deps/yelp-tools.bst  ] SUCCESS gnome/core-deps-yelp-tools/????????-track.17997.log
[00:00:00][????????][track:core-deps/gtk-doc.bst     ] SUCCESS Tracking master from https://git.gnome.org/browse/gtk-doc
[00:00:00][????????][track:core-deps/gtk-doc.bst     ] SUCCESS gnome/core-deps-gtk-doc/????????-track.18002.log
[--:--:--][????????][track:base/base-system.bst      ] START   Fetching tracking ref 'debian/testing/amd64' from origin: http://gnome7.codethink.co.uk/repo
[00:00:01][????????][track:core-deps/glib.bst        ] SUCCESS Tracking master from https://git.gnome.org/browse/glib
[00:00:01][????????][track:core-deps/glib.bst        ] SUCCESS gnome/core-deps-glib/????????-track.18006.log
[00:00:00][????????][track:base/base-system.bst      ] SUCCESS Fetching tracking ref 'debian/testing/amd64' from origin: http://gnome7.codethink.co.uk/repo
[00:00:01][????????][track:base/base-system.bst      ] SUCCESS gnome/base-base-system/????????-track.17983.log
[00:00:01][????????][track:core-deps/gettext.bst     ] SUCCESS Tracking https://ftp.gnu.org/gnu/gettext/gettext-0.19.8.1.tar.xz
[00:00:01][????????][track:core-deps/gettext.bst     ] SUCCESS gnome/core-deps-gettext/????????-track.17994.log
[00:00:02] SUCCESS Build Complete

Pipeline Summary
  Total:       10
  Session:     10
  Track Queue: processed 0, skipped 10, failed 0 
  Pull Queue:  processed 0, skipped 4,  failed 0 
  Fetch Queue: processed 0, skipped 3,  failed 0 
  Build Queue: processed 0, skipped 3,  failed 0 
[jjardon[[Gitlab user @edoras]](https://gitlab.com/edoras) gnome-build-meta (master)]$ bst shell core-deps/glib.bst
[--:--:--] START   Loading pipeline
[00:00:00] SUCCESS Loading pipeline
[--:--:--] START   Resolving pipeline
[00:00:00] SUCCESS Resolving pipeline
[--:--:--] START   Resolving cached state
[00:00:01] SUCCESS Resolving cached state
[--:--:--] START   Staging dependencies
Traceback (most recent call last):
  File "/home/jjardon/.local/bin/bst", line 8, in <module>
    sys.exit(cli())
  File "/home/jjardon/.local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/jjardon/.local/lib/python3.6/site-packages/buildstream/_frontend/main.py", line 142, in override_main
    standalone_mode=standalone_mode, **extra)
  File "/home/jjardon/.local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/jjardon/.local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/jjardon/.local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/jjardon/.local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/jjardon/.local/lib/python3.6/site-packages/click/decorators.py", line 27, in new_func
    return f(get_current_context().obj, *args, **kwargs)
  File "/home/jjardon/.local/lib/python3.6/site-packages/buildstream/_frontend/main.py", line 534, in shell
    exitcode = app.pipeline.targets[0]._shell(scope, sysroot, command=command)
  File "/home/jjardon/.local/lib/python3.6/site-packages/buildstream/element.py", line 1354, in _shell
    with self._prepare_sandbox(scope, directory) as sandbox:
  File "/usr/lib/python3.6/contextlib.py", line 81, in __enter__
    return next(self.gen)
  File "/home/jjardon/.local/lib/python3.6/site-packages/buildstream/element.py", line 1328, in _prepare_sandbox
    self.stage_dependency_artifacts(sandbox, scope)
  File "/home/jjardon/.local/lib/python3.6/site-packages/buildstream/element.py", line 486, in stage_dependency_artifacts
    element_project = element._get_project()
AttributeError: 'NoneType' object has no attribute '_get_project'
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Feb 5, 2018, 17:13

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Feb 6, 2018, 18:20

I received the same error when using the shell command for Gtk+3 ![gtk3](/uploads/121f51030c8c091e4410d99205221e79/gtk3.png)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Feb 6, 2018, 18:32

marked this issue as a duplicate of #225

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Feb 6, 2018, 18:32

closed
