### ISSUE TITLE
Build sometimes hangs forever after "Unknown exception in SIGCHLD handler"

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#299]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/299)
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Mar 13, 2018, 18:42

Sometimes BuildStream hits this error in job.py, after which the build will continue forever and ever until I Ctrl+C. I don't know what's needed to trigger this error condition. It happens to me every few days.

```
[00:00:00][01b48bc7][build:core/glib-networking.bst      ] SUCCESS Running strip-commands
[00:00:15][01b48bc7][build:core/glib-networking.bst      ] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 265, in child_action
        result = self.action(element)
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/element.py", line 1125, in _assemble
        self._assemble_done()
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/element.py", line 814, in _assemble_done
        assert(self.__assemble_scheduled)
    AssertionError

======================================== 00:00:33 gnome (13/13) ========================================
                   (Tracked:1 12 0)→ (Pulled:0 13 0)→ (Fetched:0 13 0)→ (Built:0 12 0)                   
                                        ~~~~~ Active Tasks ~~~~~                                        
00:00:15[Build:core/glib-networking.bst]
Unknown exception in SIGCHLD handler
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 810, in _sig_chld
    self._do_waitpid_all()
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 876, in _do_waitpid_all
    self._do_waitpid(pid)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 910, in _do_waitpid
    callback(pid, returncode, *args)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 327, in child_complete
    self.complete(self, returncode, element)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/queue.py", line 212, in job_done
    if self.done(element, job.result, returncode):
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/buildqueue.py", line 51, in done
    element._assemble_done()
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 14, 2018, 10:48

[[Gitlab user @juergbi]](https://gitlab.com/juergbi) possible fallout from centralizing state handling ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Mar 14, 2018, 16:22

I've noticed this twice today, and managed to reproduce it. It happens when I retry a failed build (it was a workspace, but even putting my changes in a patch source and closing the workspace, I get the same error).

It might be unrelated, but when I answer shell in the failed build prompt instead, I find an empty `/buildstream/build`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 15, 2018, 06:59

I have encountered something disturbing while working on my side branch.

I found that; when an exception is raised and unhandled in `Job.child_complete()`, the message *"Unknown exception in SIGCHLD handler"* is fired.

This is a bit disturbing. I am expecting the child watcher callback to fire *inside the loop*, the said message seems to indicate that the client callback is getting called *inside the signal handler*.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 15, 2018, 12:26

> _"Unknown exception in SIGCHLD handler"_

This message is from `asyncio`. As far as I can tell, the `asyncio` signal handlers are always event loop based. The message above means that there was an unknown exception in the asynchronously scheduled SIGCHLD handler, not in the real low-level signal handler.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Mar 15, 2018, 15:58

mentioned in commit 4b644abac6a81571b3d674c96bf9669f8a86ef8e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 15, 2018, 16:41

closed via merge request !320

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Mar 19, 2018, 22:42

Reopening, this is still happening even after !320. The backtrace is somewhat different now, though:

```
Unknown exception in SIGCHLD handler
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 810, in _sig_chld
    self._do_waitpid_all()
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 876, in _do_waitpid_all
    self._do_waitpid(pid)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 910, in _do_waitpid
    callback(pid, returncode, *args)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 327, in child_complete
    self.complete(self, returncode, element)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/queue.py", line 212, in job_done
    if self.done(element, job.result, returncode):
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/trackqueue.py", line 91, in done
    element._update_state()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/element.py", line 1573, in _update_state
    source._update_state()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/source.p
```

I hit this error running `bst build core.bst`. No retry required. Seems the task that hung is `Track:core/gnome-control-center.bst`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Mar 19, 2018, 22:42

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Mar 19, 2018, 22:51

100% reproducible. I get a more interesting traceback when running track manually:

```
$ bst track core/gnome-control-center.bst
[--:--:--][][] START   Loading pipeline
[00:00:00][][] SUCCESS Loading pipeline
[--:--:--][][] START   Resolving pipeline
[00:00:00][][] SUCCESS Resolving pipeline
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state

BuildStream Version 1.1.2.dev47+g024a37c
  Session Start: Monday, 19-03-2018 at 17:46:54
  Project:       gnome (/home/mcatanzaro/Projects/gnome-build-meta)
  Targets:       core/gnome-control-center.bst

User Configuration
  Configuration File:      Default Configuration
  Log Files:               /home/mcatanzaro/.cache/buildstream/logs
  Source Mirrors:          /home/mcatanzaro/.cache/buildstream/sources
  Build Area:              /home/mcatanzaro/.cache/buildstream/build
  Artifact Cache:          /home/mcatanzaro/.cache/buildstream/artifacts
  Maximum Fetch Tasks:     10
  Maximum Build Tasks:     4
  Maximum Push Tasks:      4
  Maximum Network Retries: 2

Project Options
  arch: x86_64

Pipeline
no reference ???????? core/gnome-control-center.bst 

[--:--:--][][] START   Starting track
[--:--:--][????????][track:core/gnome-control-center.bst ] START   home/mcatanzaro/.cache/buildstream/logs/gnome/core-gnome-control-center/????????-track.9327.log
[--:--:--][????????][track:core/gnome-control-center.bst ] START   Tracking master from https://git.gnome.org/browse/gnome-control-center
[00:00:01][????????][track:core/gnome-control-center.bst ] SUCCESS Tracking master from https://git.gnome.org/browse/gnome-control-center
[00:00:01][????????][track:core/gnome-control-center.bst ] SUCCESS home/mcatanzaro/.cache/buildstream/logs/gnome/core-gnome-control-center/????????-track.9327.log
============================ 00:00:01 gnome (1/92) ============================
                                (Tracked:0 0 0)                                
                            ~~~~~ Active Tasks ~~~~~                            
[00:00:01][Track:core/gnome-control-center.bst]
Unknown exception in SIGCHLD handler
Traceback (most recent call last):
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 810, in _sig_chld
    self._do_waitpid_all()
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 876, in _do_waitpid_all
    self._do_waitpid(pid)
  File "/usr/lib64/python3.6/asyncio/unix_events.py", line 910, in _do_waitpid
    callback(pid, returncode, *args)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 327, in child_complete
    self.complete(self, returncode, element)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/queue.py", line 212, in job_done
    if self.done(element, job.result, returncode):
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/trackqueue.py", line 91, in done
    element._update_state()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/element.py", line 1573, in _update_state
    source._update_state()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/source.py", line 303, in _update_state
    self.__consistency = self.get_consistency()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/plugins/sources/git.py", line 290, in get_consistency
    if self.have_all_refs():
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/plugins/sources/git.py", line 375, in have_all_refs
    self.refresh_submodules()
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/plugins/sources/git.py", line 403, in refresh_submodules
    ref = self.mirror.submodule_ref(path)
  File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/plugins/sources/git.py", line 231, in submodule_ref

User interrupted with ^C

Choose one of the following options:
  (c)ontinue  - Continue queueing jobs as much as possible
  (q)uit      - Exit after all ongoing jobs complete
  (t)erminate - Terminate any ongoing jobs and exit

Pressing ^C again will terminate jobs and exit

Choice: [continue]: t

Terminating all jobs at user request

[00:00:12][][] WARNING Terminated after updating 0 source references



Pipeline Summary
  Total:       92
  Session:     1
  Track Queue: processed 0, skipped 0, failed 0
```

Note it's coming from submodule code. It's probably related to https://gitlab.gnome.org/GNOME/gnome-control-center/commit/a1bace468352092c5f5ce5d03024f380e672502d. Perhaps BuildStream may not be prepared to handle a submodule disappearing?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 21, 2018, 15:59

mentioned in commit d246403e584969bcdac4a2d87ad64aaeab2ac850

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 21, 2018, 16:01

This will be fixed with !334 

Further, !333 fixes this such that any exceptions are handled more gracefully in the SIGCHLD handler, and there will not be any hangs in the case that failures or bugs occur in this area.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 21, 2018, 16:12

closed via merge request !334
