### ISSUE TITLE
`bst source-bundle` should get better documentation and receive test cases

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#310]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/310)
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Mar 20, 2018, 14:12

Currently, `bst source-bundle` only has documentation from `bst --help`, and has no tests *at all*. It makes up a fairly significant portion of our untested code.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Sep 13, 2018, 16:50

I tried to use this recently (`b3ffcdc8fcc8d150cf6d75acbc660379b3fc0fcb`) and it simply seems to crash
for me.

e.g.:

```
[--:--:--][][] BUG     [Errno 2] No such file or directory: '/home/danielsilverstone/.cache/buildstream/build/hello-hf8dr0o1/source/hello'

    Traceback (most recent call last):
      File "/home/danielsilverstone/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/danielsilverstone/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/danielsilverstone/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/danielsilverstone/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/danielsilverstone/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/danielsilverstone/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/danielsilverstone/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/danielsilverstone/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/danielsilverstone/buildstream/buildstream/_frontend/cli.py", line 831, in source_bundle
        except_targets=except_)
      File "/home/danielsilverstone/buildstream/buildstream/_stream.py", line 723, in source_bundle
        self._write_element_sources(tempdir, elements)
      File "/home/danielsilverstone/buildstream/buildstream/_stream.py", line 1092, in _write_element_sources
        element._stage_sources_at(element_source_dir)
      File "/home/danielsilverstone/buildstream/buildstream/element.py", line 1374, in _stage_sources_at
        if not vdirectory.is_empty():
      File "/home/danielsilverstone/buildstream/buildstream/storage/_filebaseddirectory.py", line 179, in is_empty
        self._populate_index()
      File "/home/danielsilverstone/buildstream/buildstream/storage/_filebaseddirectory.py", line 61, in _populate_index
        for entry in os.listdir(self.external_directory):
    FileNotFoundError: [Errno 2] No such file or directory: '/home/danielsilverstone/.cache/buildstream/build/hello-hf8dr0o1/source/hello'
```

I think it would be valuable if, on this issue, we could collate:

1. What was `bst source-bundle` intended to do
2. Do we still need that?
3. What has happened to mean that it doesn't work?
4. How do we fix that?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @LaurenceUrhegyi]](https://gitlab.com/LaurenceUrhegyi) on Oct 5, 2018, 14:11

I actually think we can close this since we decided to kill source-bundle - see #672

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 8, 2018, 10:18

> I actually think we can close this since we decided to kill source-bundle - see #672

For the record, #672 proposes a deprecation of `bst source-bundle` (which is different from *"removal"*, which is an API break).

The functionality in `bst source-bundle` will have to appear somewhere, and for the sake of backwards compatibility will need to still be exposed from `bst source-bundle` (even if we hide it from `bst --help` and raise a warning in case people use a deprecated API).

I don't think *closing* this is the right approach, this functionality still needs better test coverage.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 8, 2018, 10:31

> 1. What was `bst source-bundle` intended to do

This piece of code is intended for the cross-bootstrapping case, it is unclear at this time if it is possible (or practical) to implement this with remote execution instead.

The workflow of using `bst source-bundle` is intended to work like this:

* First tune your base kernel, compiler and C library to support this brand new machine architecture you just designed and have some test boards for

* Cross compile your base stack to target your new machine architecture, for which we must assume that there is no already existing runtime environment you can already use on that machine

* Repeat the first two steps until you have a booting system, with the kernel, compiler and C runtime, plus bash and busybox and perhaps a few things like GNU sed that you might need in the early compile stages.

* Now run `bst source-bundle` on your project, using `--except` to exclude the base part of the bootstrap which you've already compiled and deployed to hardware. In theory, the project you use in `bst source-bundle` builds everything you need to run BuildStream.

* Now unpack the output of `bst source-bundle` on your new, booting machine, and run the generated script on that machine.

This might fail, in which you may need to modify your project and repeat the last two steps. Finally the goal is to have booted a system on your new hardware which is capable of running BuildStream, and building things for that target platform.

> 2. Do we still need that?

Yes.

> 3. What has happened to mean that it doesn't work?

Cannot say for sure, I have been careful to smoke test it when making changes over the last year, but I have not run a complete bootstrap with it, I think the last person to do that is [[Gitlab user @samthursfield]](https://gitlab.com/samthursfield).

I doubt that this stack trace happens in `bst-1.2`, probably only in `master` by the looks of the stack trace.

One thing contributing to this not working is certainly the blatant lack of test coverage (this is the one part which we have never added test coverage for, and probably accounts for our coverage only being around `~85%`).

> 4. How do we fix that?

Good question :)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Oct 10, 2019, 13:52

Closing this based on previous comments.

For posterity, `source-bundle` command was retired and its functionality was moved to `bst source checkout --include-build-scripts`. It has basic tests asserting that scripts are generated as expected. In case anyone wants to add more tests, it might be worth orchestrating a setup where those scripts are actually exercised.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Oct 10, 2019, 13:52

closed
