### ISSUE TITLE
buildstream fails with "EOFError: Compressed file ended before the end-of-stream marker was reached"

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#338]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/338)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Apr 4, 2018, 17:09

```
[00:00:03][1cbcd0f7][build:base/freedesktop-sdk-junction.bst:base/icu.bst] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 265, in child_action
        result = self.action(element)
      File "/usr/local/lib/python3.6/site-packages/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/usr/local/lib/python3.6/site-packages/buildstream/element.py", line 1084, in _assemble
        self.stage(sandbox)
      File "/usr/local/lib/python3.6/site-packages/buildstream/buildelement.py", line 189, in stage
        self.stage_sources(sandbox, self.get_variable('build-root'))
      File "/usr/local/lib/python3.6/site-packages/buildstream/element.py", line 568, in stage_sources
        self._stage_sources_in_sandbox(sandbox, directory)
      File "/usr/local/lib/python3.6/site-packages/buildstream/element.py", line 1485, in _stage_sources_in_sandbox
        self._stage_sources_at(host_directory, mount_workspaces=mount_workspaces)
      File "/usr/local/lib/python3.6/site-packages/buildstream/element.py", line 1509, in _stage_sources_at
        source._stage(directory)
      File "/usr/local/lib/python3.6/site-packages/buildstream/source.py", line 418, in _stage
        self.stage(staging_directory)
      File "/usr/local/lib/python3.6/site-packages/buildstream/plugins/sources/tar.py", line 108, in stage
        base_dir = self._find_base_dir(tar, self.base_dir)
      File "/usr/local/lib/python3.6/site-packages/buildstream/plugins/sources/tar.py", line 188, in _find_base_dir
        matches = sorted(list(utils.glob(paths, pattern)))
      File "/usr/local/lib/python3.6/site-packages/buildstream/utils.py", line 188, in glob
        for filename in paths:
      File "/usr/local/lib/python3.6/site-packages/buildstream/plugins/sources/tar.py", line 152, in _list_tar_paths
        for member in tar.getmembers():
      File "/usr/lib64/python3.6/tarfile.py", line 1758, in getmembers
        self._load()        # all members, we first have to
      File "/usr/lib64/python3.6/tarfile.py", line 2355, in _load
        tarinfo = self.next()
      File "/usr/lib64/python3.6/tarfile.py", line 2286, in next
        self.fileobj.seek(self.offset - 1)
      File "/usr/lib64/python3.6/gzip.py", line 368, in seek
        return self._buffer.seek(offset, whence)
      File "/usr/lib64/python3.6/_compression.py", line 143, in seek
        data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
      File "/usr/lib64/python3.6/gzip.py", line 482, in read
        raise EOFError("Compressed file ended before the "
    EOFError: Compressed file ended before the end-of-stream marker was reached
```

Full log here: https://gitlab.gnome.org/GNOME/gnome-build-meta/-/jobs/21281

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Apr 5, 2018, 08:02

Actually, the problem is that the track succeeds even though the file was not completely downloaded.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 5, 2018, 08:23

[[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk): Ah, I was about to ask if this was consistently reproducible with a given tarball...

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 5, 2018, 08:25

FWIW: For both fetch and track tasks, the code will go through `plugins/sources/_downloadablefilesource.py:_ensure_mirror()`

This looks broken, it seems that the code doesnt handle the case where the `etag` matches, but the file was already locally cached.

I think a reading of https://docs.python.org/3.4/howto/urllib2.html is necessary to make this more robust.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 7, 2018, 12:49

Ok so my bad; the code in `_downloadablefilesource.py` could do with some comments; it's not at all clear that a successful request over HTTP is going to raise an exception that we are supposed to check for response code `304` in order to determine that the file was not downloaded due to an etag match.

I've tried various combinations to reproduce but I am still unable to reproduce this.

Interestingly, I've noticed that when trying this on the icu tarball, the server hosting it is rather slow (at least when I tried it), and the tarball is rather huge (23MB)... so maybe this is happening spuriously with larger tarballs on unstable connections ?

If you have a way to consistently reproduce this, I would like to know...

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 2, 2018, 18:41

I have not seeing this for a long time, let's close it

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 2, 2018, 18:41

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @krichter]](https://gitlab.com/krichter) on May 19, 2020, 17:44

I'm seeing this with 1.4.3 (installed with `pip3`) on Ubuntu 20.04 with a very similar stacktrace (only a few changes and some offset in the line number, so probably the same issue):

```
[00:01:09][df6fd5f1][build:core-deps/libvirt.bst         ] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.8/dist-packages/buildstream/_scheduler/jobs/job.py", line 384, in _child_action
        result = self.child_process()
      File "/usr/local/lib/python3.8/dist-packages/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/_scheduler/queues/buildqueue.py", line 35, in process
        return element._assemble()
      File "/usr/local/lib/python3.8/dist-packages/buildstream/element.py", line 1533, in _assemble
        self.stage(sandbox)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/buildelement.py", line 174, in stage
        self.stage_sources(sandbox, self.get_variable('build-root'))
      File "/usr/local/lib/python3.8/dist-packages/buildstream/element.py", line 822, in stage_sources
        self._stage_sources_in_sandbox(sandbox, directory)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/element.py", line 1360, in _stage_sources_in_sandbox
        self._stage_sources_at(host_directory, mount_workspaces=mount_workspaces)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/element.py", line 1387, in _stage_sources_at
        source._stage(directory)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/source.py", line 704, in _stage
        self.stage(staging_directory)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/plugins/sources/tar.py", line 115, in stage
        base_dir = self._find_base_dir(tar, self.base_dir)
      File "/usr/local/lib/python3.8/dist-packages/buildstream/plugins/sources/tar.py", line 195, in _find_base_dir
        matches = sorted(list(utils.glob(paths, pattern)))
      File "/usr/local/lib/python3.8/dist-packages/buildstream/utils.py", line 205, in glob
        for filename in paths:
      File "/usr/local/lib/python3.8/dist-packages/buildstream/plugins/sources/tar.py", line 159, in _list_tar_paths
        for member in tar.getmembers():
      File "/usr/lib/python3.8/tarfile.py", line 1787, in getmembers
        self._load()        # all members, we first have to
      File "/usr/lib/python3.8/tarfile.py", line 2372, in _load
        tarinfo = self.next()
      File "/usr/lib/python3.8/tarfile.py", line 2303, in next
        self.fileobj.seek(self.offset - 1)
      File "/usr/lib/python3.8/lzma.py", line 253, in seek
        return self._buffer.seek(offset, whence)
      File "/usr/lib/python3.8/_compression.py", line 143, in seek
        data = self.read(min(io.DEFAULT_BUFFER_SIZE, offset))
      File "/usr/lib/python3.8/_compression.py", line 99, in read
        raise EOFError("Compressed file ended before the "
    EOFError: Compressed file ended before the end-of-stream marker was reached

```

I can open a new report as well, if you want. Unfortunately, I can't reproduce the issue reliably and cannot reconstruct the argument `bst` has been invoked with, I have seen it several times, though the last days with elements from https://gitlab.gnome.org/GNOME/gnome-build-meta.
