### ISSUE TITLE
AssertionError when caching artifact

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#347]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/347)
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Apr 9, 2018, 00:24

bst 1.1.2 crashes whenever it tries to build glib-networking. Note that I have an open workspace for it:

```
[--:--:--][????????][build:core/glib-networking.bst      ] START   Caching Artifact
[00:00:29][????????][build:core/glib-networking.bst      ] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 265, in child_action
        result = self.action(element)
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/element.py", line 1145, in _assemble
        self.__artifacts.commit(self, assembledir, self.__get_cache_keys_for_commit())
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_artifactcache/ostreecache.py", line 265, in commit
        refs = [buildref(element, key) for key in keys]
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_artifactcache/ostreecache.py", line 265, in <listcomp>
        refs = [buildref(element, key) for key in keys]
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_artifactcache/ostreecache.py", line 47, in buildref
        assert key is not None
    AssertionError
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Apr 9, 2018, 00:46

Errr, looks like it's now happening for WebKit.bst as well. :(

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 9, 2018, 05:46

This is another report of #316

Are you *sure* you have updated BuildStream to master and have https://gitlab.com/BuildStream/buildstream/commit/9012a5ed2f94704a99b3a2ac8f673160fca86668 from late last week ?

I'll try to see if I can reproduce in the meantime, if this is indeed not fixed; it would be nice if you could provide some additional information; the full build log as an attachment would be nice, along with the command you used to invoke BuildStream.

* I guess this is non-strict mode ?
* I guess that your open workspaces include `glib-networking` and `WebKit` ?
* Does this happen with `--track-all` ? Or is it reproducible with `bst build core-deps/WebKit.bst` ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 9, 2018, 09:26

I didnt notice that you mentioned `1.1.2` in the report, closing this as it's fixed since then.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Apr 9, 2018, 09:26

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on Apr 9, 2018, 19:43

Yes, I was using exactly version 1.1.2. I'd better try updating then, thanks!
