### ISSUE TITLE
_sandboxbwrap.py: Post-bwrap cleanup shouldn't attempt to remove preexisting folders

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#379]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/379)
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Apr 25, 2018, 16:19

**Problem**: According to comments [here](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/sandbox/_sandboxbwrap.py#L164) and [here](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/sandbox/_sandboxbwrap.py#L210), Bubblewrap-sandbox shouldn't try to remove some special folders (dev,tmp,proc) if they already exist before `run_bwrap()`. In other words, it only should remove (as cleanup) if those folders get created during bubblewraping. But, the `if` condition [here](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/sandbox/_sandboxbwrap.py#L210) seems to be doing the opposite and one can get errors like this:

```bash
[00:00:05][febd1eb1][build:rhel6-base/rhel6-build-base.bst] BUG     Build

    An unhandled exception occured:

    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/buildstream/_scheduler/job.py", line 320, in _child_action
        result = self._action_cb(element)
      File "/usr/local/lib/python3.6/dist-packages/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/usr/local/lib/python3.6/dist-packages/buildstream/element.py", line 1396, in _assemble
        collect = self.assemble(sandbox)
      File "/usr/local/lib/python3.6/dist-packages/buildstream/buildelement.py", line 186, in assemble
        self.__run_command(sandbox, cmd, command_name)
      File "/usr/local/lib/python3.6/dist-packages/buildstream/buildelement.py", line 242, in __run_command
        SandboxFlags.ROOT_READ_ONLY)
      File "/usr/local/lib/python3.6/dist-packages/buildstream/sandbox/_sandboxbwrap.py", line 231, in run
        os.rmdir(base_directory)
    OSError: [Errno 39] Directory not empty: '/root/.cache/buildstream/build/rhel6-base-rhel6-build-base-4gxmx90l/root/dev'
```

In our case, this happened while running `bst build` on an `kind: manual` element that depends on an import element (a base image with non-empty /dev/ folder).

**Solution**: According to clarification on IRC, the negation in the if clause should be removed and having an integration test to verify the behaviour should be added.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 1, 2018, 11:30

created branch [`379-_sandboxbwrap-py-post-bwrap-cleanup-shouldn-t-attempt-to-remove-preexisting-folders`](https://gitlab.com/BuildStream/buildstream/compare/master...379-_sandboxbwrap-py-post-bwrap-cleanup-shouldn-t-attempt-to-remove-preexisting-folders)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 1, 2018, 11:30

mentioned in merge request !478

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 1, 2018, 12:05

mentioned in merge request !479

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 1, 2018, 17:10

mentioned in merge request !480

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @gokcennurlu]](https://gitlab.com/gokcennurlu) on Jun 5, 2018, 17:23

mentioned in commit 75fe8037343223d3bb674f3dc16db70327e74609

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 5, 2018, 18:02

closed via merge request !480
