### ISSUE TITLE
AssertionError when caching artifact

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#383]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/383)
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on May 1, 2018, 02:51

This seems to be happening for every element in the build pipeline with bst version 1.1.3+4.g0916d81e

```
[--:--:--][????????][build:base/freedesktop-sdk-junction.bst:desktop/vulkan.bst] START   Caching artifact
[00:00:44][????????][build:base/freedesktop-sdk-junction.bst:desktop/vulkan.bst] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/job.py", line 320, in _child_action
        result = self._action_cb(element)
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_scheduler/buildqueue.py", line 34, in process
        element._assemble()
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/element.py", line 1497, in _assemble
        self.__artifacts.commit(self, assembledir, self.__get_cache_keys_for_commit())
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_artifactcache/ostreecache.py", line 135, in commit
        refs = [self.get_artifact_fullname(element, key) for key in keys]
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_artifactcache/ostreecache.py", line 135, in <listcomp>
        refs = [self.get_artifact_fullname(element, key) for key in keys]
      File "/home/mcatanzaro/.local/lib/python3.6/site-packages/buildstream/_artifactcache/artifactcache.py", line 152, in get_artifact_fullname
        assert key is not None
    AssertionError
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @TheRealMichaelCatanzaro]](https://gitlab.com/TheRealMichaelCatanzaro) on May 1, 2018, 19:02

I was able to work around this error by deleting my `~/.cache/buildstream`.  This was a bit difficult, because due to #135 it had reached 5,604,306 items, totalling 160.7 GB, and my attempts to delete it using `rm` failed due to [this kernel bug](https://bugzilla.redhat.com/show_bug.cgi?id=1573524). I was eventually able to delete it successfully using nautilus.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on May 3, 2018, 15:13

mentioned in commit eceb7c982295b402ab18730796dbb61112f72468

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on May 3, 2018, 15:14

mentioned in merge request !448

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on May 4, 2018, 07:28

closed via merge request !448
