### ISSUE TITLE
pylint version too permissive

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#427]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/427)
In GitLab by [[Gitlab user @dp0]](https://gitlab.com/dp0) on Jun 18, 2018, 13:22

## Summary

[//]: # (Summarize the bug encountered concisely)

When attempting to run tests locally, it appears that the version of pylint and pytest_pylint are not compatible. As a result, when these incompatible versions are used, tests are not able to run.

The change in question which causes this incompatibility can be found at https://github.com/PyCQA/pylint/commit/4210ef9b8c5d9e7b33ff0542683f18b8031193fa#diff-ade2cfcf3e840a993dbd465f517d91f5L1189 .

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

Perform a test locally. When using pytest_pylint 0.9.0 and pylint 2.0.0, the bug behavior is observed.

## What is the current bug behavior?

[//]: # (What actually happens)

An exception is thrown stating that pylint is being using incorrectly:

```
Linting files
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pytest-3.6.1-py3.6.egg/_pytest/main.py", line 178, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pytest-3.6.1-py3.6.egg/_pytest/main.py", line 214, in _main
INTERNALERROR>     config.hook.pytest_collection(session=session)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pytest-3.6.1-py3.6.egg/_pytest/main.py", line 224, in pytest_collection
INTERNALERROR>     return session.perform_collect()
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pytest-3.6.1-py3.6.egg/_pytest/main.py", line 432, in perform_collect
INTERNALERROR>     hook.pytest_collection_finish(session=self)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/__init__.py", line 617, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/__init__.py", line 222, in _hookexec
INTERNALERROR>     return self._inner_hookexec(hook, methods, kwargs)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/__init__.py", line 216, in <lambda>
INTERNALERROR>     firstresult=hook.spec_opts.get('firstresult'),
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/callers.py", line 201, in _multicall
INTERNALERROR>     return outcome.get_result()
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/callers.py", line 76, in get_result
INTERNALERROR>     raise ex[1].with_traceback(ex[2])
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pluggy-0.6.0-py3.6.egg/pluggy/callers.py", line 180, in _multicall
INTERNALERROR>     res = hook_impl.function(*args)
INTERNALERROR>   File "/home/dplayle/Code/kittyhawk/bst-build/buildstream/.eggs/pytest_pylint-0.9.0-py3.6.egg/pytest_pylint.py", line 161, in pytest_collection_finish
INTERNALERROR>     result = lint.Run(args_list, reporter=reporter, exit=False)
INTERNALERROR> TypeError: __init__() got an unexpected keyword argument 'exit'
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

The tests should run without an exception halting the testing process.

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

See above.

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

Restrict down the allowable versions of pylint.

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: issue present at 73b930024d164e076275868253f92a47593f2dd8

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @dp0]](https://gitlab.com/dp0) on Jun 18, 2018, 13:25

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @dp0]](https://gitlab.com/dp0) on Jun 18, 2018, 13:35

mentioned in merge request !503

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 18, 2018, 15:58

[[Gitlab user @knownexus]](https://gitlab.com/knownexus) also ran into this a few days ago.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @dp0]](https://gitlab.com/dp0) on Jun 20, 2018, 08:31

mentioned in commit 9b08bfe34d1127efd9dab73f60cbaca1457a7b41

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @dp0]](https://gitlab.com/dp0) on Jun 20, 2018, 08:33

mentioned in merge request !509

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @dp0]](https://gitlab.com/dp0) on Jun 20, 2018, 23:05

mentioned in commit 4f168b9b6a02216e2fae24d758ae6b778e545869

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 20, 2018, 23:44

closed via merge request !509

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 7, 2018, 16:09

mentioned in merge request !615
