### ISSUE TITLE
Stack trace shown if you accidentially `bst COMMAND <directory>`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#446]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/446)
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 10:00

## Summary
It's not uncommon to find elements with the same name (minus the file extension) as a subdirectory within the element path, especially when we're using [stack](https://buildstream.gitlab.io/buildstream/elements/stack.html) elements.

Executing a `bst COMMAND` on a directory will produce a stack trace.

## Steps to reproduce
If you execute the `bst show` command on a directory you'll receive something similar to the following:
```
 $ pwd
/home/jamesennis/autotools

 $ ls elements/
base  base.bst  hello.bst  importme.bst

 $ bst show base
[--:--:--][][] START   Loading pipeline
[--:--:--][][] BUG     [Errno 21] Is a directory: '/home/jamesennis/autotools/elements/base'

    Traceback (most recent call last):
      File "/home/jamesennis/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/jamesennis/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/jamesennis/buildstream/buildstream/_frontend/cli.py", line 543, in show
        except_targets=except_)
      File "/home/jamesennis/buildstream/buildstream/_stream.py", line 114, in load_selection
        fetch_subprojects=False)
      File "/home/jamesennis/buildstream/buildstream/_stream.py", line 814, in _load
        fetch_subprojects=fetch_subprojects)
      File "/home/jamesennis/buildstream/buildstream/_pipeline.py", line 113, in load
        meta_elements = self._loader.load(rewritable, None)
      File "/home/jamesennis/buildstream/buildstream/_loader/loader.py", line 114, in load
        loader._load_file(name, rewritable, ticker)
      File "/home/jamesennis/buildstream/buildstream/_loader/loader.py", line 218, in _load_file
        node = _yaml.load(fullpath, shortname=filename, copy_tree=rewritable)
      File "/home/jamesennis/buildstream/buildstream/_yaml.py", line 182, in load
        with open(filename) as f:
    IsADirectoryError: [Errno 21] Is a directory: '/home/jamesennis/autotools/elements/base'

```

## What is the expected correct behavior?
We should handle this exception better. Perhaps with a message along the lines of: "base is a directory, did you mean base.bst?".

This is similar to how the `git` command responds to typos:
```
 $ git feth
git: 'feth' is not a git command. See 'git --help'.

Did you mean this?
	fetch
```

Optional extra:
1. A [y/n] option, whereupon `y` we execute: `bst show base.bst`

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 10:09

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @franred]](https://gitlab.com/franred) on Jun 28, 2018, 15:27

mentioned in merge request !520

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @franred]](https://gitlab.com/franred) on Jun 28, 2018, 15:47

The patch catches the `IsADirectoryError` exception and return a nice error message.
I didn't add an option or suggestion because the directory/folder which the command will try to load could be anything, so adding a suggestion like "$directory_name" + ".bst" it might not make sense.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 17:33

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 18:46

mentioned in merge request !522

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 28, 2018, 18:54

I am not able to reproduce this error. For me, `click` itself is able to catch it, which is what I would've expected given that we set `dir_okay=False` here: https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/_frontend/cli.py#L491.

Here's what I get:

```
root[[Gitlab user @153b27714b58]](https://gitlab.com/153b27714b58):/src# bst show i-am-a-dir
Usage: bst show [OPTIONS] [ELEMENTS]...

Error: Invalid value for "elements": Path "i-am-a-dir" is a directory.
```

Does this only happen when the directories follow a specific naming pattern?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 18:57

Hi [[Gitlab user @cs]](https://gitlab.com/cs)\-shadow, I suspect that this is because you're not storing your elements in a sub-directory so have not set an `element-path` in the `project.conf` file.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 28, 2018, 19:08

Ah! You are right [[Gitlab user @jennis]](https://gitlab.com/jennis), that was it.

It makes sense now, we don't set `exists=True` so as far as click is concerned, it's a valid filename.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 29, 2018, 09:33

So I guess we should stick to one or the other to remain consistent.

I think that !522 outputs a more useful error message than what already exists, and it also performs a check to see if `<directory-name>.bst` exists in the element-path, which, in turn, prints an even more useful error message.

However, in order to remain consistent this way, I'll have to set the click argument, argument `dir_okay=True`, which may seem counter-intuitive to someone only reading that part of the code... What do we think?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 29, 2018, 09:46

mentioned in commit 48848f4e69201b78524443dc34a77cf872e0ad6c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlater]](https://gitlab.com/tlater) on Jun 29, 2018, 13:15

[[Gitlab user @jennis]](https://gitlab.com/jennis) I believe that we will need to remove the `type` entirely for consistency, and defer checking until we know where the file is.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 29, 2018, 17:37

closed via merge request !522

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @franred]](https://gitlab.com/franred) on Jul 16, 2018, 08:59

mentioned in commit 463698ec3203190aeac1f41ed3885f08e95bceae
