### ISSUE TITLE
Strack trace shown when trying to checkout an unbuilt element

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#447]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/447)
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 10:39

## Summary
`bst checkout <element> <directory>` on an unbuilt element will produce a stack trace.

## Steps to reproduce

```
 $ ls
elements  files  project.conf

 $ ls elements/
base  base.bst  hello.bst  importme.bst

 $ bst show hello.bst 
[--:--:--][][] START   Loading pipeline
[00:00:00][][] SUCCESS Loading pipeline
[--:--:--][][] START   Resolving pipeline
[00:00:00][][] SUCCESS Resolving pipeline
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state
      cached a352c93edfc55a41868b4f482758ad3ea1c21571532373542cd20b9135f0718d base/alpine.bst 
      cached a8eeb045115a4a71c18d09fe14b7b4fc3f3e838414a7d23d7c6d4c3027f28743 base.bst 
fetch needed 3f7f32d9cab049f2664b1299c07f0afdd16e8db5f8e9c6e4f6460439bad91013 hello.bst 

 $ bst checkout hello.bst ~/checkouts/hello
[--:--:--][][] START   Loading pipeline
[00:00:00][][] SUCCESS Loading pipeline
[--:--:--][][] START   Resolving pipeline
[00:00:00][][] SUCCESS Resolving pipeline
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state
[--:--:--][][] START   Staging dependencies
[--:--:--][][] BUG     autotools element at hello.bst [line 1 column 0]: Missing artifact 3f7f32d9

    Traceback (most recent call last):
      File "/home/jamesennis/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/jamesennis/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/jamesennis/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/jamesennis/buildstream/buildstream/_frontend/cli.py", line 642, in checkout
        hardlinks=hardlinks)
      File "/home/jamesennis/buildstream/buildstream/_stream.py", line 387, in checkout
        with target._prepare_sandbox(Scope.RUN, None, integrate=integrate) as sandbox:
      File "/usr/lib/python3.5/contextlib.py", line 59, in __enter__
        return next(self.gen)
      File "/home/jamesennis/buildstream/buildstream/element.py", line 1259, in _prepare_sandbox
        self.stage_dependency_artifacts(sandbox, scope)
      File "/home/jamesennis/buildstream/buildstream/element.py", line 710, in stage_dependency_artifacts
        update_mtimes=to_update)
      File "/home/jamesennis/buildstream/buildstream/element.py", line 613, in stage_artifact
        self.__assert_cached()
      File "/home/jamesennis/buildstream/buildstream/element.py", line 2025, in __assert_cached
        assert self._cached(), "{}: Missing artifact {}".format(self, self.__get_brief_display_key())
    AssertionError: autotools element at hello.bst [line 1 column 0]: Missing artifact 3f7f32d9

```

## What is the expected correct behavior?

We don't receive a stack trace. Instead, we output a message to inform the user that the element is unbuilt. 

Optional extra:
A [y/n] option that invokes `bst build` on the element if `y` is specified.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Jun 28, 2018, 11:19

I'm a bit confused by the title of this issue. While the title talks about opening a workspace, the stacktrace is for a `bst checkout`. Judging by what you wrote as the expected behavior, I'm guessing you meant "Strack trace shown when trying to checkout an unbuilt element". Is that right?

(Opening a workspace shouldn't require an element to be built in any case.)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 11:21

changed title from **Strack trace shown when trying to {-open a workspace for an-} unbuilt element** to **Strack trace shown when trying to {+checkout+} unbuilt element**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 11:21

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 11:22

[[Gitlab user @cs]](https://gitlab.com/cs)\-shadow, it turns out I was simultaneously working on a workspace elsewhere and I think I just went into autopilot... Thank you for spotting that!

The issue title and description have been updated

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Jun 28, 2018, 11:24

changed title from **Strack trace shown when trying to checkout unbuilt element** to **Strack trace shown when trying to checkout {+an +}unbuilt element**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Jul 30, 2018, 13:13

I can have a look at that.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Jul 30, 2018, 13:13

assigned to [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Jul 30, 2018, 13:47

mentioned in commit f542241345c51789f90b92d2f8d5c353cee26395

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Jul 30, 2018, 16:00

mentioned in commit c3bf577502c494b78f879d0da36dd4a5459b68e8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Jul 30, 2018, 16:23

mentioned in merge request !590

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 09:51

mentioned in commit acf0112e63c54fa9a0a71a0802bf6ac555a45d0b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 10:44

mentioned in commit f91799e6a85cad354a0b1dcbb95d274ea0883388

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 10:45

mentioned in commit c7657763c1e778bf74f9a7470400909a3f068a67

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 13:06

mentioned in commit 425f3b876ad2acb0964159dd6c19daec923f94ad

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 14:25

mentioned in commit a0ab6b56bc32123499bacc67084fff13db55701a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 16:16

mentioned in commit 00ddcbd765b25681452039d87b3928c4d61d99a3

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 1, 2018, 17:51

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:15

This is marked as a bug and it affects 1.2 (tested it manually). This should probably be backported.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:16

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 13, 2018, 15:32

mentioned in commit 62a128bc3b8552981b68227135578bdce6bd2a13

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 15:34

mentioned in merge request !653

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @martinblanchard]](https://gitlab.com/martinblanchard) on Aug 14, 2018, 08:12

mentioned in commit 3088aca2b869c791442cca57fe5feb810a09a070

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 14, 2018, 09:18

Backported by !653

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 14, 2018, 09:18

closed
