### ISSUE TITLE
ostree mirror fallback breaks assertion

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#538]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/538)
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 1, 2018, 16:37

## Summary

[//]: # (Summarize the bug encountered concisely)

When trying to fetch from ostree mirror when upstream is down, fetchqueue fails with a broken assertion.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

 - Have a setup with an upstream and a mirror ostree repositories.
 - Take down upstream.
 - Fetch.

## What is the current bug behavior?

[//]: # (What actually happens)

```
        Traceback (most recent call last):
          File "/home/valentin/repos/buildstream/buildstream/_scheduler/queues/queue.py", line 310, in _job_done
            processed = self.done(job, element, result, success)
          File "/home/valentin/repos/buildstream/buildstream/_scheduler/queues/fetchqueue.py", line 78, in done
            assert element._get_consistency() == Consistency.CACHED
        AssertionError
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

No error.

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.2

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 1, 2018, 16:39

mentioned in merge request !471

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 3, 2018, 09:20

marked this issue as related to #328

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @toscalix]](https://gitlab.com/toscalix) on Aug 6, 2018, 09:57

assigned to [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) on Aug 8, 2018, 14:54

I've had a look at this, and it seems the cause is:
1. `self.mirror` is based on `self.url`, not `self.original_url`, so when we create an instance of the source with a different alias, it creates an entirely different repository and fetches to that. Since it's a different directory, the main source can't find that fetched ref.
2. We configure the repo with remote "origin" that points to the upstream URL, and successive calls to _ostree.configure_remote() can't change it to a different URL (a remote is added if one doesn't exist, otherwise nothing happens).

I have a branch that fixes this (https://gitlab.com/BuildStream/buildstream/tree/jonathan/ostree-fix-no-upstream), but that implementation is probably suboptimal.
Ideally, instead of writing and changing "origin" all the time, we should add a new remote whose name is based on the URL (`utils.url_directory_name()` is useful here), and fetch from that remote (add a `remote` keyword arg to all calls to `_ostree.fetch()`)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 14, 2018, 14:34

mentioned in commit 36a4fad383101d5a77eed0cd2a36f0d35ab1b6d2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 14, 2018, 14:36

mentioned in merge request !658

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 14, 2018, 14:42

I have added !658 to solve the issue. It does what [[Gitlab user @jonathanmaw]](https://gitlab.com/jonathanmaw) proposed as ideal fix.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 15, 2018, 14:22

mentioned in commit c044537669a285cd9732248a56515cef4c8a5acb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 15, 2018, 14:24

mentioned in commit febfa626db0417bf02122b6be6afe246d0b7899f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 15, 2018, 14:25

mentioned in merge request !667

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 15, 2018, 16:37

mentioned in commit 0754810f4ee009225bbfa8a4550909f2c53b48f2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 16, 2018, 08:43

mentioned in commit c0431f15c3ee6910726e9b75abc784582a866d41

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 16, 2018, 09:54

closed via merge request !658

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 16, 2018, 09:54

mentioned in commit 04f836796d6d7f45a69ae607deebf3fb5b133611

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 16, 2018, 09:55

Reopening for the backport

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 16, 2018, 09:55

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 16, 2018, 12:18

mentioned in commit fd8443155611463b95cd32b5f02c1a08d229ba19

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 16, 2018, 14:37

mentioned in commit de73cc0b7076d5c6d60ea771a3ff388a7eb4153c

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 17, 2018, 07:22

This was backported with !667

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 17, 2018, 07:22

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 30, 2018, 07:38

mentioned in commit 9ea40e2cfeb39ff62ad88c5d1e684c23fa9051a8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 30, 2018, 07:39

mentioned in merge request !755

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 30, 2018, 07:40

mentioned in commit cd608e28cb7d44aaeeb97f1cf165d527dae0df46
