### ISSUE TITLE
Spurious error when running fedora job (the change in the MR was only on documentation)

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#559]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/559)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 7, 2018, 09:30

Job [#87321473](https://gitlab.com/BuildStream/buildstream/-/jobs/87321473) failed for 01ff01779c04877110ba4944b1286229dfe03267:

```
[00:00:00][fd215cab][build:import-dev.bst                ] SUCCESS test/import-dev/fd215cab-build.10679.log
Process Process-834:
Traceback (most recent call last):
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib64/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/builds/BuildStream/buildstream/dist/buildstream/buildstream/_scheduler/jobs/job.py", line 437, in _child_action
    self._queue.put(Envelope('child_data', self.child_process_data()))
  File "/builds/BuildStream/buildstream/dist/buildstream/buildstream/_scheduler/jobs/elementjob.py", line 113, in child_process_data
    cache_size = self._element._get_artifact_cache().calculate_cache_size()
  File "/builds/BuildStream/buildstream/dist/buildstream/buildstream/_artifactcache/cascache.py", line 476, in calculate_cache_size
    self.cache_size = utils._get_dir_size(self.casdir)
  File "/builds/BuildStream/buildstream/dist/buildstream/buildstream/utils.py", line 572, in _get_dir_size
    return get_size(path)
  File "/builds/BuildStream/buildstream/dist/buildstream/buildstream/utils.py", line 568, in get_size
    total += get_size(f.path)
  File "/builds/BuildStream/buildstream/dist/buildstream/buildstream/utils.py", line 565, in get_size
    total += f.stat(follow_symlinks=False).st_size
FileNotFoundError: [Errno 2] No such file or directory: '/builds/BuildStream/buildstream/dist/buildstream/tmp/test_push_after_pull0/cache/artifacts/cas/tmp/tmph4th_esx'
Coverage.py warning: No data was collected. (no-data-collected)
Coverage.py warning: No data was collected. (no-data-collected)

BUG: Message handling out of sync, unable to retrieve failure message for element import element at import-bin.bst [line 1 column 0]
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 7, 2018, 09:31

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 7, 2018, 09:42

I wonder if this is related to #503. The error shown is very similar, i.e. something missing from the cache.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 7, 2018, 09:55

marked this issue as a duplicate of #420

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 7, 2018, 09:55

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @phildawson]](https://gitlab.com/phildawson) on Aug 7, 2018, 10:24

marked this issue as a duplicate of #520
