### ISSUE TITLE
ruamel.yaml automatically updates to 0.15.52 and breaks BuildStream

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#571]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/571)
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 9, 2018, 18:33

## Summary

We don't pin a version of ruamel in our `setup.py` and the newly-released 0.15.52 version breaks BuildStream.

## Steps to reproduce

On a currently installed BuildStream instance, run `pip3 install --user -e .` as per the current install instructions, then invoke `bst` (Just `bst` on the command line on its own is enough).

## What is the current bug behavior?

Line present in pip upgrade log:

```
Collecting ruamel.yaml (from BuildStream==1.3.0+38.g8c9fd9e4)
  Using cached https://files.pythonhosted.org/packages/07/0f/c57e0f402f8f0b780d0cf3b5814489c30a531b7fdf21f9180a90320bc347/ruamel.yaml-0.15.52-cp36-cp36m-manylinux1_x86_64.whl
```

Running `bst` will produce:

```
Error loading user configuration: YAML file has content of type 'CommentedMap' instead of expected type 'dict': /home/jimmacarthur/bs/buildstream/buildstream/data/userconfig.yaml
```

## What is the expected correct behavior?

`bst` should work as it previously did.

## Possible fixes

Pin ruamel version number in `setup.py`, like this:

```
-          'ruamel.yaml',
+          'ruamel.yaml <= 0.15',
```

## Other relevant information

Pinning is the current advice given by ruamel for production systems:

```
Starting with version 0.15.0 the way YAML files are loaded and dumped is changing. See the API doc for details. Currently existing functionality will throw a warning before being changed/removed. For production systems you should pin the version being used with ``ruamel.yaml<=0.15``.
```

* BuildStream version affected: /milestone %BuildStream_v1.3

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 9, 2018, 18:37

mentioned in merge request !630

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 9, 2018, 19:02

This looks good, but we need to keep the version shipped in the docker images in sync or users will not be able to use buildstream anymore

I've opened https://gitlab.com/BuildStream/buildstream-docker-images/merge_requests/56 to try to fix this

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 9, 2018, 21:05

Thanks [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) !

Can you please merge the patch from !630 on `bst-1.2` also ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 9, 2018, 22:32

[[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) Not until Monday; I'm happy to do so if no-one has done it by then.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 9, 2018, 23:22

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 10, 2018, 05:10

[[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur), no worries, I've created !631 for this.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Aug 10, 2018, 14:47

This completely breaks here, presumably that version of `ruamel.yaml` is too old for Python 3.7.

```
Collecting ruamel.yaml<=0.15 (from BuildStream==1.3.0+193.ga602365c)
  Downloading https://files.pythonhosted.org/packages/10/aa/f31c8a858e23fe5b14c59e6a03ae80b4cb76353c184df48a582a55eb2674/ruamel.yaml-0.15.0.tar.gz (247kB)
    100% |████████████████████████████████| 256kB 3.3MB/s 
    Complete output from command python setup.py egg_info:
    /tmp/tmp_ruamel_jjmaijjh/test_ruamel_yaml.c: In function ‘main’:
    /tmp/tmp_ruamel_jjmaijjh/test_ruamel_yaml.c:6:8: warning: ‘parser’ is used uninitialized in this function [-Wuninitialized]
     parser = parser;  /* prevent warning */
     ~~~~~~~^~~~~~~~
    Warning: 'keywords' should be a list, got type 'NoneType'
    sys.argv ['-c', 'egg_info', '--egg-base', 'pip-egg-info']
    test compiling test_ruamel_yaml
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-g35u5n86/ruamel.yaml/setup.py", line 858, in <module>
        main()
      File "/tmp/pip-install-g35u5n86/ruamel.yaml/setup.py", line 847, in main
        setup(**kw)
      File "/usr/lib/python3.7/site-packages/setuptools/__init__.py", line 131, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 108, in setup
        _setup_distribution = dist = klass(attrs)
      File "/usr/lib/python3.7/site-packages/setuptools/dist.py", line 370, in __init__
        k: v for k, v in attrs.items()
      File "/usr/lib/python3.7/distutils/dist.py", line 267, in __init__
        getattr(self.metadata, "set_" + key)(val)
      File "/usr/lib/python3.7/distutils/dist.py", line 1203, in set_keywords
        self.keywords = _ensure_list(value, 'keywords')
      File "/usr/lib/python3.7/distutils/dist.py", line 40, in _ensure_list
        value = list(value)
    TypeError: 'NoneType' object is not iterable
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-g35u5n86/ruamel.yaml/
```

Can we change it to `ruamel.yaml < 0.15.52` instead? The test suite passes fine here with 0.15.51.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 10, 2018, 14:57

Yeah, it breaks here too

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 10, 2018, 15:41

mentioned in merge request buildstream-docker-images!56

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 11:12

mentioned in commit 4c02e3dd745db32357b0a186d4c7769e30726372

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 11:18

mentioned in merge request !646

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 11:29

mentioned in commit 465c165ddc02222353b6d3764c0af4fdf92b37e8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 11:36

mentioned in commit bda4e935edc234ce277ac7a2b7137b50c755938a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 11:38

mentioned in merge request !647

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:20

mentioned in commit be6d64fe22b84bdd930bad7dff6ef2d4164f70f6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:22

mentioned in commit eb90e0c262581d5c8548911bc3a35a3e11dbbfb5

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:22

mentioned in commit fcc28407612ba2d5575f84b8f2dca6c0eb5b8d7b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:39

mentioned in commit 6e759d8aa41f60e9a0dfe409e61e2c32a7a1d386

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 13:39

mentioned in commit f53e12c2d337446d112f53652c6bba9ce8c2f6c8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 14:36

closed via merge request !646

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 13, 2018, 14:36

mentioned in commit 56f2b2e4f733f9c604c072a60bc53cac749f3f5e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 23, 2018, 11:37

mentioned in commit c1b1076afeefcc7751505985e703761d4aef4535
