### ISSUE TITLE
Unhandled exception when build reports "bug"

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#577]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/577)
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Aug 14, 2018, 21:45

## Summary

[//]: # (Summarize the bug encountered concisely)

When building the freedesktop sdk i encountered a stack trace for sdk-integration.bst

## Steps to reproduce

Build freedesktop-sdk using the Makefile provided in the git repo using buildstream 1.1.5

## What is the current bug behavior?

A stack trace occurs related the cache

## What is the expected correct behavior?

No stack trace to occur

## Relevant logs and/or screenshots

```
[00:00:01][f98e9d70][build:sdk-integration.bst           ] BUG     Build

    An unhandled exception occured:

    Traceback (most recent call last):
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_artifactcache/cascache.py", line 95, in extract
        os.rename(checkoutdir, dest)
    OSError: [Errno 39] Directory not empty: '/home/adds68/.cache/buildstream/artifacts/extract/tmpghdzdw4u/freedesktop-sdk/base-iso-codes/f1862ecacbc713a82afc5a789b82c3015a94f49cc03f74095b47dfff90e520b6' -> '/home/adds68/.cache/buildstream/artifacts/extract/freedesktop-sdk/base-iso-codes/1ef40f5f758cacb7454fe65f3c292ccdfe2ac5af1efd256dd6fb249abb141db7'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 398, in _child_action
        result = self.child_process()
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_scheduler/queues/buildqueue.py", line 34, in process
        element._assemble()
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/element.py", line 1463, in _assemble
        collect = self.assemble(sandbox)
      File "/home/adds68/git-repos/freedesktop-sdk/plugins/elements/collect-integration.py", line 47, in assemble
        bstdata = dependency.get_public_data('bst')
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/element.py", line 825, in get_public_data
        self.__load_public_data()
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/element.py", line 2476, in __load_public_data
        artifact_base, _ = self.__extract()
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/element.py", line 2343, in __extract
        return (self.__artifacts.extract(self, key), key)
      File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_artifactcache/cascache.py", line 102, in extract
        if e.errno not in [os.errno.ENOTEMPTY, os.errno.EEXIST]:
    AttributeError: module 'os' has no attribute 'errno'
```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Aug 14, 2018, 22:34

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Aug 15, 2018, 10:34

changed title from **Unhandled exception w{-ith build bug-}** to **Unhandled exception w{+hen build reports "bug"+}**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Aug 15, 2018, 10:35

It seems hitting "r"(retry) multiple times then keeps the build going

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 10:53

assigned to [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 11:04

mentioned in commit 4aa74acae1b21562a78dd138962a31109a0b49b9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 11:05

mentioned in commit 7a38957d6c4346d646c844eef6d318ee4a91db35

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 11:06

mentioned in merge request !674

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 11:08

mentioned in commit 2911879a65aa082a63d95fef2ede82ba835abf5a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 11:10

mentioned in merge request !675

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 14:55

mentioned in commit b62c361c427a20bc5c2e2811cd2629b012cbe5df

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 14:55

mentioned in commit c31b2500645c083a1eab6ad12b80d00606bc4908

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 16:00

closed via merge request !674

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 16:00

mentioned in commit 1e3e2a936d706509d4f75fa7181c9081ad6cfa40

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 16:00

mentioned in commit f15ff4562d5ce3fbebdedde5d28e0436d53a6887

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 17:14

marked this issue as related to #590

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 16, 2018, 17:20

mentioned in commit 3200093e9b4377ae809ecdd1928d1dc34bc0c962
