### ISSUE TITLE
An unhandled exception occured when building: OSError: [Errno 39] Directory not empty

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#590]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/590)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Aug 16, 2018, 17:08

## Summary
I'm getting the below stack trace every time I try to build my system

## Relevant logs and/or screenshots

```
[00:00:03][66e00599][build:bootstrap-junction.bst:file-stage1.bst] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/_artifactcache/cascache.py", line 95, in extract
        os.rename(checkoutdir, dest)
    OSError: [Errno 39] Directory not empty: '/home/jjardon/.cache/buildstream/artifacts/extract/tmpx3f0n0yt/freedesktop-sdk-bootstrap/dependencies-base-sdk-image/d1f300b6e2b55e3b4db358e673330295e61742321c394c4e4945e329387ea44a' -> '/home/jjardon/.cache/buildstream/artifacts/extract/freedesktop-sdk-bootstrap/dependencies-base-sdk-image/77bddd9d7be3dd3437072b4a75463c3212817358a1e9fee9899703c5164f6a54'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 398, in _child_action
        result = self.child_process()
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/_scheduler/queues/buildqueue.py", line 34, in process
        element._assemble()
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/element.py", line 1479, in _assemble
        self.stage(sandbox)
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/buildelement.py", line 165, in stage
        self.stage_dependency_artifacts(sandbox, Scope.BUILD)
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/element.py", line 723, in stage_dependency_artifacts
        update_mtimes=to_update)
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/element.py", line 630, in stage_artifact
        artifact_base, _ = self.__extract()
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/element.py", line 2350, in __extract
        return (self.__artifacts.extract(self, key), key)
      File "/home/jjardon/.local/lib/python3.7/site-packages/buildstream/_artifactcache/cascache.py", line 102, in extract
        if e.errno not in [os.errno.ENOTEMPTY, os.errno.EEXIST]:
    AttributeError: module 'os' has no attribute 'errno'

```

## Other relevant information

* BuildStream version affected: latest commit from bst-1.2, sha 87960822f8f66f4c31a89d834d80929add13887d

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 17:14

marked this issue as related to #577

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 16, 2018, 17:14

closed
