### ISSUE TITLE
Error after apparently successful build

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#593]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/593)
In GitLab by [[Gitlab user @tlsa]](https://gitlab.com/tlsa) on Aug 17, 2018, 14:28

## Summary

Weird error after apparently successful build.

## Steps to reproduce

I ran this command `bst -o target_arch aarch64 build linux.bst` with buildstream 1.1.5, on a repo that uses the freedesktop sdk as a junction.  It fetched most of the artifacts from freedesktop sdk's artifact cache, and built the linux.bst.  Build running on a aarch64 host, targeting aarch64.

## What is the current bug behavior?

See log below.

## What is the expected correct behavior?

No error at the end.

## Relevant logs and/or screenshots

```
[--:--:--][32244031][build:linux.bst                     ] STATUS  Running strip-commands

    find "/buildstream-install" -type f \
      '(' -perm -111 -o -name '*.so*' \
          -o -name '*.cmxs' -o -name '*.node' ')' \
      -exec sh -ec \
      'read -n4 hdr <"$1" # check for elf header
       if [ "$hdr" != "$(printf \\x7fELF)" ]; then
           exit 0
       fi
       debugfile="/buildstream-install/usr/lib/debug/$(basename "$1")"
       mkdir -p "$(dirname "$debugfile")"
       objcopy --only-keep-debug --compress-debug-sections "$1" "$debugfile"
       chmod 644 "$debugfile"
       strip --remove-section=.comment --remove-section=.note --strip-unneeded "$1"
       objcopy --add-gnu-debuglink "$debugfile" "$1"' - {} ';'

[00:00:00][32244031][build:linux.bst                     ] SUCCESS Running strip-commands
[--:--:--][32244031][build:linux.bst                     ] START   Caching artifact
[00:00:09][32244031][build:linux.bst                     ] SUCCESS Caching artifact
[00:59:24][32244031][build:linux.bst                     ] SUCCESS vdc/linux/32244031-build.14287.log
[01:08:45][][] SUCCESS Build

Pipeline Summary
  Total:       162
  Session:     162
  Pull Queue:  processed 116, skipped 1,   failed 0 
  Fetch Queue: processed 0,   skipped 117, failed 0 
  Build Queue: processed 1,   skipped 116, failed 0 
Error in atexit._run_exitfuncs:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/util.py", line 288, in _exit_function
    _run_finalizers(0)
  File "/usr/lib/python3.5/multiprocessing/util.py", line 248, in _run_finalizers
    items = [x for x in list(_finalizer_registry.items()) if f(x)]
RuntimeError: dictionary changed size during iteration
```
## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: 1.1.5

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tlsa]](https://gitlab.com/tlsa) on Aug 17, 2018, 14:30

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 17, 2018, 16:28

marked this issue as related to #20

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 17, 2018, 16:29

This already has been reported. Closing dup.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tacgomes]](https://gitlab.com/tacgomes) on Aug 17, 2018, 16:29

closed
