### ISSUE TITLE
Git url without alias causes ValueError

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#597]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/597)
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 21, 2018, 10:58

## Summary

[//]: # (Summarize the bug encountered concisely)

Getting a traceback when tracking element without alias for git source.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

Have a git source with `url: files/repo`

`bst track <element>`

## What is the current bug behavior?

[//]: # (What actually happens)

Traceback

## What is the expected correct behavior?

[//]: # (What you should see instead)

Failure with a suggested fix

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
    Traceback (most recent call last):
      File "/home/joshsmith/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/joshsmith/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/joshsmith/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/joshsmith/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/joshsmith/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/joshsmith/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/joshsmith/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/joshsmith/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/joshsmith/buildstream/buildstream/_frontend/cli.py", line 420, in track
        cross_junctions=cross_junctions)
      File "/home/joshsmith/buildstream/buildstream/_stream.py", line 279, in track
        fetch_subprojects=True)
      File "/home/joshsmith/buildstream/buildstream/_stream.py", line 872, in _load
        fetch_subprojects=fetch_subprojects)
      File "/home/joshsmith/buildstream/buildstream/_pipeline.py", line 111, in load
        fetch_subprojects=fetch_subprojects)
      File "/home/joshsmith/buildstream/buildstream/_project.py", line 324, in load_elements
        for meta in meta_elements
      File "/home/joshsmith/buildstream/buildstream/_project.py", line 324, in <listcomp>
        for meta in meta_elements
      File "/home/joshsmith/buildstream/buildstream/element.py", line 883, in _new_from_meta
        first_pass=meta.first_pass)
      File "/home/joshsmith/buildstream/buildstream/_project.py", line 252, in create_source
        return self.config.source_factory.create(self._context, self, meta)
      File "/home/joshsmith/buildstream/buildstream/_sourcefactory.py", line 61, in create
        source = source_type(context, project, meta)
      File "/home/joshsmith/buildstream/buildstream/source.py", line 295, in __init__
        self.configure(self.__config)
      File "/home/joshsmith/buildstream/buildstream/plugins/sources/git.py", line 310, in configure
        self.mirror = GitMirror(self, '', self.original_url, ref)
      File "/home/joshsmith/buildstream/buildstream/plugins/sources/git.py", line 111, in __init__
        self.mark_download_url(url)
      File "/home/joshsmith/buildstream/buildstream/source.py", line 224, in mark_download_url
        alias, _ = url.split(utils._ALIAS_SEPARATOR, 1)
    ValueError: not enough values to unpack (expected 2, got 1)
```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 21, 2018, 14:41

mentioned in commit 6a97640bc3364e70746987bd51d6dcc7bb49ef11

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 21, 2018, 15:44

mentioned in commit 6a4a6479e3ec54593722f6a18c169cb9a92a4e38

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 22, 2018, 11:41

mentioned in commit 2a9599725fbc5a24a1c3c19dd527b5c68be7fd88

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 22, 2018, 11:45

mentioned in merge request !700

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 28, 2018, 15:46

mentioned in commit 6c7ec7b543dedbfbe46c3d13f60ce8052527279e

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 10:43

mentioned in commit e1536545f07f9dd5a420dbbb06622cf39a900788

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 11:15

mentioned in commit e15d98f041b1da409a726b140cb80a2e62079ebc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 13:38

mentioned in commit 42ad937d7c47a685cb6f7a58f81d82d66cf2a157

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 13:57

mentioned in commit 4a823cd450dae5edf73b9088c572f4427875d34b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 14:02

mentioned in commit 582e0c05be81cedb174704e509c87391036c4841

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 29, 2018, 14:03

closed via merge request !700

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 29, 2018, 14:04

mentioned in commit aa3a33b3baf6f0151a35ddd42ae899bd251cd660

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 29, 2018, 14:27

Reopening this for the required backport.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Aug 29, 2018, 14:27

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 15:08

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 15:11

Closed for backport being merged !751

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 15:23

marked this issue as related to #612

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Aug 29, 2018, 15:30

marked this issue as related to #613
