### ISSUE TITLE
PermissionError when calling `vdirectory.import_files()`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#601]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/601)
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 22, 2018, 12:00

## Overview

Using master, my build instantly fails when trying to import the base image (a tarball) due to a permissions error when calling `vdirectory.import_files()` in [element.py](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/element.py#L1379)

## Stack trace
Here is the stack trace I received: 
```
[--:--:--] START   bootstrap.bst: Staging sources
[--:--:--] BUG     bootstrap.bst: Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/jennis/buildstream/buildstream/_scheduler/jobs/job.py", line 398, in _child_action
        result = self.child_process()
      File "/home/jennis/buildstream/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/jennis/buildstream/buildstream/_scheduler/queues/buildqueue.py", line 70, in process
        element._assemble()
      File "/home/jennis/buildstream/buildstream/element.py", line 1516, in _assemble
        collect = self.assemble(sandbox)
      File "/home/jennis/buildstream/buildstream/plugins/elements/import.py", line 71, in assemble
        self._stage_sources_in_sandbox(sandbox, 'input', mount_workspaces=False)
      File "/home/jennis/buildstream/buildstream/element.py", line 1346, in _stage_sources_in_sandbox
        self._stage_sources_at(host_vdirectory, mount_workspaces=mount_workspaces)
      File "/home/jennis/buildstream/buildstream/element.py", line 1379, in _stage_sources_at
        vdirectory.import_files(temp_staging_directory)
      File "/usr/lib/python3.5/tempfile.py", line 947, in __exit__
        self.cleanup()
      File "/usr/lib/python3.5/tempfile.py", line 951, in cleanup
        _rmtree(self.name)
      File "/usr/lib/python3.5/shutil.py", line 474, in rmtree
        _rmtree_safe_fd(fd, path, onerror)
      File "/usr/lib/python3.5/shutil.py", line 412, in _rmtree_safe_fd
        _rmtree_safe_fd(dirfd, fullname, onerror)
      File "/usr/lib/python3.5/shutil.py", line 432, in _rmtree_safe_fd
        onerror(os.unlink, fullname, sys.exc_info())
      File "/usr/lib/python3.5/shutil.py", line 430, in _rmtree_safe_fd
        os.unlink(name, dir_fd=topfd)
    PermissionError: [Errno 13] Permission denied: 'ldconfig'
```

## What's going on
This is what we're doing:
1. Staging sources in a temporary directory ([here](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/element.py#L1377))
2. Then importing them from the temporary directory into a virtual directory ([here](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/element.py#L1379))
3. This `import_files()` call eventually calls [os.unlink()](https://docs.python.org/3.6/library/os.html#os.unlink), which is semantically identical to [os.remove()](https://docs.python.org/3.6/library/os.html#os.remove).
4. `import_files()` calls `copy_files()` in utils ([here](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/storage/_filebaseddirectory.py#L118)).
5. `copy_files()` calls [`_process_list()`](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/utils.py#L757) which is used to copying/moving/linking file lists.

So, it looks like when we copy files from the temp dir, we're also deleting them. And we simply do not have the permission to delete these files.

I'm not sure what the best solution is for this, because my guess is that at *some* point, files in the tmp dir, or the tmp dir itself will need to be deleted, and we won't have the permission to do this.

Another thought is that it appears that `_process_list()` handles file permissions by setting them at the end, perhaps we're invoking this twice?

Any thoughts?

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 22, 2018, 12:22

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 22, 2018, 13:01

marked this issue as related to #521

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 22, 2018, 14:16

I don't think that's quite what's happening. import_files() shouldn't unlink or otherwise delete anything, either in the file-backed version or the CAS-backed one. The most it can do is hardlink one file to another.

I think it looks like `import_files` is calling unlink because the import_files line is where temp_staging_directory goes out of scope so the cleanup procedure for it is being called. It's tempfile calling unlink, rather than import_files.

I think `_process_files` is a likely suspect - I'll continue investigating. I'd like to try and reproduce it - is 'bootstap.bst' the one from Freedesktop-SDK?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 22, 2018, 17:16

This is a real puzzler. `import_files`, as called by `_stage_sources_at`, doesn't supply a `can_link` argument so everything should be copied, not linked. I think it's the simple fact of staging into a temp directory, rather than anything import_files or stage() does, that causes this. It's very difficult to track down without having the tar file you have.

I've been able to make a Debian rootfs which has all files set to root ownership, without devices. This works in an import element with a file:/// url with no problems.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 23, 2018, 09:56

[[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) upon inspection of the tarball, it seems that some of these files and directories are read only, _sbin/ldconfig_ included. This seems to be the cause of the problem, which I assume arises when we try to tear down the tmp directory

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 23, 2018, 11:47

Found the problem; it's tars which have directories with less than 'rwx' permissions for the owner, e.g.:

`dr-xr-xr-x 0/0       0 2017-07-10 14:21 sbin/`

This is unusual in rootfs tarballs hence not spotting it before, but we definitely should support it.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) on Aug 23, 2018, 13:53

mentioned in merge request !713

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 30, 2018, 13:27

Closed by !713

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jennis]](https://gitlab.com/jennis) on Aug 30, 2018, 13:27

closed
