### ISSUE TITLE
Non strict build causes "Missing artifact"

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#607]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/607)
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Aug 24, 2018, 13:28

## Summary

[//]: # (Summarize the bug encountered concisely)

There is a regression in master not present in 1.2. When build non strict mode we get "Missing artifact" errors.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

You need three elements:
 - `a.bst`
 - `b.bst` build depends `a.bst` with a plugin *without* `BST_STRICT_REBUILD` so *not* `compose`
 - `c.bst` build depends `b.bst` with a plugin *without* `BST_STRICT_REBUILD` so *not* `compose`

1. Build `b.bst`.
1. Modify `a.bst` to change its key.
1. Build non-strict `c.bst`

## What is the current bug behavior?

[//]: # (What actually happens)

```
    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/element.py", line 1511, in _assemble
        self.stage(sandbox)
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/buildelement.py", line 165, in stage
        self.stage_dependency_artifacts(sandbox, Scope.BUILD)
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/element.py", line 699, in stage_dependency_artifacts
        update_mtimes=to_update)
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/element.py", line 609, in stage_artifact
        self.__assert_cached()
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/element.py", line 2069, in __assert_cached
        self, self._get_brief_display_key())
    AssertionError: manual element at a.bst [line 1 column 0]: Missing artifact 4c27cb74
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/_scheduler/jobs/job.py", line 398, in _child_action
        result = self.child_process()
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/_scheduler/queues/buildqueue.py", line 70, in process
        element._assemble()
      File "/home/valentin/.local/lib/python3.6/site-packages/BuildStream-1.3.0+313.g8216ff8d-py3.6.egg/buildstream/element.py", line 1591, in _assemble
        build_result_dict = {"success": self.__build_result[0], "description": self.__build_result[1]}
    TypeError: 'NoneType' object is not subscriptable
```

## What is the expected correct behavior?

[//]: # (What you should see instead)

It should build without error

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: master /milestone %"BuildStream\_v1.4" 

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 14:16

assigned to [[Gitlab user @juergbi]](https://gitlab.com/juergbi)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 14:54

I've seen this as well and can reproduce this. `c.bst` can also be `compose`/`BST_STRICT_REBUILD`, though (`b.bst` indeed must not).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 15:00

mentioned in commit 86ea1173a485024a3f241263814632a70c43b867

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 15:00

mentioned in commit da7e038bb2b256b7e880f9fcd86f6bf1403cb986

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 15:01

mentioned in merge request !822

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 17:02

closed via merge request !822

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Sep 24, 2018, 17:02

mentioned in commit a76339deb7303901e8602635523b1776b4a1bb0c
