### ISSUE TITLE
bug in build after failed build with workspace's

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#634]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/634)
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 7, 2018, 14:36

## Summary

bug in build after failed build with workspace's

## Steps to reproduce

As follows:
* set up a workspace for a element
* build element
* (element fails at configure stage)
* try to build element again
* bst craches with a missing artifact bug report

## What is the current bug behavior?

Bst thinks there should be a cached artifact even though the last build failed
But only for workspaces.

## What is the expected correct behavior?

bst should try to rebuild

## Relevant logs and/or screenshots

```
 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  bst workspace reset hello.bst
This will remove all your changes, are you sure? [y/N]: y
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[00:00:00][][] SUCCESS Resolving elements
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state
[--:--:--][????????][ main:hello.bst                     ] START   Removing workspace directory /home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3/hlws
[00:00:00][????????][ main:hello.bst                     ] SUCCESS Removing workspace directory /home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3/hlws
[--:--:--][????????][ main:hello.bst                     ] START   Staging sources to /home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3/hlws
[--:--:--][        ][ main:hello.bst-0                   ] START   Staging local files at files/hello
[00:00:00][        ][ main:hello.bst-0                   ] SUCCESS Staging local files at files/hello
[00:00:00][????????][ main:hello.bst                     ] SUCCESS Staging sources to /home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3/hlws
[--:--:--][][] INFO    Reset workspace for hello.bst at: /home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3/hlws
 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  bst build hello.bst
[--:--:--][][] START   Build
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[00:00:00][][] SUCCESS Resolving elements
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state
[--:--:--][][] START   Checking sources
[00:00:00][][] SUCCESS Checking sources

BuildStream Version 1.3.0+428.gc878ebe9.dirty
  Session Start: Friday, 07-09-2018 at 14:23:14
  Project:       outOfSourceBuilds2 (/home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3)
  Targets:       hello.bst

User Configuration
  Configuration File:      Default Configuration
  Log Files:               /home/will/.cache/buildstream/logs
  Source Mirrors:          /home/will/.cache/buildstream/sources
  Build Area:              /home/will/.cache/buildstream/build
  Artifact Cache:          /home/will/.cache/buildstream/artifacts
  Strict Build Plan:       Yes
  Maximum Fetch Tasks:     10
  Maximum Build Tasks:     4
  Maximum Push Tasks:      4
  Maximum Network Retries: 2

Pipeline
      cached 7279b9cc8a468bcc07336479b67b02b8c142b1cfd34d8922c05ff9917942eafc base/alpine.bst 
      cached 3f746703110816af8c43534f3e76dbe61dd5661a9bef0cb1960bff4f53881186 base.bst 
   buildable ???????????????????????????????????????????????????????????????? hello.bst Workspace: /home/will/projects/buildstream/buildstream/doc/examples/out-of-source-builds3/hlws
===============================================================================
[--:--:--][????????][build:hello.bst                     ] START   outOfSourceBuilds2/hello/????????-build.7750.log
[--:--:--][????????][build:hello.bst                     ] START   Staging dependencies
[00:00:01][????????][build:hello.bst                     ] SUCCESS Staging dependencies
[--:--:--][????????][build:hello.bst                     ] START   Integrating sandbox
[00:00:00][????????][build:hello.bst                     ] SUCCESS Integrating sandbox
============================================================================= 00:00:01 outOfSourceBuilds2 (1/3) =============================================================================
                                                                                (Fetched:0 1 0)→ (Built:0 0 0)                                                                                
                                                                                   ~~~~~ Active Tasks ~~~~~                                                                                   
[00:00:01][Build:hello.bst]
[--:--:--][????????][build:hello.bst                     ] START   Staging sources
[00:00:00][????????][build:hello.bst                     ] SUCCESS Staging sources
[--:--:--][????????][build:hello.bst                     ] START   Running configure-commands
[--:--:--][????????][build:hello.bst                     ] STATUS  Running configure-commands

    cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
    -DCMAKE_INSTALL_LIBDIR=lib

============================================================================= 00:00:01 outOfSourceBuilds2 (1/3) =============================================================================
[00:00:00][????????][build:hello.bst                     ] FAILURE Running configure-commands
============================================================================= 00:00:02 outOfSourceBuilds2 (1/3) =============================================================================
                                                                                (Fetched:0 1 0)→ (Built:0 0 0)                                                                                
                                                                                   ~~~~~ Active Tasks ~~~~~                                                                                   
[00:00:01][Build:hello.bst]
subdirectory_spec ['outOfSourceBuilds2', 'hello.bst']
subdirectory_spec ['hello.bst']
subdirectory_spec []
subdirectory_spec ['buildstream-install']
subdirectory_spec []
[--:--:--][????????][build:hello.bst                     ] START   Caching artifact
[00:00:00][????????][build:hello.bst                     ] SUCCESS Caching artifact
[00:00:01][????????][build:hello.bst                     ] FAILURE Command 'cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
-DCMAKE_INSTALL_LIBDIR=lib' failed with exitcode 1

    Sandbox directory: /home/will/.cache/buildstream/build/hello-csohbp7s

    Printing the last 20 lines from log file:
    /home/will/.cache/buildstream/logs/outOfSourceBuilds2/hello/????????-build.7750.log
    ======================================================================
    [00:00:01] SUCCESS base/alpine.bst: Staging base/alpine.bst/7279b9cc
    [--:--:--] START   base.bst: Staging base.bst/3f746703
    [00:00:00] SUCCESS base.bst: Staging base.bst/3f746703
    [00:00:01] SUCCESS hello.bst: Staging dependencies
    [--:--:--] START   hello.bst: Integrating sandbox
    [00:00:00] SUCCESS hello.bst: Integrating sandbox
    [--:--:--] START   hello.bst: Staging sources
    [00:00:00] SUCCESS hello.bst: Staging sources
    [--:--:--] START   hello.bst: Running configure-commands
    [--:--:--] STATUS  hello.bst: Running configure-commands

        cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
        -DCMAKE_INSTALL_LIBDIR=lib
    CMake Error: The source directory "/buildstream/outOfSourceBuilds2/hello.bst" does not appear to contain CMakeLists.txt.
    Specify --help for usage, or press the help button on the CMake GUI.
    [00:00:00] FAILURE hello.bst: Running configure-commands
    [--:--:--] START   hello.bst: Caching artifact
    [00:00:00] SUCCESS hello.bst: Caching artifact
    [00:00:01] FAILURE hello.bst: Command 'cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
    -DCMAKE_INSTALL_LIBDIR=lib' failed with exitcode 1
    ======================================================================


Build failure on element: hello.bst

Choose one of the following options:
  (c)ontinue  - Continue queueing jobs as much as possible
  (q)uit      - Exit after all ongoing jobs complete
  (t)erminate - Terminate any ongoing jobs and exit
  (r)etry     - Retry this job
  (l)og       - View the full log file
  (s)hell     - Drop into a shell in the failed build sandbox

Pressing ^C will terminate jobs and exit


Choice: [continue]: t

Terminating all jobs

[00:00:14][][] FAILURE Build


Failure Summary
  hello.bst:
    [00:00:00][????????][build:hello.bst                     ] FAILURE Running configure-commands
    [00:00:01][????????][build:hello.bst                     ] FAILURE Command 'cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
    -DCMAKE_INSTALL_LIBDIR=lib' failed with exitcode 1

        Sandbox directory: /home/will/.cache/buildstream/build/hello-csohbp7s

        Printing the last 20 lines from log file:
        /home/will/.cache/buildstream/logs/outOfSourceBuilds2/hello/????????-build.7750.log
        ======================================================================
        [00:00:01] SUCCESS base/alpine.bst: Staging base/alpine.bst/7279b9cc
        [--:--:--] START   base.bst: Staging base.bst/3f746703
        [00:00:00] SUCCESS base.bst: Staging base.bst/3f746703
        [00:00:01] SUCCESS hello.bst: Staging dependencies
        [--:--:--] START   hello.bst: Integrating sandbox
        [00:00:00] SUCCESS hello.bst: Integrating sandbox
        [--:--:--] START   hello.bst: Staging sources
        [00:00:00] SUCCESS hello.bst: Staging sources
        [--:--:--] START   hello.bst: Running configure-commands
        [--:--:--] STATUS  hello.bst: Running configure-commands

            cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
            -DCMAKE_INSTALL_LIBDIR=lib
        CMake Error: The source directory "/buildstream/outOfSourceBuilds2/hello.bst" does not appear to contain CMakeLists.txt.
        Specify --help for usage, or press the help button on the CMake GUI.
        [00:00:00] FAILURE hello.bst: Running configure-commands
        [--:--:--] START   hello.bst: Caching artifact
        [00:00:00] SUCCESS hello.bst: Caching artifact
        [00:00:01] FAILURE hello.bst: Command 'cmake -B_builddir -H"/buildstream/outOfSourceBuilds2/hello.bst/././" -G"Unix Makefiles" -DCMAKE_INSTALL_PREFIX:PATH="/usr" \
        -DCMAKE_INSTALL_LIBDIR=lib' failed with exitcode 1
        ======================================================================

Pipeline Summary
  Total:       3
  Session:     1
  Fetch Queue: processed 0, skipped 1, failed 0 
  Build Queue: processed 0, skipped 0, failed 1 


 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  ls
elements  files  hlws  project.conf
 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  ls hlws/
build  Source
 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  ls hlws/Source/
CMakeLists.txt  main.c
 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  ls hlws/build/
 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  bst build hello.bst
[--:--:--][][] START   Build
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[00:00:00][][] SUCCESS Resolving elements
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state
[--:--:--][][] BUG     cmake element at hello.bst [line 1 column 0]: Missing artifact ????????

    Traceback (most recent call last):
      File "/home/will/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/will/projects/buildstream/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/will/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/will/projects/buildstream/buildstream/buildstream/_frontend/cli.py", line 330, in build
        build_all=all_)
      File "/home/will/projects/buildstream/buildstream/buildstream/_stream.py", line 184, in build
        dynamic_plan=True)
      File "/home/will/projects/buildstream/buildstream/buildstream/_stream.py", line 933, in _load
        selected = self._pipeline.get_selection(elements, selection, silent=False)
      File "/home/will/projects/buildstream/buildstream/buildstream/_pipeline.py", line 209, in get_selection
        elements = self.plan(targets)
      File "/home/will/projects/buildstream/buildstream/buildstream/_pipeline.py", line 178, in plan
        return _Planner().plan(elements, plan_cached)
      File "/home/will/projects/buildstream/buildstream/buildstream/_pipeline.py", line 485, in plan
        self.plan_element(root, 0)
      File "/home/will/projects/buildstream/buildstream/buildstream/_pipeline.py", line 476, in plan_element
        if not element._cached_success():
      File "/home/will/projects/buildstream/buildstream/buildstream/element.py", line 967, in _cached_success
        return self.__cached_success(keystrength=None)
      File "/home/will/projects/buildstream/buildstream/buildstream/element.py", line 2626, in __cached_success
        success, _, _ = self.__get_build_result(keystrength=keystrength)
      File "/home/will/projects/buildstream/buildstream/buildstream/element.py", line 2618, in __get_build_result
        self.__load_build_result(keystrength)
      File "/home/will/projects/buildstream/buildstream/buildstream/element.py", line 2598, in __load_build_result
        self.__assert_cached(keystrength=keystrength)
      File "/home/will/projects/buildstream/buildstream/buildstream/element.py", line 2108, in __assert_cached
        self, self._get_brief_display_key())
    AssertionError: cmake element at hello.bst [line 1 column 0]: Missing artifact ????????

 will  CT-will-S-Deb  ~  projects  …  doc  examples  out-of-source-builds3  willsalmon/outOfSourecBuild  ✎  3?  $  

```
## Possible fixes

It only happens when there is a workspace so the fix is probs already in the non workspace code.

## Other relevant information

Normally this would not happen becasue you would change something between trying to build but if you are hacking on bst then this is a use case, ehter way it should not crash like this

Current master: 7b32e1ec903d658dfa75c754b0dd45a3e9331638

I am actually in a branch but i think i have seen this before but not under stood.

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 7, 2018, 14:38

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 18, 2018, 15:10

removed milestone

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 10:57

I got the following while reproducing this 

```
    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/joshsmith/buildstream/buildstream/element.py", line 1549, in _assemble
        self.__prepare(sandbox)
      File "/home/joshsmith/buildstream/buildstream/element.py", line 2077, in __prepare
        self.prepare(sandbox)
      File "/home/joshsmith/buildstream/buildstream/buildelement.py", line 213, in prepare
        self.__run_command(sandbox, cmd, 'configure-commands')
      File "/home/joshsmith/buildstream/buildstream/buildelement.py", line 248, in __run_command
        collect=self.get_variable('install-root'))
    buildstream.element.ElementError: Command 'exit 1' failed with exitcode 1
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/joshsmith/buildstream/buildstream/_scheduler/jobs/job.py", line 400, in _child_action
        result = self.child_process()
      File "/home/joshsmith/buildstream/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/joshsmith/buildstream/buildstream/_scheduler/queues/buildqueue.py", line 71, in process
        return element._assemble()
      File "/home/joshsmith/buildstream/buildstream/element.py", line 1635, in _assemble
        self._assemble_done()
      File "/home/joshsmith/buildstream/buildstream/element.py", line 1487, in _assemble_done
        self._get_context().get_workspaces().save_config()
      File "/home/joshsmith/buildstream/buildstream/_workspaces.py", line 292, in save_config
        assert utils._is_main_process()
    AssertionError
```

To reproduce, I added `exit 1` as a `configure-command`.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 11:36

[This comment](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/element.py#L1476) is invalid as the `utils._is_main_process()` [assertion](https://gitlab.com/BuildStream/buildstream/blob/master/buildstream/_workspaces.py#L292) is failing in this case.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 19, 2018, 11:41

[[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) do you get this the first or second time you run? because if its the first time then you have a separate bug...

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 11:56

Second.

I build it to fail it, It fails.

I build it to fail again, it fails and triggers a save of the workspace config. During this attempted workspace save, an assertion fails since we're still in the child process...

### Breakdown

```
[--:--:--][????????][build:5G.bst                        ] START   Staging dependencies
[00:00:00][????????][build:5G.bst                        ] FAILURE Staging dependencies
[--:--:--][????????][build:5G.bst                        ] START   Caching artifact
[00:00:00][????????][build:5G.bst                        ] SUCCESS Caching artifact
[00:00:00][????????][build:5G.bst                        ] FAILURE Attempt to access unavailable artifact: [Errno 2] No such file or directory: '/home/joshsmith/.cache/buildstream/artifacts/cas/refs/heads/CAS-interaction/5G/befbf0c20c626fd884dd851299aeb67722ed87aeb9c760f5b5fb8380012c8d07'
```

No assertion error here...

Running again however...

```
[--:--:--][????????][build:5G.bst                        ] START   CAS-interaction/5G/????????-build.12510.log
[--:--:--][????????][build:5G.bst                        ] START   Staging dependencies
[00:00:00][????????][build:5G.bst                        ] FAILURE Staging dependencies
[00:00:00][????????][build:5G.bst                        ] BUG     Build

    An unhandled exception occured:
    
    Traceback (most recent call last):
      File "/home/joshsmith/buildstream/buildstream/_artifactcache/cascache.py", line 509, in resolve_ref
        with open(refpath, 'rb') as f:
    FileNotFoundError: [Errno 2] No such file or directory: '/home/joshsmith/.cache/buildstream/artifacts/cas/refs/heads/CAS-interaction/5G/befbf0c20c626fd884dd851299aeb67722ed87aeb9c760f5b5fb8380012c8d07'
    
    The above exception was the direct cause of the following exception:
    
    Traceback (most recent call last):
      File "/home/joshsmith/buildstream/buildstream/element.py", line 1547, in _assemble
        self.stage(sandbox)
      File "/home/joshsmith/buildstream/buildstream/buildelement.py", line 168, in stage
        self.stage_dependency_artifacts(sandbox, Scope.BUILD)
      File "/home/joshsmith/buildstream/buildstream/element.py", line 672, in stage_dependency_artifacts
        old_dep_keys = self.__get_artifact_metadata_dependencies(workspace.last_successful)
      File "/home/joshsmith/buildstream/buildstream/element.py", line 2522, in __get_artifact_metadata_dependencies
        artifact_base, key = self.__extract(key)
      File "/home/joshsmith/buildstream/buildstream/element.py", line 2474, in __extract
        return (self.__artifacts.extract(self, key), key)
      File "/home/joshsmith/buildstream/buildstream/_artifactcache/cascache.py", line 90, in extract
        tree = self.resolve_ref(ref, update_mtime=True)
      File "/home/joshsmith/buildstream/buildstream/_artifactcache/cascache.py", line 518, in resolve_ref
        raise ArtifactError("Attempt to access unavailable artifact: {}".format(e)) from e
    buildstream._exceptions.ArtifactError: Attempt to access unavailable artifact: [Errno 2] No such file or directory: '/home/joshsmith/.cache/buildstream/artifacts/cas/refs/heads/CAS-interaction/5G/befbf0c20c626fd884dd851299aeb67722ed87aeb9c760f5b5fb8380012c8d07'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/home/joshsmith/buildstream/buildstream/_scheduler/jobs/job.py", line 409, in _child_action
        result = self.child_process()
      File "/home/joshsmith/buildstream/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/joshsmith/buildstream/buildstream/_scheduler/queues/buildqueue.py", line 72, in process
        return element._assemble()
      File "/home/joshsmith/buildstream/buildstream/element.py", line 1635, in _assemble
        self._assemble_done()
      File "/home/joshsmith/buildstream/buildstream/element.py", line 1487, in _assemble_done
        self._get_context().get_workspaces().save_config()
      File "/home/joshsmith/buildstream/buildstream/_workspaces.py", line 292, in save_config
        assert utils._is_main_process()
    AssertionError
```

We see the assertion error while trying to stage dependencies.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 15:10

assigned to [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 16:28

Bisecting has lead me to the conclusion that d14d8ee29b5fcaadcfd05934de71b46221243fcd is the start of the issue within BuildStream history.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 19, 2018, 17:45

#651 and this were failing with the `AssertionError: cmake element at hello.bst [line 1 column 0]: Missing artifact ????????`

Neither now fail with `Missing artifact ????????` 

They both still fail so we might as well keep the tickets but the issue that they were both running in to is no longer there. there have been a number of patches relating to the cache so it seems likely that one of them fixed the issue.

As [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) has identified the error starts with the introduction of cached builds as if we didn't cache failures then we couldn't fail to recover them but its interesting that even now we are able to get the cached build we have just exposed another bug.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 17:52

I think I've got a partial fix. I'll look into it more tomorrow [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 17:54

mentioned in commit 9d5794a2f1ab03951c0332041a3bb8e20847ff0a

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Sep 19, 2018, 17:55

mentioned in merge request !812

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Oct 3, 2018, 14:03

mentioned in commit e6d37335f4cba910ac030ad42fc09f0288d95aa9

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @Qinusty]](https://gitlab.com/Qinusty) on Oct 4, 2018, 14:43

mentioned in commit c5778941217fb0ebbaed6eb6d6a0b255918e01a4

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 4, 2018, 14:51

This will be fixed by !812, which had a `Needs Backport` label on it, however we do not cache failed builds in `1.2.x`.

So my question is: Does this bug happen in `1.2.x` ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 4, 2018, 15:11

closed via merge request !812

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 4, 2018, 15:11

mentioned in commit 8630bac464a9b98654485a2b8699eb38083b0eb5
