### ISSUE TITLE
bst source-bundle fail's for the examples.

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#651]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/651)
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 13, 2018, 10:26

## Summary

Buildstream source-bundle fail's for the examples.

## Steps to reproduce

steps:
- cd buildstream/doc/examples/flatpak-autotools
- bst build hello.bst
- bst source-bundle hello.bst

## What is the current bug behaviour?

bst reports a bug and:
`
FileNotFoundError: [Errno 2] No such file or directory: '/home/will/.cache/buildstream/build/hello-y64su587/source/base-sdk'
`

## What is the expected correct behavior?

Creates a folder/zip of the sources so you can build the element yourself. (I have not got this to work but I believe it should be a bit like a workspace but without the option to build in it.)

## Relevant logs and/or screenshots

```

 will  CT-will-S-Deb  ~  projects  …  doc  examples  flatpak-autotools $ bst source-bundle hello.bst
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[00:00:00][][] SUCCESS Resolving elements
[--:--:--][][] START   Resolving cached state
[00:00:00][][] SUCCESS Resolving cached state
[--:--:--][][] INFO    Bundling sources for target hello.bst
[--:--:--][][] START   Checking sources
[00:00:00][][] SUCCESS Checking sources
[--:--:--][d34ccf53][ main:base/sdk.bst                  ] START   Writing build script
[00:00:00][d34ccf53][ main:base/sdk.bst                  ] SUCCESS Writing build script
[--:--:--][94d6556f][ main:base/usrmerge.bst             ] START   Writing build script
[00:00:00][94d6556f][ main:base/usrmerge.bst             ] SUCCESS Writing build script
[--:--:--][cf34223f][ main:hello.bst                     ] START   Writing build script
[00:00:00][cf34223f][ main:hello.bst                     ] SUCCESS Writing build script
[--:--:--][d34ccf53][ main:base/sdk.bst                  ] START   Staging sources
[--:--:--][][] BUG     [Errno 2] No such file or directory: '/home/will/.cache/buildstream/build/hello-y64su587/source/base-sdk'

    Traceback (most recent call last):
      File "/home/will/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)
      File "/home/will/projects/buildstream/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/will/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)
      File "/home/will/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/will/projects/buildstream/buildstream/buildstream/_frontend/cli.py", line 831, in source_bundle
        except_targets=except_)
      File "/home/will/projects/buildstream/buildstream/buildstream/_stream.py", line 723, in source_bundle
        self._write_element_sources(tempdir, elements)
      File "/home/will/projects/buildstream/buildstream/buildstream/_stream.py", line 1092, in _write_element_sources
        element._stage_sources_at(element_source_dir)
      File "/home/will/projects/buildstream/buildstream/buildstream/element.py", line 1374, in _stage_sources_at
        if not vdirectory.is_empty():
      File "/home/will/projects/buildstream/buildstream/buildstream/storage/_filebaseddirectory.py", line 179, in is_empty
        self._populate_index()
      File "/home/will/projects/buildstream/buildstream/buildstream/storage/_filebaseddirectory.py", line 61, in _populate_index
        for entry in os.listdir(self.external_directory):
    FileNotFoundError: [Errno 2] No such file or directory: '/home/will/.cache/buildstream/build/hello-y64su587/source/base-sdk'

```

## Possible fixes

...

## Other relevant information

This was discovered while working on #512 but fixing this is not required to close it.

* BuildStream version affected: master (c6155f8d40b5fc4564ed66b4f9d2cc0ad7144b8f) /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 13, 2018, 10:27

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 13, 2018, 13:50

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 13, 2018, 14:18

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Sep 18, 2018, 15:10

removed milestone

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 18, 2018, 18:15

mentioned in commit fe69f3d1f83a0d13f0d51f1f3e6dc2a3fbb3b686

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 18, 2018, 18:17

mentioned in merge request !807

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 18, 2018, 18:58

mentioned in commit 2a3359d31a69a54841d237a14bcaed4aa6ad40e1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 21, 2018, 14:10

mentioned in commit e209beb0ce71eb2214cd5ac663a577dbf423ecc2

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 21, 2018, 14:56

closed via merge request !807

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Sep 21, 2018, 14:56

mentioned in commit 0b0005181676b9f60768495c91aa65818b6d318b
