### ISSUE TITLE
Crash in `bst fetch` with mirroring configured and project.refs storage

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#666]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/666)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 05:56

## Summary

[//]: # (Summarize the bug encountered concisely)

BuildStream crashes with a BUG message and stack trace when fetching a source that:

* Uses `ref-storage: project.refs`
* Does have a ref listed for the given source in the `project.refs`
* Has a mirror configured with at least one redirected alias

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
Failure Summary
  sdk/brotli.bst:
    [00:00:00][d17fe05b][fetch:sdk/brotli.bst                ] BUG     Fetch

        An unhandled exception occured:
    
        Traceback (most recent call last):
          File "/codethink/GNOME/buildstream/buildstream/_scheduler/jobs/job.py", line 407, in _child_action
            result = self.child_process()
          File "/codethink/GNOME/buildstream/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
            return self._action_cb(self._element)
          File "/codethink/GNOME/buildstream/buildstream/_scheduler/queues/fetchqueue.py", line 44, in process
            source._fetch()
          File "/codethink/GNOME/buildstream/buildstream/source.py", line 630, in _fetch
            new_source.fetch()
          File "/codethink/GNOME/buildstream/buildstream/plugins/sources/_downloadablefilesource.py", line 80, in fetch
            if os.path.isfile(self._get_mirror_file()):
          File "/codethink/GNOME/buildstream/buildstream/plugins/sources/_downloadablefilesource.py", line 171, in _get_mirror_file
            return os.path.join(self._get_mirror_dir(), sha or self.ref)
          File "/usr/lib/python3.5/posixpath.py", line 89, in join
            genericpath._check_arg_types('join', a, *p)
          File "/usr/lib/python3.5/genericpath.py", line 143, in _check_arg_types
            (funcname, s.__class__.__name__)) from None
        TypeError: join() argument must be str or bytes, not 'NoneType'
```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

Fix source re-instantiation involved with fetching with mirroring enabled, such that the resulting newly instantiated Source has passed through the same loading codepaths as it does normally.

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 06:15

mentioned in commit 42ec5cc6e6b8d3452184c0aa429c285bbddf0df8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 06:18

mentioned in merge request !816

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 06:23

mentioned in commit 68ef69e47482bda2bb759386befccd4991d38269

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 06:24

mentioned in merge request !817

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 06:59

closed via merge request !817

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Sep 21, 2018, 06:59

mentioned in commit 662c729fa32489312beed6318956ba9ce94e685f

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Oct 4, 2018, 14:38

mentioned in merge request !823
