### ISSUE TITLE
flatpak-autotools example broken

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#690]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/690)
In GitLab by [[Gitlab user @finnball]](https://gitlab.com/finnball) on Oct 2, 2018, 14:42

## Summary

Tried following this example:

https://buildstream.gitlab.io/buildstream/examples/flatpak-autotools.html

## Steps to reproduce

Run the above example on debian

## What is the current bug behavior?

```
buildgrid[[Gitlab user @client-vm]](https://gitlab.com/client-vm):~/buildstream/doc/examples/flatpak-autotools$ bst build hello.bst
[--:--:--][][] START   Build
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[00:00:00][][] SUCCESS Resolving elements
[--:--:--][][] START   Resolving cached state
[--:--:--][][] BUG     'Repo' object has no attribute 'reload_config'

    Traceback (most recent call last):
      File "/home/buildgrid/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/buildgrid/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/home/buildgrid/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/buildgrid/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/home/buildgrid/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/buildgrid/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/buildgrid/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/home/buildgrid/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/home/buildgrid/buildstream/buildstream/_frontend/cli.py", line 330, in build
        build_all=all_)
      File "/home/buildgrid/buildstream/buildstream/_stream.py", line 182, in build
        dynamic_plan=True)
      File "/home/buildgrid/buildstream/buildstream/_stream.py", line 931, in _load
        self._pipeline.resolve_elements(elements)
      File "/home/buildgrid/buildstream/buildstream/_pipeline.py", line 139, in resolve_elements
        element._update_state()
      File "/home/buildgrid/buildstream/buildstream/element.py", line 1066, in _update_state
        self.__update_source_state()
      File "/home/buildgrid/buildstream/buildstream/element.py", line 2008, in __update_source_state
        source._update_state()
      File "/home/buildgrid/buildstream/buildstream/source.py", line 650, in _update_state
        self.__consistency = self.get_consistency()
      File "/home/buildgrid/buildstream/buildstream/plugins/sources/ostree.py", line 169, in get_consistency
        self.ensure()
      File "/home/buildgrid/buildstream/buildstream/plugins/sources/ostree.py", line 181, in ensure
        self.repo = _ostree.ensure(self.mirror, True)
      File "/home/buildgrid/buildstream/buildstream/_ostree.py", line 66, in ensure
        repo.reload_config()
    AttributeError: 'Repo' object has no attribute 'reload_config'
```

## What is the expected correct behavior?

It should work.

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @finnball]](https://gitlab.com/finnball) on Oct 2, 2018, 14:57

closed

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Nov 14, 2019, 12:55

https://gitlab.com/BuildStream/buildstream/pipelines/95903565 this element is continuing to have some issues

the problem seems to be in the sdk.bst since sdk.gnome.org is offline

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Nov 14, 2019, 12:55

reopened

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Nov 19, 2019, 19:23

mentioned in merge request !1719

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Nov 19, 2019, 22:00

closed via merge request !1719

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Nov 19, 2019, 22:00

mentioned in commit 9bf0eae1cb887f1bb214b72e11f1212b6a8bc2c4
