### ISSUE TITLE
test for import failures for auto completes

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#751]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/751)
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Nov 6, 2018, 11:48

## Summary

bst is invoked sufficiently differently at complete time (on my Debian install with the standard install from source) that _stream.py can not be imported and if you import it into _frontend/cli.py then bst will crash for auto complete.

while this is not a bug as we do not currently import _stream.py in to _frontend/cli.py the failure is not catch by our tests.

I got some code quite close to getting merged before i noticed this behavour and so i think it would make a good subject of a regression test.

## Steps to reproduce

import _stream.py in to _frontend/cli.py and then try to use auto complete.
Note: i am not preposing to fix the bug but just to have a test that would catch it if any one tried to merge such a change.

## What is the current bug behaviour?

This class of error is not caught by the tests:

```
 will  CT-will-S-Deb  ~  projects  buildstream  buildstream  willsalmon/defaultWorkspaces  ?  1  $  bst sTraceback (most recent call last):
  File "/home/will/.local/bin/bst", line 5, in <module>
    from buildstream._frontend import cli
  File "/home/will/projects/buildstream/buildstream/buildstream/_frontend/__init__.py", line 20, in <module>
    from .cli import cli
  File "/home/will/projects/buildstream/buildstream/buildstream/_frontend/cli.py", line 9, in <module>
    from .._stream import DirectoryDescription
  File "/home/will/projects/buildstream/buildstream/buildstream/_stream.py", line 33, in <module>
    from ._scheduler import Scheduler, SchedStatus, TrackQueue, FetchQueue, BuildQueue, PullQueue, PushQueue
  File "/home/will/projects/buildstream/buildstream/buildstream/_scheduler/__init__.py", line 22, in <module>
    from .queues.fetchqueue import FetchQueue
  File "/home/will/projects/buildstream/buildstream/buildstream/_scheduler/queues/fetchqueue.py", line 22, in <module>
    from ... import Consistency
ImportError: cannot import name 'Consistency'
```

## What is the expected correct behaviour?

This should be caught by the tests.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Nov 6, 2018, 11:48

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Aug 4, 2020, 23:39

I don't think this is really a bug.

First, it is fine to import to `_stream` from `_frontend.cli`. We don't do it for design reasons, but that should be fine technically. I tried it with the following example and things seem to work fine.

```diff
--- a/src/buildstream/_frontend/cli.py
+++ b/src/buildstream/_frontend/cli.py
[[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) -2,6 +2,8 [[Gitlab user @]](https://gitlab.com/)[[Gitlab user @]](https://gitlab.com/) import os
 import sys
 from functools import partial

+from .. import _stream
+
 import shutil
 import click
 from .. import _yaml
```

I also can't think of a reason why importing only parts of the BuildStream package would fail once it has been installed. At least not in a way that won't also make the test suite fail.

We also have tests for the autocomplete business. So, I'm reasonably confident that this would have been caused by some other issue in your environment. (perhaps some files were moved etc)

Closing it as per above, feel free to reopen in case I may have missed something.
