### ISSUE TITLE
Stack trace when integrating a local plugin

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#764]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/764)
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Nov 13, 2018, 11:51

## Summary

[//]: # (Summarize the bug encountered concisely)
A stack trace is produced when trying to build with a local plugin installed.

## Steps to reproduce

Install collect_manifest.bst from bst-external

## What is the current bug behavior?

[//]: # (What actually happens)

Produces a stack trace.

## What is the expected correct behavior?

[//]: # (What you should see instead)

Fail with a helpful error message

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```
Failure Summary
  platform-manifest.bst:
    [00:00:01][06efeae7][build:platform-manifest.bst         ] BUG     Build

        An unhandled exception occured:

        Traceback (most recent call last):
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/job.py", line 415, in _child_action
            result = self.child_process()
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
            return self._action_cb(self._element)
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_scheduler/queues/buildqueue.py", line 35, in process
            return element._assemble()
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/element.py", line 1498, in _assemble
            collect = self.assemble(sandbox)
          File "/home/adds68/git-repos/freedesktop-sdk/plugins/elements/collect_manifest.py", line 145, in assemble
            self.set_public_data('cpe-manifest', manifest)
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/element.py", line 855, in set_public_data
            data = _yaml.node_copy(data)
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 1082, in node_copy
            copy[key] = list_copy(value)
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 1097, in list_copy
            copy.append(node_copy(item))
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 1080, in node_copy
            copy[key] = node_copy(value)
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 1084, in node_copy
            copy[key] = value.clone()
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 105, in clone
            for member_name, member in self.members.items()
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 105, in <dictcomp>
            for member_name, member in self.members.items()
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 130, in clone
            provenance.elements = [e.clone() for e in self.elements]
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 130, in <listcomp>
            provenance.elements = [e.clone() for e in self.elements]
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 155, in clone
            provenance.elements = [e.clone for e in self.elements]
          File "/home/adds68/.local/lib/python3.7/site-packages/buildstream/_yaml.py", line 155, in <listcomp>
            provenance.elements = [e.clone for e in self.elements]
        AttributeError: 'function' object has no attribute 'clone'

```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

.bst file where is fails
```
kind: collect_manifest

config:
  path: "%{prefix}/manifest.json"

depends:
  - filename: desktop-platform.bst
    type: build
  - filename: bootstrap-manifest.bst
    junction: bootstrap-junction.bst
    type: build
```

* BuildStream version affected: /milestone %BuildStream_v1.2.3

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Nov 22, 2018, 15:08

mentioned in merge request bst-external!60

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Nov 22, 2018, 16:47

mentioned in merge request freedesktop-sdk/freedesktop-sdk!735

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) on Nov 26, 2018, 08:58

[[Gitlab user @adds68]](https://gitlab.com/adds68) Could you use `cleanup_provenance(manifest)` instead of just `manifest` in call to `set_public_data`?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Dec 6, 2018, 11:38

assigned to [[Gitlab user @adds68]](https://gitlab.com/adds68)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Dec 17, 2018, 12:28

[[Gitlab user @valentindavid]](https://gitlab.com/valentindavid) Thanks! This seems to have fixed it, i will close now and do some further checks once i have everything cleaned up.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @adds68]](https://gitlab.com/adds68) on Dec 17, 2018, 12:28

closed
