### ISSUE TITLE
Unhandled NoneType exception

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#803]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/803)
In GitLab by [[Gitlab user @knownexus]](https://gitlab.com/knownexus) on Dec 5, 2018, 09:45

## Summary

[//]: # (Summarize the bug encountered concisely)
If you have an element with "depends:" but nothing in the depends, it gives a nonetype error

## Steps to reproduce

make a normal element and add a "depends:" line to it, but no dependency beneath it

>  kind: stack
>
>  description: |
>
> 
> 
>    Main stack target for the bst build test
>
>
>
>  depends:
>
> 

Attempt to build this project and you will get an exception

[//]: # (How one can reproduce the issue - this is very important)

## What is the current bug behavior?

[//]: # (What actually happens)    

A NoneType exception is thrown

## What is the expected correct behavior?

[//]: # (What you should see instead)
 I would expect an invalid YAML error

## Relevant logs and/or screenshots

     Traceback (most recent call last):
 
     File "/home/phillipsmyth/.local/bin/bst", line 8, in <module>
        sys.exit(cli())

      File "/home/phillipsmyth/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
        return self.main(*args, **kwargs)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_frontend/cli.py", line 166, in override_main
        standalone_mode=standalone_mode, **extra)

      File "/home/phillipsmyth/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
        rv = self.invoke(ctx)

      File "/home/phillipsmyth/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))

      File "/home/phillipsmyth/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
        return ctx.invoke(self.callback, **ctx.params)

      File "/home/phillipsmyth/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
        return callback(*args, **kwargs)

      File "/home/phillipsmyth/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_frontend/cli.py", line 336, in build
       build_all=all_)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_stream.py", line 182, in build
        dynamic_plan=True)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_stream.py", line 952, in _load
        fetch_subprojects=fetch_subprojects)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_pipeline.py", line 111, in load
        fetch_subprojects=fetch_subprojects)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_project.py", line 334, in load_elements
        fetch_subprojects=fetch_subprojects)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_loader/loader.py", line 134, in load
        loader._load_file(name, rewritable, ticker, fetch_subprojects, yaml_cache)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_loader/loader.py", line 278, in _load_file
        element = LoadElement(node, filename, self)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_loader/loadelement.py", line 78, in __init__
        self.deps = _extract_depends_from_node(self.node)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_loader/loadelement.py", line 135, in 
       _extract_depends_from_node
        depends = _extract_depends_from_node(node, key=Symbol.DEPENDS)

      File "/home/phillipsmyth/projects/buildstream/buildstream/_loader/loadelement.py", line 149, in _extract_depends_from_node
        for index, dep in enumerate(depends):

      TypeError: 'NoneType' object is not iterable

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Dec 7, 2018, 07:59

mentioned in commit 642ae4e8ba4715023c98f24981b412ac146edb88

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Dec 7, 2018, 07:59

mentioned in commit e61e6e50b74813f7a50f8c3a66f54b6682a427b8

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Dec 7, 2018, 08:00

mentioned in merge request !999

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Dec 7, 2018, 08:33

closed via merge request !999

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Dec 7, 2018, 08:33

mentioned in commit 2a0676c3bf607a95a41bd802839eaf677588bf79

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 21, 2019, 08:37

mentioned in merge request !1401
