### ISSUE TITLE
Stack Trace while trying to use autocompletions on `bst workspace open`

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#825]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/825)
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Dec 19, 2018, 08:59

## Summary

While trying to autocomplete a `bst workspace open` command, for which I had accidentally mistyped the initial segment of a filename, I got the stack trace below:

```
$ bst workspace open pyh
Traceback (most recent call last):
  File "/home/tom/.local/bin//bst", line 5, in <module>
    from buildstream._frontend import cli
  File "/home/tom/Documents/work/buildstream/buildstream/_frontend/__init__.py", line 20, in <module>
    from .cli import cli
  File "/home/tom/Documents/work/buildstream/buildstream/_frontend/cli.py", line 1088, in <module>
    [[Gitlab user @click]](https://gitlab.com/click).pass_obj
  File "/home/tom/.local/lib/python3.7/site-packages/click/core.py", line 1163, in decorator
    cmd = command(*args, **kwargs)(f)
  File "/home/tom/.local/lib/python3.7/site-packages/click/decorators.py", line 115, in decorator
    cmd = _make_command(f, name, attrs, cls)
  File "/home/tom/.local/lib/python3.7/site-packages/click/decorators.py", line 89, in _make_command
    callback=f, params=params, **attrs)
TypeError: __init__() got an unexpected keyword argument 'hidden'
```

Edit: it seems autocompletions are not working for me generally here.

## Steps to reproduce

I can reproduce reliably by:

1) Clone [libreml](https://gitlab.com/libreml/libreml)
2) Type `bst workspace open pyh` and attempt to autocomplete.
3) Observe the stack trace

## What is the expected correct behavior?

There should be no traceback or output - nothing should happen.

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.2

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Dec 19, 2018, 09:00

changed title from **Stack Trace while trying to use autocompletions on `bst workspace open`{- with mistyped initial segment-}** to **Stack Trace while trying to use autocompletions on `bst workspace open`**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Dec 19, 2018, 09:00

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Dec 19, 2018, 09:02

It looks like this was due to me using master, not 1.2. Will users have to change the auto-completions installation on the next update?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 19, 2018, 19:26

Hi [[Gitlab user @coldtom]](https://gitlab.com/coldtom), I believe this might be caused due to an old version of Click. Since https://gitlab.com/BuildStream/buildstream/merge_requests/1003 was merged, BuildStream requires Click version >= 7.0.

Can you please check which version of Click you have? (Can use something like `pip3 show Click`)

If you are running an older version of Click, please try updating it and let us know if the problem persists.

> Will users have to change the auto-completions installation on the next update?

I don't think so. But, they will have to ensure that they have the correct dependencies installed, IF they update BuildStream by checking out a new commit in the local git repo. Fresh installs, or updates via pip should automatically take care of this.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @coldtom]](https://gitlab.com/coldtom) on Dec 20, 2018, 09:42

Ah yes, that was the issue, thanks!

It may be worth mentioning that this can cause issues somewhere, perhaps the installing from source section of the docs?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 20, 2018, 15:51

This is kind of mentioned at https://buildstream.build/source_install.html#upgrading-from-a-git-checkout:

> If you did not specify the -e option at install time or the dependancies have changed, you will need to cleanly reinstall BuildStream:
>
> \<snip\>

If you have any ideas about how to make it more obvious and visible to users, we should probably update https://gitlab.com/BuildStream/website.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 20, 2018, 16:29

Seems like [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) has recently sent a ML message about it (https://mail.gnome.org/archives/buildstream-list/2018-December/msg00143.html). Thanks for that! :)

Do you think this issue can be closed now?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Dec 20, 2018, 16:38

I read all of this and yet when I go to the error I didn't twig it was the same thing... I chatted to [[Gitlab user @jmacarthur]](https://gitlab.com/jmacarthur) about maybe catching the error and flagging a warning, but he pointed but, do we really want to add warnings every time dependencies change? as we recommend installation from package rather than source and the point of a package is to sort this sort of thing it seems like this is just one of those things...

I vote to close but if we could all keep a eye on irc/ML so if anyone has a similar issue we can help them asap?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 20, 2018, 16:52

For now, I agree to keep an eye out on IRC/ML.

For the long run, I don't think that BuildStream itself should raise warnings when we update our dependencies. That's clearly in territory of package managers. I imagine this would automatically get better with time as BuildStream becomes available in various distros.

Having said that, I don't really see a reason to not install BuildStream using pip via PyPI (for end-users). I don't think our users need to deal with the git repo. That makes a ton of sense for folks developing BuildStream, but not so much for the users IMHO.

If that makes sense to others, then we can say something along these lines on the install page. And, for developers, add something to the CONTRIBUTING file about how to handle upgrades.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Dec 20, 2018, 16:56

https://buildstream.build/install.html pretty much recommends that now.

Apparently we are not having any installation instructions in the repo but all on the website... I assumed this stretched to upgrade instructions?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @cs-shadow]](https://gitlab.com/cs-shadow) on Dec 20, 2018, 17:18

I was thinking more like removing those instructions (install via git/tarball) entirely from the install guide, which should make it simpler. (This may be potentially controversial.)

> Apparently we are not having any installation instructions in the repo but all on the website... I assumed this stretched to upgrade instructions?

My impression is that the website is for end-users mostly, and if so, pulling out developer instructions from there would make sense. Unless people think that there is a clear disadvantage for installing via pip directly. It's worth noting that we already require pip (and PyPI) for installing our dependencies, so installing via git or a tarball doesn't require fewer host tools as well.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Dec 20, 2018, 17:24

Umm, 
Personally I don't like having the install instruction out of the repo
Having the install from source in the repo and the package install instructions on the website would be cute but then the install instructions would be split up, which would be less good... I don't know.
How ever its done, the discussion should move to the ML/new issue.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Dec 20, 2018, 17:26

Closing after checking with [[Gitlab user @coldtom]](https://gitlab.com/coldtom) else were

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @willsalmon]](https://gitlab.com/willsalmon) on Dec 20, 2018, 17:26

closed
