### ISSUE TITLE
BUG hit: "no module named 'grpc.framework'

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#853]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/853)
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jan 9, 2019, 19:02

## Summary

[//]: # (Summarize the bug encountered concisely)

We got a stack trace when trying to push an element

```
[bschubert[[Gitlab user @me]](https://gitlab.com/me)]$ cat 0eae8fd3-push.24630.log
[--:--:--] START   ${ELEMENT}.bst: Push
[--:--:--] LOG     ${ELEMENT}.bst: Build environment for element ${ELEMENT}.bst

    HOME: /tmp
    LC_ALL: C
    LOGNAME: tomjon
    PATH: /usr/bin:/bin:/usr/sbin:/sbin
    SHELL: /bin/sh
    SOURCE_DATE_EPOCH: '1320937200'
    TERM: dumb
    TZ: UTC
    USER: tomjon
    USERNAME: tomjon
[--:--:--] BUG     ${ELEMENT}.bst: Push

    An unhandled exception occured:

    Traceback (most recent call last):
      File "/home/bschubert/.local/lib/python3.6/site-packages/buildstream/_scheduler/jobs/job.py", line 417, in _child_action
        result = self.child_process()  # pylint: disable=assignment-from-no-return
      File "/home/bschubert/.local/lib/python3.6/site-packages/buildstream/_scheduler/jobs/elementjob.py", line 94, in child_process
        return self._action_cb(self._element)
      File "/home/bschubert/.local/lib/python3.6/site-packages/buildstream/_scheduler/queues/pushqueue.py", line 37, in process
        if not element._push():
      File "/home/bschubert/.local/lib/python3.6/site-packages/buildstream/element.py", line 1835, in _push
        pushed = self.__artifacts.push(self, self.__get_cache_keys_for_commit())
      File "/home/bschubert/.local/lib/python3.6/site-packages/buildstream/_artifactcache/artifactcache.py", line 623, in push
        remote.init()
      File "/home/bschubert/.local/lib/python3.6/site-packages/buildstream/_artifactcache/cascache.py", line 1185, in init
        self.channel = grpc.secure_channel('{}:{}'.format(url.hostname, port), credentials)
      File "/home/bschubert/.local/lib/python3.6/site-packages/grpc/__init__.py", line 1675, in secure_channel
        from grpc import _channel  # pylint: disable=cyclic-import
      File "/home/bschubert/.local/lib/python3.6/site-packages/pluginbase.py", line 439, in plugin_import
        fromlist, level)
      File "/home/bschubert/.local/lib/python3.6/site-packages/grpc/_channel.py", line 25, in <module>
        from grpc.framework.foundation import callable_util
      File "/home/bschubert/.local/lib/python3.6/site-packages/pluginbase.py", line 439, in plugin_import
        fromlist, level)
    ModuleNotFoundError: No module named 'grpc.framework'
```

Launching python and "import grpc.framework" does work. Pushing again did work.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

Sadly... no idea

## What is the current bug behavior?

[//]: # (What actually happens)

## What is the expected correct behavior?

[//]: # (What you should see instead)

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @danielsilverstone-ct]](https://gitlab.com/danielsilverstone-ct) on Mar 29, 2019, 08:35

Since noone else has chimed in to say that they have encountered this, and you've not updated to say that you've encountered it again, I suggest we put it down to a bogon on your computer and move on.  The backtrace does look odd because grpc was clearly there.

[[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) are you prepared to have this closed?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Mar 29, 2019, 15:54

Let's close this, I'll reopen if I hit this again

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Mar 29, 2019, 15:54

closed
