### ISSUE TITLE
Traceback with current master (564cb2450a8657762e16c1d26d1373987dc4a6c5)

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#884]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/884)
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 14:23

After following the instructions to install current master (commit 564cb2450a8657762e16c1d26d1373987dc4a6c5) from source using pip (https://buildstream.build/source_install.html#install_git), I'm getting the following:

```
# bst help
Traceback (most recent call last):
  File "/root/.local/bin/bst", line 5, in <module>
    from buildstream._frontend import cli
  File "/root/.local/lib/python3.7/site-packages/buildstream/__init__.py", line 30, in <module>
    from .sandbox import Sandbox, SandboxFlags, SandboxCommandError
  File "/root/.local/lib/python3.7/site-packages/buildstream/sandbox/__init__.py", line 21, in <module>
    from ._sandboxremote import SandboxRemote
  File "/root/.local/lib/python3.7/site-packages/buildstream/sandbox/_sandboxremote.py", line 37, in <module>
    from .._protos.google.rpc import code_pb2
  File "/root/.local/lib/python3.7/site-packages/buildstream/_protos/google/rpc/code_pb2.py", line 23, in <module>
    serialized_pb=_b('\n\x15google/rpc/code.proto\x12\ngoogle.rpc*\xb7\x02\n\x04\x43ode\x12\x06\n\x02OK\x10\x00\x12\r\n\tCANCELLED\x10\x01\x12\x0b\n\x07UNKNOWN\x10\x02\x12\x14\n\x10INVALID_ARGUMENT\x10\x03\x12\x15\n\x11\x44\x45\x41\x44LINE_EXCEEDED\x10\x04\x12\r\n\tNOT_FOUND\x10\x05\x12\x12\n\x0e\x41LREADY_EXISTS\x10\x06\x12\x15\n\x11PERMISSION_DENIED\x10\x07\x12\x13\n\x0fUNAUTHENTICATED\x10\x10\x12\x16\n\x12RESOURCE_EXHAUSTED\x10\x08\x12\x17\n\x13\x46\x41ILED_PRECONDITION\x10\t\x12\x0b\n\x07\x41\x42ORTED\x10\n\x12\x10\n\x0cOUT_OF_RANGE\x10\x0b\x12\x11\n\rUNIMPLEMENTED\x10\x0c\x12\x0c\n\x08INTERNAL\x10\r\x12\x0f\n\x0bUNAVAILABLE\x10\x0e\x12\r\n\tDATA_LOSS\x10\x0f\x42X\n\x0e\x63om.google.rpcB\tCodeProtoP\x01Z3google.golang.org/genproto/googleapis/rpc/code;code\xa2\x02\x03RPCb\x06proto3')
TypeError: __init__() got an unexpected keyword argument 'serialized_options'
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 14:23

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 14:24

changed title from **Traceback with current master ({-cd9b8e54aad6aa885afd28cefbbd40ea77c9353d-})** to **Traceback with current master ({+564cb2450a8657762e16c1d26d1373987dc4a6c5+})**

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 14:24

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @abderrahimk]](https://gitlab.com/abderrahimk) on Jan 28, 2019, 14:59

mentioned in merge request !1114

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 15:19

mentioned in merge request !1115

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 15:20

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 17:54

closed via merge request !1114

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Jan 28, 2019, 17:54

mentioned in commit 80b36d0c5cf89eb9130642c255d18cbdf296cef0
