### ISSUE TITLE
Spurious blockingio error

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#929]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/929)
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Feb 23, 2019, 07:51

## Summary

Today it happened to me that I could not use BuildStream due to a stack trace which happens at the beginning of the session.

After applying an `fcntl` workaround which clears the file descriptor flags on stderr/stdio, BuildStream started working again.

After *removing* the workaround, BuildStream no longer produces the unreproducible error.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)

None.

## What is the current bug behavior?

[//]: # (What actually happens)

Spurious stack traces which rarely happen.

## What is the expected correct behavior?

[//]: # (What you should see instead)

No spurious stack traces

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

Here is a sample of the log file:

```
      cached 15d0d536e33e473b6cdc71fce2c8d935cefa2480aa53e1c13e7d5878ff8fe6e8 freedesktop-sdk.bst:base/libassuan.bst 
      cached 63c47a9a99233e6c20f720202a952cee77d278edd4578c5807493a35d05aa19b freedesktop-sdk.bst:base/libksba.bst 
      cached e8b2afa8d69c88aeb6e148af8290c80eea616c11b6ef10bb3a85a6770d24bf07 freedesktop-sdk.bst:base/npth.bst 
      cached 0277075af66ca787c632cfeb8633dcdbe8fb20875a8cdf55159b56205b8ec38d freedesktop-sdk.bst:base/gnupg.bst 
      cached 7043a1feb89f7c416525cce0b315dbaccb2d61de92fca1994a545c5d952cb1b1 freedesktop-sdk.bst:base/pcre2.bst 
      cached bf4f16eebdd80ff8b70a4fdd4e10f8a922db73e6f6b69a7c663c6638f932a527 freedesktop-sdk.bst:base/git.bst 
      cached 61a91a356e8af39cd6f448cda9b621859b56293c414c9de309423e9040f8ca3d[--:--:--][][] BUG     [Errno 11] write could not complete without blocking

    Traceback (most recent call last):
      File "/home/tristan/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/codethink/GNOME/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/codethink/GNOME/buildstream/buildstream/_frontend/cli.py", line 330, in build
        build_all=all_)
      File "/codethink/GNOME/buildstream/buildstream/_stream.py", line 213, in build
        self._run()
      File "/codethink/GNOME/buildstream/buildstream/_stream.py", line 1006, in _run
        self._session_start_callback()
      File "/codethink/GNOME/buildstream/buildstream/_frontend/app.py", line 637, in session_start_cb
        styling=self.colors)
      File "/codethink/GNOME/buildstream/buildstream/_frontend/widget.py", line 498, in print_heading
        click.echo(text, color=styling, nl=False, err=True)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/utils.py", line 260, in echo
        file.write(message)
    BlockingIOError: [Errno 11] write could not complete without blocking
```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

Clear file descriptor flags unconditionally at startup, can't say right now that this workaround is completely safe. 

The idea for the workaround was taken from a [similar issue](https://github.com/travis-ci/travis-ci/issues/8920#issuecomment-352767521)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Feb 23, 2019, 07:52

mentioned in commit 130cb6d3f7e8fb24567f053a8f87ef8e077f4c98

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Feb 23, 2019, 07:56

For me, !1176 fixed this.

Marking as `WIP` for now to avoid accidental merging... I cannot say for sure that the fix is completely safe.

[[Gitlab user @juergbi]](https://gitlab.com/juergbi), any idea what might be happening here, or if the workaround is okay ?

Also cannot say for sure, perhaps this [upstream python issue](https://bugs.python.org/issue25476) is also related...

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 5, 2019, 13:11

Happened to me again today, at the same place:

```
     ...
     cached 9bc8360c6323e38efc4c77558a000ed[--:--:--][][] BUG     [Errno 11] write could not complete without blocking

    Traceback (most recent call last):
      File "/home/tristan/.local/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/codethink/GNOME/buildstream/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/codethink/GNOME/buildstream/buildstream/_frontend/cli.py", line 330, in build
        build_all=all_)
      File "/codethink/GNOME/buildstream/buildstream/_stream.py", line 213, in build
        self._run()
      File "/codethink/GNOME/buildstream/buildstream/_stream.py", line 1006, in _run
        self._session_start_callback()
      File "/codethink/GNOME/buildstream/buildstream/_frontend/app.py", line 637, in session_start_cb
        styling=self.colors)
      File "/codethink/GNOME/buildstream/buildstream/_frontend/widget.py", line 498, in print_heading
        click.echo(text, color=styling, nl=False, err=True)
      File "/home/tristan/.local/lib/python3.5/site-packages/click/utils.py", line 260, in echo
        file.write(message)
    BlockingIOError: [Errno 11] write could not complete without blocking
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 7, 2019, 08:40

So this is regularly happening to me, and I have a suspicion about why.

This always happens to me when I am working on a VM image and running qemu in my dev cycles (a highly likely thing to occur in a shell which launches BuildStream).

I also notice another side effect that `^C` fails to get handled in the interactive prompt, this could be because BuildStream fails to recognize that it is attached to the terminal and enable interactive mode.

My suspicion is that qemu modifies the terminal settings in some intrusive way which causes BuildStream to behave erratically, probably in the likely case that qemu was forcefully killed (I say likely, because when developing a fresh new VM image with BuildStream there are likely cycles where you get stuck and dont get as far as a login prompt).

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 7, 2019, 09:34

This can be fixed by either forcefully configuring the terminal at early startup, or bailing out with an early error requiring the user to reset their terminal.

I asked around in `#debian` to get the opinion of system integrators, and the few who answered my queries are more in favor of terminal apps which bail out instead of attempting to *"recover"* the terminal.

I am also more in favor of bailing out early because it means less responsibility for the app, and portably supporting terminal recovery doesnt sound like fun.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Mar 27, 2019, 08:22

mentioned in merge request !1176

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 10, 2019, 11:25

Looked further into this today, as it happened to me again (consequence of working on any bootable image which you start with `qemu -nographic ...`)

Seems that `click` does some funkiness when trying to open a stream in *"binary"* mode, [here](https://github.com/pallets/click/blob/master/click/_compat.py#L204).

Perhaps we should still just ignore that strangeness and ask `fcntl` if it's blocking, and error out nicely, rather than trying to manhandle the terminal.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @BenjaminSchubert]](https://gitlab.com/BenjaminSchubert) on Jun 10, 2019, 11:42

[[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) this doesn't seem to apply when not in binary mode, correct? Would we be able to not use binary mode?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 11, 2019, 07:56

> [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) this doesn't seem to apply when not in binary mode, correct? Would we be able to not use binary mode?

So essentially that line does the same thing (or a bit less) than what I had in !1176, i.e. if we *clear* the `O_NONBLOCK` bit from the underlying file handle using fcntl, then this stack trace goes away (even on subsequent runs of BuildStream which do *not* clear the bit).

But this is ugly as it means running BuildStream causes persistent side effects, and it shouldn't really be our business, as I mentioned in the few comments above, I don't think man handling the terminal is the right thing to do.

My thinking is that the right thing to do is something like this in the early initialization before any logging:

```python

   flags = fcntl.fcntl(fileno, fcntl.F_GETFL)
   if (flags & os.O_NONBLOCK) != 0:
       exit_with_nicer_user_facing_error()
```

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 11, 2019, 08:28

mentioned in commit 428eec3ed9066e59ccdaaa4efc894ad1c15f5d84

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 11, 2019, 08:29

mentioned in merge request !1389

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 11, 2019, 08:32

> My thinking is that the right thing to do is something like this in the early initialization before any logging:

Like I did in !1389 (currently bst-1.2 based)... any thoughts ?

Tested this and it does work locally on a terminal contaminated by `qemu -nographic`, not sure the error message is that great... the goal is to provide the user with some hint of what to do, rather than a rude stack trace.

FWIW:
* typing `reset` in the terminal does *not* fix the issue
* typeing `bash` in the terminal *does* fix the issue
* exiting the new shell does *not* cause the issue to come back (invoking `bash` the first time has modified the underlying file handle)

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 19, 2019, 14:38

mentioned in commit b2e3163dfbdad7aee327e2de531cb82745ee0ccb

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jun 19, 2019, 14:39

mentioned in merge request !1411

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @juergbi]](https://gitlab.com/juergbi) on Jun 19, 2019, 16:51

Seems sensible. If this happens with `qemu -nographic` without forceful termination, it would probably be good to also report this issue or submit a patch to qemu upstream. I'd expect qemu to restore terminal settings on exit.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 4, 2019, 14:45

mentioned in commit 41e02b3220fd90638e8dff0630f6ad296fc62a22

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 10, 2019, 09:14

mentioned in commit a6b0951da02188c62f6aea6b0ce3937ea5b092b7

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @tristanvb]](https://gitlab.com/tristanvb) on Jul 10, 2019, 09:17

mentioned in commit acf4962f0c010a0344e252ffacce741118a844a1

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 10, 2019, 09:55

closed via merge request !1411

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @marge-bot123]](https://gitlab.com/marge-bot123) on Jul 10, 2019, 09:55

mentioned in commit 199f080fac88fac1277541baec9def1c13afd048

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 15:11

mentioned in commit ef63500c37b23a475edfce452343f397ab1a576b

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @traveltissues]](https://gitlab.com/traveltissues) on Jul 10, 2019, 18:48

mentioned in commit 8b95ca18feef745455704466ce31be63781565d6

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @raoul]](https://gitlab.com/raoul).hidalgocharman on Jul 11, 2019, 12:06

mentioned in commit bb3bf9d275336cf3a55fb91669499b59299646e7
