### ISSUE TITLE
OSTree import fails with: Namespace OSTree not available

### ISSUE THREAD

**Issue by Cynical-Optimist** [buildstream-migration/bst-staging#952]
[See original issue on GitLab](https://gitlab.com/BuildStream/buildstream/-/issues/952)
In GitLab by [[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) on Mar 9, 2019, 20:10

## Summary

[//]: # (Summarize the bug encountered concisely)
Building any project with an ostree import fails with bst 1.2.4 from pypi.
For example https://gitlab.com/BuildStream/glade-demo, however any project with an import source ostree fails in the same way.

## Steps to reproduce

[//]: # (How one can reproduce the issue - this is very important)
```sh
git clone https://gitlab.com/BuildStream/glade-demo
cd glade-demo
bst build glade.bst
```

## What is the current bug behavior?

[//]: # (What actually happens)
See log below

## What is the expected correct behavior?

[//]: # (What you should see instead)

## Relevant logs and/or screenshots

[//]: # (Paste any relevant logs - please use code blocks ``` to format console output, logs, and code as it's hard to read otherwise. You can also add a Snippet and link it here. Check the markdown giude on Gitlab for further tips)

```sh
abcd[[Gitlab user @ares]](https://gitlab.com/ares):~/Projects/glade-demo$ bst build glade.bst 
[--:--:--][][] START   Build
[--:--:--][][] START   Loading elements
[00:00:00][][] SUCCESS Loading elements
[--:--:--][][] START   Resolving elements
[--:--:--][][] BUG     Namespace OSTree not available

    Traceback (most recent call last):
      File "/usr/bin/bst", line 8, in <module>
        sys.exit(cli())
      File "/usr/lib/python3/dist-packages/click/core.py", line 764, in __call__
        return self.main(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/buildstream/_frontend/cli.py", line 162, in override_main
        standalone_mode=standalone_mode, **extra)
      File "/usr/lib/python3/dist-packages/click/core.py", line 717, in main
        rv = self.invoke(ctx)
      File "/usr/lib/python3/dist-packages/click/core.py", line 1137, in invoke
        return _process_result(sub_ctx.command.invoke(sub_ctx))
      File "/usr/lib/python3/dist-packages/click/core.py", line 956, in invoke
        return ctx.invoke(self.callback, **ctx.params)
      File "/usr/lib/python3/dist-packages/click/core.py", line 555, in invoke
        return callback(*args, **kwargs)
      File "/usr/lib/python3/dist-packages/click/decorators.py", line 27, in new_func
        return f(get_current_context().obj, *args, **kwargs)
      File "/usr/lib/python3/dist-packages/buildstream/_frontend/cli.py", line 330, in build
        build_all=all_)
      File "/usr/lib/python3/dist-packages/buildstream/_stream.py", line 184, in build
        dynamic_plan=True)
      File "/usr/lib/python3/dist-packages/buildstream/_stream.py", line 871, in _load
        fetch_subprojects=fetch_subprojects)
      File "/usr/lib/python3/dist-packages/buildstream/_pipeline.py", line 111, in load
        fetch_subprojects=fetch_subprojects)
      File "/usr/lib/python3/dist-packages/buildstream/_project.py", line 321, in load_elements
        for meta in meta_elements
      File "/usr/lib/python3/dist-packages/buildstream/_project.py", line 321, in <listcomp>
        for meta in meta_elements
      File "/usr/lib/python3/dist-packages/buildstream/element.py", line 928, in _new_from_meta
        dependency = Element._new_from_meta(meta_dep, artifacts)
      File "/usr/lib/python3/dist-packages/buildstream/element.py", line 928, in _new_from_meta
        dependency = Element._new_from_meta(meta_dep, artifacts)
      File "/usr/lib/python3/dist-packages/buildstream/element.py", line 915, in _new_from_meta
        first_pass=meta.first_pass)
      File "/usr/lib/python3/dist-packages/buildstream/_project.py", line 249, in create_source
        return self.config.source_factory.create(self._context, self, meta)
      File "/usr/lib/python3/dist-packages/buildstream/_sourcefactory.py", line 60, in create
        source_type, _ = self.lookup(meta.kind)
      File "/usr/lib/python3/dist-packages/buildstream/_plugincontext.py", line 77, in lookup
        return self._ensure_plugin(kind)
      File "/usr/lib/python3/dist-packages/buildstream/_plugincontext.py", line 161, in _ensure_plugin
        self._types[kind] = self._load_plugin(source, kind, defaults)
      File "/usr/lib/python3/dist-packages/buildstream/_plugincontext.py", line 170, in _load_plugin
        plugin = source.load_plugin(kind)
      File "/usr/lib/python3/dist-packages/pluginbase.py", line 302, in load_plugin
        globals(), {}, ['__name__'])
      File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
        fromlist, level)
      File "/usr/lib/python3/dist-packages/buildstream/plugins/sources/ostree.py", line 57, in <module>
        from buildstream import _ostree
      File "/usr/lib/python3/dist-packages/pluginbase.py", line 439, in plugin_import
        fromlist, level)
      File "/usr/lib/python3/dist-packages/buildstream/_ostree.py", line 36, in <module>
        gi.require_version('OSTree', '1.0')
      File "/usr/lib/python3/dist-packages/gi/__init__.py", line 129, in require_version
        raise ValueError('Namespace %s not available' % namespace)
    ValueError: Namespace OSTree not available

```

## Possible fixes

[//]: # (If you can, link to the line of code that might be responsible for the problem)

## Other relevant information

[//]: # (Add the BuildStream version. Substitute below the "x" by "1", "2" or the right version. Add more than one version if necessary)

* BuildStream version affected: /milestone %BuildStream_v1.x

----

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) on Mar 9, 2019, 20:31

changed the description

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Mar 9, 2019, 20:40

[[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) have you installed the ostree dependencies as documented at https://buildstream.build/source_install.html#installing_dependencies ?

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) on Mar 9, 2019, 22:17

Hi, thanks for your answer. Your question just made me realize this is not the version from pypi but the debian package in buster. However I've also installed buildstream at work on an ubuntu 18:04 and there I've installed it from pypi. Both have the same problem.

What dependencies are actually needed? ostree is installed. The documented dependencies (Debian) on this site are installed on my system.

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Mar 9, 2019, 22:35

Hi [[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) The dependencies for the ostree plugin in Debian are:
- ostree
- gir1.2-ostree-1.0

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) on Mar 9, 2019, 23:12

That's it. Seems like gir1.2-ostree-1.0 is missing from the dependencies. Thanks.
Shouldn't this be automatically fetched in both versions (pypi and debian packages)?
regards
Marc

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Mar 9, 2019, 23:16

[[Gitlab user @mbodmer]](https://gitlab.com/mbodmer) agree that should be the case for debian packages (please file a bug there)

AFAIK the problem with pip is that you can not specify system dependencies, only python ones

I'm going to close this now; feel free to open another issue if you found any more problems

**Comment by Cynical-Optimist** [comment]
In GitLab by [[Gitlab user @jjardon]](https://gitlab.com/jjardon) on Mar 9, 2019, 23:16

closed
